import type { QuizQuestion } from "./quiz-types";

export const QUESTIONS_W2_W3: Record<string, QuizQuestion[]> = {

  // ── Skyline Heights — sh-1: "Why Save?" ──────────────────────────────────────
  "sh-1": [
    {
      id: "sh-1-q1", nodeId: "sh-1",
      textEn: "What is the primary purpose of an emergency fund?",
      textAr: "ما الغرض الأساسي من صندوق الطوارئ؟",
      choices: [
        { id: "a", textEn: "To invest in stocks during market dips",       textAr: "للاستثمار في الأسهم خلال تراجع السوق" },
        { id: "b", textEn: "Readily accessible cash for unexpected costs", textAr: "نقود متاحة للتكاليف غير المتوقعة"       },
        { id: "c", textEn: "A separate account for luxury spending",        textAr: "حساب منفصل للإنفاق الفاخر"              },
        { id: "d", textEn: "Money set aside only for medical bills",        textAr: "أموال مخصصة للفواتير الطبية فقط"        },
      ],
      correctId: "b",
      explanationCorrectEn: "An emergency fund is a liquid cash reserve for unexpected costs — job loss, car breakdown, medical bills. It must be instantly accessible, not locked in investments.",
      explanationCorrectAr: "صندوق الطوارئ احتياطي نقدي سائل للتكاليف غير المتوقعة — فقدان الوظيفة وأعطال السيارة والفواتير الطبية. يجب أن يكون متاحاً فوراً وليس محجوزاً في استثمارات.",
      explanationWrongEn: "Emergency funds are for unexpected costs, not investments or luxuries. The defining feature is that you can access the money the same day you need it.",
      explanationWrongAr: "صناديق الطوارئ مخصصة للتكاليف غير المتوقعة لا للاستثمارات أو الكماليات. السمة المميزة هي أنك تستطيع الوصول للمال في نفس اليوم الذي تحتاجه فيه.",
    },
    {
      id: "sh-1-q2", nodeId: "sh-1",
      textEn: "Financial experts typically recommend an emergency fund that covers how many months of expenses?",
      textAr: "يوصي الخبراء الماليون عموماً بأن يغطي صندوق الطوارئ كم شهراً من المصروفات؟",
      choices: [
        { id: "a", textEn: "2 weeks",   textAr: "أسبوعان"      },
        { id: "b", textEn: "1 month",   textAr: "شهر واحد"     },
        { id: "c", textEn: "3–6 months", textAr: "٣ إلى ٦ أشهر" },
        { id: "d", textEn: "2 years",   textAr: "سنتان"        },
      ],
      correctId: "c",
      explanationCorrectEn: "3–6 months of expenses is the widely recommended range. 3 months covers most short disruptions; 6 months is better if your income is variable or your job market is competitive.",
      explanationCorrectAr: "٣ إلى ٦ أشهر من المصروفات هو النطاق الموصى به على نطاق واسع. ٣ أشهر يغطي معظم الاضطرابات القصيرة؛ ٦ أشهر أفضل إذا كان دخلك متغيراً أو سوق العمل تنافسياً.",
      explanationWrongEn: "2 weeks is far too little — most job searches take months. 2 years is more than needed for most people and ties up too much cash.",
      explanationWrongAr: "أسبوعان غير كافٍ على الإطلاق — معظم عمليات البحث عن عمل تستغرق أشهراً. سنتان أكثر مما يحتاجه معظم الناس ويحبس الكثير من النقود.",
    },
    {
      id: "sh-1-q3", nodeId: "sh-1",
      textEn: "Omar spends AED 9,000/month. He wants a 3-month emergency fund. How much does he need to save?",
      textAr: "ينفق عمر ٩٬٠٠٠ درهم شهرياً. يريد صندوق طوارئ لمدة ٣ أشهر. كم يحتاج أن يدّخر؟",
      choices: [
        { id: "a", textEn: "AED 9,000",  textAr: "٩٬٠٠٠ درهم"  },
        { id: "b", textEn: "AED 18,000", textAr: "١٨٬٠٠٠ درهم" },
        { id: "c", textEn: "AED 27,000", textAr: "٢٧٬٠٠٠ درهم" },
        { id: "d", textEn: "AED 36,000", textAr: "٣٦٬٠٠٠ درهم" },
      ],
      correctId: "c",
      explanationCorrectEn: "AED 9,000 × 3 months = AED 27,000. Base your fund on expenses, not income — what you actually need to survive each month.",
      explanationCorrectAr: "٩٬٠٠٠ × ٣ أشهر = ٢٧٬٠٠٠ درهم. ابنِ صندوقك على المصروفات لا الدخل — ما تحتاجه فعلاً للعيش كل شهر.",
      explanationWrongEn: "Multiply monthly expenses by 3: AED 9,000 × 3 = AED 27,000. It's based on spending, not income.",
      explanationWrongAr: "اضرب المصروفات الشهرية في ٣: ٩٬٠٠٠ × ٣ = ٢٧٬٠٠٠ درهم. يستند إلى الإنفاق لا الدخل.",
    },
  ],

  // ── Skyline Heights — sh-2: "Building Your Fund" ──────────────────────────────
  "sh-2": [
    {
      id: "sh-2-q1", nodeId: "sh-2",
      textEn: "Layla wants to build a AED 21,000 emergency fund and can save AED 700/month. How many months will it take?",
      textAr: "تريد ليلى بناء صندوق طوارئ بقيمة ٢١٬٠٠٠ درهم ويمكنها ادخار ٧٠٠ درهم شهرياً. كم شهراً يستغرق ذلك؟",
      choices: [
        { id: "a", textEn: "15 months", textAr: "١٥ شهراً" },
        { id: "b", textEn: "21 months", textAr: "٢١ شهراً" },
        { id: "c", textEn: "30 months", textAr: "٣٠ شهراً" },
        { id: "d", textEn: "7 months",  textAr: "٧ أشهر"   },
      ],
      correctId: "c",
      explanationCorrectEn: "AED 21,000 ÷ AED 700/month = 30 months. This shows why increasing your savings rate — even slightly — makes a big difference to how fast you reach goals.",
      explanationCorrectAr: "٢١٬٠٠٠ ÷ ٧٠٠ = ٣٠ شهراً. هذا يوضح لماذا زيادة معدل ادخارك — ولو قليلاً — يحدث فرقاً كبيراً في مدى سرعة تحقيق الأهداف.",
      explanationWrongEn: "21,000 ÷ 700 = 30 months (2.5 years). The faster path: increase the monthly contribution.",
      explanationWrongAr: "٢١٬٠٠٠ ÷ ٧٠٠ = ٣٠ شهراً (٢.٥ سنة). الطريق الأسرع: زيادة المساهمة الشهرية.",
    },
    {
      id: "sh-2-q2", nodeId: "sh-2",
      textEn: "Where should you keep your emergency fund?",
      textAr: "أين يجب أن تحتفظ بصندوق الطوارئ؟",
      choices: [
        { id: "a", textEn: "Invested in stocks for higher returns",        textAr: "مستثمراً في الأسهم للحصول على عوائد أعلى" },
        { id: "b", textEn: "In a savings account you can access instantly", textAr: "في حساب ادخار يمكنك الوصول إليه فوراً"    },
        { id: "c", textEn: "In cryptocurrency for growth",                  textAr: "في العملات الرقمية للنمو"                   },
        { id: "d", textEn: "In a fixed-term deposit locked for 2 years",    textAr: "في وديعة لأجل مقفلة لمدة سنتين"           },
      ],
      correctId: "b",
      explanationCorrectEn: "Your emergency fund needs to be liquid — accessible the same day. Stocks and crypto can drop 50% right when you need the money most. Fixed deposits lock your cash when you need it most.",
      explanationCorrectAr: "يحتاج صندوق طوارئك أن يكون سائلاً — متاحاً في نفس اليوم. الأسهم والعملات الرقمية يمكن أن تنخفض ٥٠٪ في الوقت الذي تحتاج فيه المال أكثر.",
      explanationWrongEn: "Emergency funds must be instantly accessible. A regular savings account is ideal — don't sacrifice liquidity for returns on this money.",
      explanationWrongAr: "يجب أن تكون صناديق الطوارئ متاحة فوراً. حساب الادخار العادي مثالي — لا تضحِّ بالسيولة من أجل العوائد على هذه الأموال.",
    },
    {
      id: "sh-2-q3", nodeId: "sh-2",
      textEn: "Which of these is NOT a good reason to use your emergency fund?",
      textAr: "أيٌّ من التالي ليس سبباً جيداً لاستخدام صندوق طوارئك؟",
      choices: [
        { id: "a", textEn: "Sudden job loss",                      textAr: "فقدان مفاجئ للوظيفة"      },
        { id: "b", textEn: "Unexpected medical bill",              textAr: "فاتورة طبية غير متوقعة"    },
        { id: "c", textEn: "A flash sale at the electronics store", textAr: "تخفيضات في متجر الإلكترونيات" },
        { id: "d", textEn: "Car breakdown you need to get to work", textAr: "عطل في السيارة تحتاجها للعمل" },
      ],
      correctId: "c",
      explanationCorrectEn: "Sales are not emergencies — they're marketing tactics. True emergencies are unplanned, urgent, and necessary. A sale creates urgency artificially.",
      explanationCorrectAr: "التخفيضات ليست طوارئ — إنها تكتيكات تسويقية. الطوارئ الحقيقية غير مخطط لها وعاجلة وضرورية. التخفيض يخلق الإلحاح بشكل اصطناعي.",
      explanationWrongEn: "Job loss, medical bills, and essential car repairs are genuine emergencies. A sale is just a sale — it will come back, and your emergency fund shouldn't fund impulse buys.",
      explanationWrongAr: "فقدان الوظيفة والفواتير الطبية وإصلاحات السيارة الضرورية طوارئ حقيقية. التخفيض مجرد تخفيض — سيعود، وصندوق طوارئك لا يجب أن يموّل المشتريات الاندفاعية.",
    },
  ],

  // ── Skyline Heights — sh-5: "Savings Master" (boss) ──────────────────────────
  "sh-5": [
    {
      id: "sh-5-q1", nodeId: "sh-5",
      textEn: "Sara used her entire emergency fund for unexpected surgery. What should she do FIRST when she recovers?",
      textAr: "استخدمت سارة صندوق طوارئها بالكامل لعملية جراحية غير متوقعة. ماذا يجب أن تفعل أولاً بعد تعافيها؟",
      choices: [
        { id: "a", textEn: "Stop saving until finances fully stabilise",        textAr: "توقف عن الادخار حتى تستقر الماليات تماماً"   },
        { id: "b", textEn: "Immediately restart contributions to rebuild it",   textAr: "تبدأ فوراً بتجديد المساهمات لإعادة بنائه"    },
        { id: "c", textEn: "Take a personal loan to replenish the fund faster", textAr: "تأخذ قرضاً شخصياً لتجديد الصندوق بشكل أسرع" },
        { id: "d", textEn: "Invest the savings in stocks to recover faster",    textAr: "تستثمر المدخرات في الأسهم للتعافي بشكل أسرع" },
      ],
      correctId: "b",
      explanationCorrectEn: "Using an emergency fund is exactly what it's for. The moment you stabilise, restart contributions — even small ones. The fund did its job; now rebuild it.",
      explanationCorrectAr: "استخدام صندوق الطوارئ هو تماماً ما هو موجود من أجله. في اللحظة التي تستقر فيها، أعد بدء المساهمات — حتى الصغيرة منها. الصندوق أدى مهمته؛ الآن أعد بناءه.",
      explanationWrongEn: "The fund fulfilled its purpose. Don't take loans to replenish it — just restart regular contributions as soon as you can.",
      explanationWrongAr: "الصندوق حقق غرضه. لا تأخذ قروضاً لتجديده — فقط أعد المساهمات المنتظمة بأسرع ما يمكنك.",
    },
    {
      id: "sh-5-q2", nodeId: "sh-5",
      textEn: "Omar earns AED 15,000 and spends AED 10,000/month. If he saves the full difference, how many months to build a 6-month fund?",
      textAr: "يكسب عمر ١٥٬٠٠٠ درهم وينفق ١٠٬٠٠٠ درهم شهرياً. إذا ادّخر الفرق كاملاً، كم شهراً لبناء صندوق ٦ أشهر؟",
      choices: [
        { id: "a", textEn: "6 months",  textAr: "٦ أشهر"  },
        { id: "b", textEn: "10 months", textAr: "١٠ أشهر" },
        { id: "c", textEn: "12 months", textAr: "١٢ شهراً" },
        { id: "d", textEn: "18 months", textAr: "١٨ شهراً" },
      ],
      correctId: "c",
      explanationCorrectEn: "6-month fund target = AED 10,000 × 6 = AED 60,000. Monthly savings = AED 15,000 − AED 10,000 = AED 5,000. AED 60,000 ÷ AED 5,000 = 12 months.",
      explanationCorrectAr: "هدف صندوق ٦ أشهر = ١٠٬٠٠٠ × ٦ = ٦٠٬٠٠٠ درهم. المدخرات الشهرية = ١٥٬٠٠٠ − ١٠٬٠٠٠ = ٥٬٠٠٠ درهم. ٦٠٬٠٠٠ ÷ ٥٬٠٠٠ = ١٢ شهراً.",
      explanationWrongEn: "Fund needed = 10,000 × 6 = 60,000. He saves 5,000/month. 60,000 ÷ 5,000 = 12 months.",
      explanationWrongAr: "الصندوق المطلوب = ١٠٬٠٠٠ × ٦ = ٦٠٬٠٠٠. يدّخر ٥٬٠٠٠ شهرياً. ٦٠٬٠٠٠ ÷ ٥٬٠٠٠ = ١٢ شهراً.",
    },
    {
      id: "sh-5-q3", nodeId: "sh-5",
      textEn: "The 'pay yourself first' strategy applied to savings means:",
      textAr: "تعني استراتيجية 'ادفع لنفسك أولاً' المطبّقة على المدخرات:",
      choices: [
        { id: "a", textEn: "Spend freely and save whatever is left at month end",            textAr: "أنفق بحرية وادّخر ما تبقّى في نهاية الشهر"               },
        { id: "b", textEn: "Transfer a fixed amount to savings the moment your salary lands", textAr: "حوّل مبلغاً ثابتاً إلى المدخرات لحظة وصول راتبك"          },
        { id: "c", textEn: "Always prioritise loan repayment over savings",                  textAr: "أعطِ دائماً الأولوية لسداد القروض على المدخرات"            },
        { id: "d", textEn: "Negotiate your salary before saving anything",                   textAr: "تفاوض على راتبك قبل ادخار أي شيء"                        },
      ],
      correctId: "b",
      explanationCorrectEn: "Automate the transfer on payday before you see the money. What you don't see, you don't spend. This single habit builds more wealth than any investment tip.",
      explanationCorrectAr: "أتمت التحويل في يوم الراتب قبل أن ترى المال. ما لا تراه لا تنفقه. هذه العادة الواحدة تبني ثروة أكبر من أي نصيحة استثمارية.",
      explanationWrongEn: "Saving 'what's left' usually means nothing is left. Automate savings first, then spend the rest — not the other way around.",
      explanationWrongAr: "ادخار 'ما تبقّى' يعني عادةً أنه لا يتبقى شيء. أتمت المدخرات أولاً، ثم أنفق الباقي — وليس العكس.",
    },
  ],

  // ── Souk of Savings — sos-1: "Needs vs Wants" ────────────────────────────────
  "sos-1": [
    {
      id: "sos-1-q1", nodeId: "sos-1",
      textEn: "Which of the following is a 'need' rather than a 'want'?",
      textAr: "أيٌّ من التالي يُعدّ 'احتياجاً' وليس 'رغبة'؟",
      choices: [
        { id: "a", textEn: "The latest smartphone model",  textAr: "أحدث طراز هاتف ذكي"        },
        { id: "b", textEn: "Designer sunglasses",          textAr: "نظارات شمسية فاخرة"          },
        { id: "c", textEn: "Basic health insurance",       textAr: "تأمين صحي أساسي"             },
        { id: "d", textEn: "A streaming subscription",     textAr: "اشتراك خدمة بث"              },
      ],
      correctId: "c",
      explanationCorrectEn: "Health insurance is a need — it protects your ability to work and live. Smartphones, designer items, and subscriptions may be enjoyable but are not essential to survival.",
      explanationCorrectAr: "التأمين الصحي احتياج — يحمي قدرتك على العمل والعيش. الهواتف الذكية والسلع الفاخرة والاشتراكات قد تكون ممتعة لكنها ليست ضرورية للبقاء.",
      explanationWrongEn: "Needs are things you cannot reasonably live without: food, shelter, transport to work, basic healthcare. Wants improve life quality but aren't essential.",
      explanationWrongAr: "الاحتياجات هي أشياء لا يمكنك العيش بدونها: الطعام والمأوى والمواصلات للعمل والرعاية الصحية الأساسية. الرغبات تحسّن جودة الحياة لكنها ليست ضرورية.",
    },
    {
      id: "sos-1-q2", nodeId: "sos-1",
      textEn: "Reem sees a 70% off sale on shoes she doesn't need. Buying them would be:",
      textAr: "ترى ريم تخفيضاً بنسبة ٧٠٪ على أحذية لا تحتاجها. شراؤها سيكون:",
      choices: [
        { id: "a", textEn: "Always a good deal because the discount is high",        textAr: "دائماً صفقة جيدة لأن التخفيض عالٍ"          },
        { id: "b", textEn: "Spending money she didn't plan to spend",                textAr: "إنفاق مال لم تخطط لإنفاقه"                   },
        { id: "c", textEn: "Smart because it reduces future shopping trips",         textAr: "ذكي لأنه يقلل رحلات التسوق المستقبلية"       },
        { id: "d", textEn: "Counts as a need since it's discounted",                 textAr: "يُحسب احتياجاً لأنه مخفَّض السعر"             },
      ],
      correctId: "b",
      explanationCorrectEn: "A saving is only a saving if you were going to buy the item anyway. Buying something you don't need just because it's on sale is still spending — at any discount.",
      explanationCorrectAr: "التوفير توفير حقيقي فقط إذا كنت ستشتري السلعة على أي حال. شراء شيء لا تحتاجه فقط لأنه مخفَّض لا يزال إنفاقاً — بأي خصم.",
      explanationWrongEn: "A 70% discount doesn't save you money if you weren't planning to buy. You still spent 30% of the full price on something you didn't need.",
      explanationWrongAr: "خصم ٧٠٪ لا يوفّر لك المال إذا لم تكن تخطط للشراء. لا تزال قد أنفقت ٣٠٪ من السعر الكامل على شيء لم تحتجه.",
    },
    {
      id: "sos-1-q3", nodeId: "sos-1",
      textEn: "The concept of 'lifestyle inflation' means:",
      textAr: "يعني مفهوم 'التضخم الحياتي':",
      choices: [
        { id: "a", textEn: "Prices rising due to economic inflation",                       textAr: "ارتفاع الأسعار بسبب التضخم الاقتصادي"            },
        { id: "b", textEn: "Spending more as you earn more, without building more wealth",  textAr: "إنفاق المزيد كلما كسبت أكثر دون بناء ثروة أكبر" },
        { id: "c", textEn: "The rate at which living costs increase in cities",             textAr: "المعدل الذي ترتفع فيه تكاليف المعيشة في المدن"    },
        { id: "d", textEn: "Upgrading your insurance plan with each pay rise",              textAr: "ترقية خطة تأمينك مع كل زيادة راتب"                },
      ],
      correctId: "b",
      explanationCorrectEn: "Lifestyle inflation is when every pay rise gets consumed by bigger spending — new car, nicer apartment, more dining out. Your net worth doesn't grow even though you earn more.",
      explanationCorrectAr: "التضخم الحياتي هو عندما تُستهلك كل زيادة راتب بإنفاق أكبر — سيارة جديدة وشقة أفخم ومطاعم أكثر. لا تنمو ثروتك الصافية رغم أنك تكسب أكثر.",
      explanationWrongEn: "Lifestyle inflation means spending rises to match income, leaving nothing extra saved. The fix: bank at least half of every raise before adjusting your lifestyle.",
      explanationWrongAr: "التضخم الحياتي يعني ارتفاع الإنفاق ليتوافق مع الدخل دون ادخار إضافي. الحل: اودع في البنك على الأقل نصف كل زيادة راتب قبل تعديل أسلوب حياتك.",
    },
  ],

  // ── Souk of Savings — sos-2: "Value vs Price" ────────────────────────────────
  "sos-2": [
    {
      id: "sos-2-q1", nodeId: "sos-2",
      textEn: "A gym membership costs AED 200/month and Reem goes 20 times. A daily coffee habit costs AED 350/month (about AED 12/cup). Which is better value?",
      textAr: "عضوية النادي الرياضي تكلف ٢٠٠ درهم شهرياً وريم تذهب ٢٠ مرة. عادة القهوة اليومية تكلف ٣٥٠ درهم شهرياً (حوالي ١٢ درهم/كوب). أيهما أفضل قيمة؟",
      choices: [
        { id: "a", textEn: "Coffee — it's a daily habit so it brings daily value",    textAr: "القهوة — إنها عادة يومية تجلب قيمة يومية"        },
        { id: "b", textEn: "Gym — at AED 10/visit vs AED 12/cup, the gym wins",       textAr: "النادي — بـ١٠ درهم/زيارة مقابل ١٢ درهم/كوب، النادي يفوز" },
        { id: "c", textEn: "They are equal in value",                                  textAr: "قيمتهما متساوية"                                    },
        { id: "d", textEn: "Cannot be compared since they serve different purposes",   textAr: "لا يمكن مقارنتهما لأنهما يخدمان أغراضاً مختلفة"    },
      ],
      correctId: "b",
      explanationCorrectEn: "Gym: AED 200 ÷ 20 visits = AED 10/visit. Coffee: AED 350 ÷ ~29 cups = AED 12/cup. The gym delivers more value per dirham and has lasting health benefits.",
      explanationCorrectAr: "النادي: ٢٠٠ ÷ ٢٠ زيارة = ١٠ درهم/زيارة. القهوة: ٣٥٠ ÷ ~٢٩ كوباً = ١٢ درهم/كوب. النادي يقدم قيمة أكبر لكل درهم وله فوائد صحية دائمة.",
      explanationWrongEn: "Cost per use reveals value: gym is AED 10/visit vs coffee at AED 12/cup. Frequency of use matters — divide the total cost by how many times you use something.",
      explanationWrongAr: "التكلفة لكل استخدام تكشف القيمة: النادي ١٠ درهم/زيارة مقابل القهوة ١٢ درهم/كوب. تكرار الاستخدام مهم — اقسم التكلفة الإجمالية على عدد مرات الاستخدام.",
    },
    {
      id: "sos-2-q2", nodeId: "sos-2",
      textEn: "'Price anchoring' is a retail technique where:",
      textAr: "'تثبيت السعر' هو أسلوب بيع تجزئة حيث:",
      choices: [
        { id: "a", textEn: "Stores lower prices for loyalty card holders",                  textAr: "تخفّض المتاجر الأسعار لحاملي بطاقات الولاء"            },
        { id: "b", textEn: "A high original price makes the sale price seem more attractive", textAr: "السعر الأصلي المرتفع يجعل سعر البيع يبدو أكثر جاذبية" },
        { id: "c", textEn: "Prices are pegged to the country's inflation rate",              textAr: "تُربط الأسعار بمعدل التضخم في البلاد"                  },
        { id: "d", textEn: "Anchor stores offer the best discounts in a mall",              textAr: "المتاجر الرئيسية تقدم أفضل الخصومات في المول"          },
      ],
      correctId: "b",
      explanationCorrectEn: "A AED 2,000 jacket 'on sale' for AED 800 feels like a bargain because the AED 2,000 anchor is set first. The anchor may be inflated — always compare to actual market price.",
      explanationCorrectAr: "جاكيت بـ٢٠٠٠ درهم 'بتخفيض' بـ٨٠٠ درهم يبدو صفقة لأن مرساة ٢٠٠٠ تُحدد أولاً. المرساة قد تكون مبالغاً فيها — قارن دائماً بالسعر الفعلي في السوق.",
      explanationWrongEn: "Price anchoring uses a high reference price to make discounts seem bigger than they are. Always research the actual market value before buying.",
      explanationWrongAr: "تثبيت السعر يستخدم سعراً مرجعياً مرتفعاً لجعل الخصومات تبدو أكبر مما هي عليه. ابحث دائماً عن القيمة الفعلية في السوق قبل الشراء.",
    },
    {
      id: "sos-2-q3", nodeId: "sos-2",
      textEn: "Ahmed spends AED 150/month on subscriptions he never uses. Over 3 years, how much has he wasted?",
      textAr: "ينفق أحمد ١٥٠ درهماً شهرياً على اشتراكات لا يستخدمها. خلال ٣ سنوات، كم أهدر؟",
      choices: [
        { id: "a", textEn: "AED 1,800", textAr: "١٬٨٠٠ درهم" },
        { id: "b", textEn: "AED 3,600", textAr: "٣٬٦٠٠ درهم" },
        { id: "c", textEn: "AED 5,400", textAr: "٥٬٤٠٠ درهم" },
        { id: "d", textEn: "AED 4,500", textAr: "٤٬٥٠٠ درهم" },
      ],
      correctId: "c",
      explanationCorrectEn: "AED 150 × 12 months × 3 years = AED 5,400. Subscription audits — reviewing every recurring charge — are one of the easiest ways to find hidden savings.",
      explanationCorrectAr: "١٥٠ × ١٢ شهراً × ٣ سنوات = ٥٬٤٠٠ درهم. مراجعة الاشتراكات — فحص كل رسوم متكررة — من أسهل طرق العثور على مدخرات خفية.",
      explanationWrongEn: "150 per month × 36 months = AED 5,400. Do a subscription audit every 6 months to cancel anything you're not actively using.",
      explanationWrongAr: "١٥٠ شهرياً × ٣٦ شهراً = ٥٬٤٠٠ درهم. قم بمراجعة الاشتراكات كل ٦ أشهر لإلغاء أي شيء لا تستخدمه بنشاط.",
    },
  ],

  // ── Souk of Savings — sos-5: "Souk Boss" (boss) ──────────────────────────────
  "sos-5": [
    {
      id: "sos-5-q1", nodeId: "sos-5",
      textEn: "Nadia's grocery bill is AED 1,200/month at a premium supermarket. The same basket costs AED 780 at a regular supermarket. Annual saving by switching?",
      textAr: "فاتورة بقالة نادية ١٬٢٠٠ درهم شهرياً في سوبرماركت فاخر. نفس السلع بـ٧٨٠ درهم في سوبرماركت عادي. التوفير السنوي بالتبديل؟",
      choices: [
        { id: "a", textEn: "AED 420",   textAr: "٤٢٠ درهم"  },
        { id: "b", textEn: "AED 2,520", textAr: "٢٬٥٢٠ درهم" },
        { id: "c", textEn: "AED 5,040", textAr: "٥٬٠٤٠ درهم" },
        { id: "d", textEn: "AED 9,360", textAr: "٩٬٣٦٠ درهم" },
      ],
      correctId: "c",
      explanationCorrectEn: "(AED 1,200 − AED 780) × 12 = AED 420 × 12 = AED 5,040/year. That's enough to fully fund a 3-month emergency fund for many people — from one habit change.",
      explanationCorrectAr: "(١٬٢٠٠ − ٧٨٠) × ١٢ = ٤٢٠ × ١٢ = ٥٬٠٤٠ درهم/سنة. هذا يكفي لتمويل صندوق طوارئ كامل لمدة ٣ أشهر لكثير من الناس — من تغيير عادة واحدة.",
      explanationWrongEn: "Monthly saving = 1,200 − 780 = 420. Annual = 420 × 12 = AED 5,040. Small recurring decisions add up to very large annual numbers.",
      explanationWrongAr: "التوفير الشهري = ١٢٠٠ − ٧٨٠ = ٤٢٠. السنوي = ٤٢٠ × ١٢ = ٥٬٠٤٠ درهم. القرارات الصغيرة المتكررة تصل إلى أرقام سنوية كبيرة جداً.",
    },
    {
      id: "sos-5-q2", nodeId: "sos-5",
      textEn: "The '24-hour rule' in personal finance suggests:",
      textAr: "تقترح 'قاعدة الـ٢٤ ساعة' في التمويل الشخصي:",
      choices: [
        { id: "a", textEn: "Wait 24 hours before making ANY financial decision",          textAr: "انتظر ٢٤ ساعة قبل اتخاذ أي قرار مالي"            },
        { id: "b", textEn: "Wait 24 hours before non-essential impulse purchases",        textAr: "انتظر ٢٤ ساعة قبل المشتريات الاندفاعية غير الضرورية" },
        { id: "c", textEn: "Review your budget every 24 hours",                          textAr: "راجع ميزانيتك كل ٢٤ ساعة"                           },
        { id: "d", textEn: "Pay bills within 24 hours of receiving them",                textAr: "ادفع الفواتير خلال ٢٤ ساعة من استلامها"              },
      ],
      correctId: "b",
      explanationCorrectEn: "The 24-hour rule targets impulse buys. If you still want it the next day, the desire is likely genuine — not just triggered by a sale or a moment of boredom.",
      explanationCorrectAr: "قاعدة الـ٢٤ ساعة تستهدف المشتريات الاندفاعية. إذا لا تزال تريدها في اليوم التالي، فالرغبة على الأرجح حقيقية — وليس فقط بسبب تخفيض أو لحظة ملل.",
      explanationWrongEn: "The 24-hour pause targets impulsive, non-essential purchases. It doesn't apply to planned shopping, bill payments, or genuine emergencies.",
      explanationWrongAr: "توقف الـ٢٤ ساعة يستهدف المشتريات الاندفاعية غير الضرورية. لا ينطبق على التسوق المخطط أو دفع الفواتير أو الطوارئ الحقيقية.",
    },
    {
      id: "sos-5-q3", nodeId: "sos-5",
      textEn: "Which budgeting habit delivers the highest long-term financial benefit?",
      textAr: "أي عادة في الميزنة تقدم أعلى فائدة مالية على المدى الطويل؟",
      choices: [
        { id: "a", textEn: "Buying everything on sale only",                           textAr: "شراء كل شيء بالتخفيض فقط"                          },
        { id: "b", textEn: "Tracking every purchase and reviewing spending monthly",    textAr: "تتبع كل عملية شراء ومراجعة الإنفاق شهرياً"          },
        { id: "c", textEn: "Using credit cards for all purchases to earn rewards",      textAr: "استخدام بطاقات الائتمان لكل المشتريات لكسب المكافآت" },
        { id: "d", textEn: "Never dining out or spending on entertainment",             textAr: "عدم تناول الطعام خارجاً أو الإنفاق على الترفيه أبداً" },
      ],
      correctId: "b",
      explanationCorrectEn: "Tracking and reviewing spending is the cornerstone habit. You can't improve what you don't measure. Most people are surprised by what they find.",
      explanationCorrectAr: "تتبع ومراجعة الإنفاق هو عادة الأساس. لا يمكنك تحسين ما لا تقيسه. معظم الناس يُفاجأون بما يجدونه.",
      explanationWrongEn: "Awareness through tracking beats any single spending rule. Knowing your numbers is the foundation of every other financial improvement.",
      explanationWrongAr: "الوعي من خلال التتبع يتفوق على أي قاعدة إنفاق منفردة. معرفة أرقامك هي أساس كل تحسين مالي آخر.",
    },
  ],
};
