import type { QuizQuestion } from "./quiz-types";

export const QUESTIONS_W8_W9: Record<string, QuizQuestion[]> = {

  // ── Asset Atlas — aa-1: "What Is an Asset?" ───────────────────────────────────
  "aa-1": [
    {
      id: "aa-1-q1", nodeId: "aa-1",
      textEn: "In personal finance, an 'asset' is best described as:",
      textAr: "في التمويل الشخصي، 'الأصل' يُوصف بشكل أفضل بأنه:",
      choices: [
        { id: "a", textEn: "Any expense you pay regularly",                     textAr: "أي مصروف تدفعه بانتظام"                      },
        { id: "b", textEn: "Something that puts money in your pocket or grows in value", textAr: "شيء يضع مالاً في جيبك أو يرتفع في قيمته" },
        { id: "c", textEn: "A fixed monthly cost such as rent",                 textAr: "تكلفة شهرية ثابتة كالإيجار"                  },
        { id: "d", textEn: "Money you owe to others",                           textAr: "مال تدين به للآخرين"                          },
      ],
      correctId: "b",
      explanationCorrectEn: "Assets generate income or appreciate. Examples: rental property, stocks, bonds, gold. Liabilities do the opposite — they cost you money. Wealth = assets minus liabilities.",
      explanationCorrectAr: "الأصول تولّد دخلاً أو ترتفع في قيمتها. أمثلة: العقارات المؤجَّرة والأسهم والسندات والذهب. الالتزامات تفعل العكس — تكلّفك مالاً. الثروة = الأصول ناقص الالتزامات.",
      explanationWrongEn: "Assets = things that make money or grow in value. Liabilities = things that cost money. Your car is usually a liability (depreciates + running costs). A rental property is an asset.",
      explanationWrongAr: "الأصول = أشياء تُدرّ مالاً أو ترتفع في قيمتها. الالتزامات = أشياء تكلّف مالاً. سيارتك عادةً التزام (تتراجع قيمتها + تكاليف التشغيل). العقار المؤجَّر أصل.",
    },
    {
      id: "aa-1-q2", nodeId: "aa-1",
      textEn: "The concept of 'compound interest' means your money grows because:",
      textAr: "مفهوم 'الفائدة المركّبة' يعني أن مالك ينمو لأن:",
      choices: [
        { id: "a", textEn: "Interest is only paid on the original deposit amount",             textAr: "الفائدة تُدفع على مبلغ الإيداع الأصلي فقط"              },
        { id: "b", textEn: "Interest is earned on the original deposit AND previously earned interest", textAr: "الفائدة تُكسب على الإيداع الأصلي والفائدة المكتسبة سابقاً" },
        { id: "c", textEn: "The bank adds a fixed bonus each year",                           textAr: "البنك يضيف مكافأة ثابتة كل عام"                           },
        { id: "d", textEn: "Returns are always the same regardless of balance",               textAr: "العوائد دائماً نفسها بغض النظر عن الرصيد"                 },
      ],
      correctId: "b",
      explanationCorrectEn: "Compound interest = interest on interest. AED 10,000 at 7% grows to ~AED 19,672 in 10 years. At simple interest, it would only reach AED 17,000. Time amplifies the difference.",
      explanationCorrectAr: "الفائدة المركّبة = فائدة على فائدة. ١٠٬٠٠٠ درهم بـ٧٪ تنمو إلى ~١٩٬٦٧٢ في ١٠ سنوات. بالفائدة البسيطة ستصل فقط إلى ١٧٬٠٠٠. الوقت يضخّم الفرق.",
      explanationWrongEn: "Compound interest means you earn returns on your returns. It's the reason long investment horizons are so powerful — each year's growth builds on all previous years.",
      explanationWrongAr: "الفائدة المركّبة تعني أنك تكسب عوائد على عوائدك. هذا سبب قوة آفاق الاستثمار الطويلة — نمو كل عام يُبنى على جميع السنوات السابقة.",
    },
    {
      id: "aa-1-q3", nodeId: "aa-1",
      textEn: "Which of these is a LIABILITY, not an asset?",
      textAr: "أيٌّ من التالي التزام وليس أصلاً؟",
      choices: [
        { id: "a", textEn: "A savings account with AED 15,000",  textAr: "حساب ادخار بـ١٥٬٠٠٠ درهم"    },
        { id: "b", textEn: "Gold bullion worth AED 40,000",       textAr: "سبائك ذهب بقيمة ٤٠٬٠٠٠ درهم" },
        { id: "c", textEn: "A personal loan of AED 20,000",       textAr: "قرض شخصي ٢٠٬٠٠٠ درهم"        },
        { id: "d", textEn: "Shares in a UAE-listed company",      textAr: "أسهم في شركة مُدرجة في الإمارات" },
      ],
      correctId: "c",
      explanationCorrectEn: "A personal loan is money you OWE — it's a liability on your personal balance sheet. Savings, gold, and shares are assets because they have positive value.",
      explanationCorrectAr: "القرض الشخصي مال تدين به — إنه التزام في ميزانيتك الشخصية. المدخرات والذهب والأسهم أصول لأن لها قيمة إيجابية.",
      explanationWrongEn: "Savings, gold, and shares are assets (positive value you own). A personal loan is a liability (money you owe). Net worth = total assets − total liabilities.",
      explanationWrongAr: "المدخرات والذهب والأسهم أصول (قيمة إيجابية تمتلكها). القرض الشخصي التزام (مال تدين به). صافي الثروة = إجمالي الأصول − إجمالي الالتزامات.",
    },
  ],

  // ── Asset Atlas — aa-2: "Stocks, Bonds & Diversification" ─────────────────────
  "aa-2": [
    {
      id: "aa-2-q1", nodeId: "aa-2",
      textEn: "When you buy a company's stock, you become:",
      textAr: "عندما تشتري سهم شركة، أنت تصبح:",
      choices: [
        { id: "a", textEn: "A creditor who must be repaid first if the company fails",  textAr: "دائناً يجب سداده أولاً إذا أفلست الشركة"   },
        { id: "b", textEn: "A partial owner (shareholder) of the company",              textAr: "مالكاً جزئياً (مساهماً) في الشركة"          },
        { id: "c", textEn: "An employee eligible for stock options",                    textAr: "موظفاً مؤهلاً لخيارات الأسهم"               },
        { id: "d", textEn: "A guaranteed dividend recipient",                           textAr: "مستلماً مضموناً للأرباح"                    },
      ],
      correctId: "b",
      explanationCorrectEn: "Shareholders are partial owners. If the company does well, the stock price rises and you may get dividends. If it fails, shareholders are last to be paid — the highest risk.",
      explanationCorrectAr: "المساهمون ملّاك جزئيون. إذا سارت الشركة بشكل جيد، يرتفع سعر السهم وقد تحصل على أرباح. إذا أفلست، المساهمون آخر من يُدفع — الأعلى مخاطرة.",
      explanationWrongEn: "Stock = ownership. Bond = loan (you're the creditor). Owning stock means sharing in the company's successes and losses — more potential reward, more risk.",
      explanationWrongAr: "السهم = ملكية. السند = قرض (أنت الدائن). امتلاك سهم يعني المشاركة في نجاحات الشركة وخسائرها — مكافأة محتملة أكبر، مخاطرة أعبر.",
    },
    {
      id: "aa-2-q2", nodeId: "aa-2",
      textEn: "Bonds are generally considered _______ stocks in terms of risk:",
      textAr: "السندات تُعتبر عموماً _______ الأسهم من حيث المخاطرة:",
      choices: [
        { id: "a", textEn: "Much riskier than",          textAr: "أكثر خطورة بكثير من"         },
        { id: "b", textEn: "Less risky than",            textAr: "أقل خطورة من"               },
        { id: "c", textEn: "Equally risky as",           textAr: "بنفس خطورة"                 },
        { id: "d", textEn: "Riskier than, but safer in recessions", textAr: "أكثر خطورة من، لكن أأمن في فترات الركود" },
      ],
      correctId: "b",
      explanationCorrectEn: "Bonds are loans to a government or company — you're the creditor, with legal priority over shareholders. Lower risk, lower return. Stocks offer higher potential but can drop to zero.",
      explanationCorrectAr: "السندات قروض لحكومة أو شركة — أنت الدائن، بأولوية قانونية على المساهمين. مخاطرة أقل وعائد أقل. الأسهم تقدم إمكانات أعلى لكن يمكن أن تنخفض إلى الصفر.",
      explanationWrongEn: "Bonds = lower risk, lower return. Stocks = higher risk, higher potential return. A diversified portfolio holds both to balance risk and growth.",
      explanationWrongAr: "السندات = مخاطرة أقل، عائد أقل. الأسهم = مخاطرة أعلى، إمكانات عائد أعلى. المحفظة المتنوعة تضم كليهما لتوازن المخاطرة والنمو.",
    },
    {
      id: "aa-2-q3", nodeId: "aa-2",
      textEn: "'Diversification' in investing is the practice of:",
      textAr: "'التنويع' في الاستثمار هو ممارسة:",
      choices: [
        { id: "a", textEn: "Putting all money in the best-performing single asset",        textAr: "وضع كل المال في أفضل أصل أداءً منفرد"          },
        { id: "b", textEn: "Spreading investments across different assets to reduce risk", textAr: "توزيع الاستثمارات على أصول مختلفة لتقليل المخاطر" },
        { id: "c", textEn: "Switching investments frequently to catch market trends",     textAr: "تغيير الاستثمارات بشكل متكرر للحاق بتوجهات السوق" },
        { id: "d", textEn: "Diversifying the currencies you hold only",                   textAr: "تنويع العملات التي تحتفظ بها فقط"                },
      ],
      correctId: "b",
      explanationCorrectEn: "Don't put all eggs in one basket. If one asset crashes, others may hold up. A diversified portfolio of stocks, bonds, and real estate smooths out volatility over time.",
      explanationCorrectAr: "لا تضع كل البيض في سلة واحدة. إذا انهار أصل واحد، قد يصمد الآخرون. محفظة متنوعة من الأسهم والسندات والعقارات تخفّف التذبذب مع الوقت.",
      explanationWrongEn: "Diversification reduces the risk of any single investment ruining your portfolio. You sacrifice the maximum possible return, but you also avoid the maximum possible loss.",
      explanationWrongAr: "التنويع يقلل خطر أن يُدمّر استثمار واحد محفظتك. تتخلى عن الحد الأقصى للعائد الممكن، لكنك أيضاً تتجنب الحد الأقصى للخسارة الممكنة.",
    },
  ],

  // ── Asset Atlas — aa-5: "Investment Boss" (boss) ─────────────────────────────
  "aa-5": [
    {
      id: "aa-5-q1", nodeId: "aa-5",
      textEn: "Hana invests AED 10,000 at 7% annual return, compounded yearly. After 10 years she has approximately:",
      textAr: "تستثمر هانا ١٠٬٠٠٠ درهم بعائد سنوي ٧٪، مركّب سنوياً. بعد ١٠ سنوات لديها تقريباً:",
      choices: [
        { id: "a", textEn: "AED 14,000", textAr: "١٤٬٠٠٠ درهم" },
        { id: "b", textEn: "AED 17,000", textAr: "١٧٬٠٠٠ درهم" },
        { id: "c", textEn: "AED 19,672", textAr: "١٩٬٦٧٢ درهم" },
        { id: "d", textEn: "AED 21,000", textAr: "٢١٬٠٠٠ درهم" },
      ],
      correctId: "c",
      explanationCorrectEn: "10,000 × (1.07)^10 ≈ AED 19,672. That's nearly double without adding a single dirham — purely from compound growth. Start early; time is your most powerful tool.",
      explanationCorrectAr: "١٠٬٠٠٠ × (١.٠٧)^١٠ ≈ ١٩٬٦٧٢ درهم. هذا ضعف تقريباً دون إضافة درهم واحد — من النمو المركّب بحتاً. ابدأ مبكراً؛ الوقت أقوى أدواتك.",
      explanationWrongEn: "10,000 × 1.07^10 ≈ 19,672. The 'rule of 72': divide 72 by the interest rate to estimate doubling time. At 7%: 72÷7 ≈ 10 years — exactly this example.",
      explanationWrongAr: "١٠٬٠٠٠ × ١.٠٧^١٠ ≈ ١٩٬٦٧٢. 'قاعدة ٧٢': اقسم ٧٢ على معدل الفائدة لتقدير وقت التضاعف. عند ٧٪: ٧٢÷٧ ≈ ١٠ سنوات — تماماً هذا المثال.",
    },
    {
      id: "aa-5-q2", nodeId: "aa-5",
      textEn: "An 'index fund' investment strategy involves:",
      textAr: "استراتيجية استثمار 'صندوق المؤشر' تتضمن:",
      choices: [
        { id: "a", textEn: "Picking individual winning stocks based on research",    textAr: "اختيار أسهم فردية رابحة بناءً على البحث"         },
        { id: "b", textEn: "Replicating a market index like the S&P 500",            textAr: "محاكاة مؤشر سوقي مثل S&P 500"                   },
        { id: "c", textEn: "Investing only in government bonds",                     textAr: "الاستثمار فقط في السندات الحكومية"               },
        { id: "d", textEn: "Active daily trading to beat the market",               textAr: "تداول يومي نشط للتفوق على السوق"                 },
      ],
      correctId: "b",
      explanationCorrectEn: "Index funds track a market index — you own a tiny slice of hundreds of companies. Low cost, passive, diversified. Most active fund managers fail to beat index funds long-term.",
      explanationCorrectAr: "صناديق المؤشر تتتبع مؤشراً سوقياً — تمتلك شريحة صغيرة من مئات الشركات. منخفضة التكلفة وسلبية ومتنوعة. معظم مديري الصناديق النشطة يفشلون في التفوق على صناديق المؤشر على المدى الطويل.",
      explanationWrongEn: "Index funds = buy and hold the whole market at minimal cost. Research shows most active managers underperform their benchmark index over 10+ years.",
      explanationWrongAr: "صناديق المؤشر = اشترِ واحتفظ بالسوق كله بأدنى تكلفة. تُظهر الأبحاث أن معظم المديرين النشطين يؤدون أداءً أدنى من مؤشرهم المرجعي على مدى ١٠+ سنوات.",
    },
    {
      id: "aa-5-q3", nodeId: "aa-5",
      textEn: "'Dirham-cost averaging' means:",
      textAr: "'متوسط تكلفة الدرهم' يعني:",
      choices: [
        { id: "a", textEn: "Converting all savings to USD for currency stability",           textAr: "تحويل كل المدخرات إلى دولار لاستقرار العملة"               },
        { id: "b", textEn: "Investing a fixed amount regularly, regardless of market price", textAr: "استثمار مبلغ ثابت بانتظام بغض النظر عن سعر السوق"       },
        { id: "c", textEn: "Only buying investments when markets are at their lowest",       textAr: "شراء الاستثمارات فقط عندما تكون الأسواق في أدنى مستوياتها" },
        { id: "d", textEn: "Selling investments when prices drop to cut losses",            textAr: "بيع الاستثمارات عند انخفاض الأسعار لتقليل الخسائر"        },
      ],
      correctId: "b",
      explanationCorrectEn: "Investing AED 500/month regardless of price means you buy more shares when prices fall and fewer when prices rise. Over time, this averages out entry cost — removing the need to 'time the market'.",
      explanationCorrectAr: "استثمار ٥٠٠ درهم/شهر بغض النظر عن السعر يعني شراء أسهم أكثر عندما تنخفض الأسعار وأقل عندما ترتفع. مع الوقت، يعدّل هذا تكلفة الدخول — يزيل الحاجة إلى 'توقيت السوق'.",
      explanationWrongEn: "Dollar/dirham-cost averaging = invest consistently, same amount, same schedule. You naturally buy more when cheap and less when expensive — a built-in advantage.",
      explanationWrongAr: "متوسط تكلفة الدولار/الدرهم = استثمر باستمرار، نفس المبلغ، نفس الجدول. تشتري تلقائياً أكثر عندما تكون رخيصة وأقل عندما تكون غالية — ميزة متأصّلة.",
    },
  ],

  // ── Skyline Keys — sk-1: "Rent vs Buy" ───────────────────────────────────────
  "sk-1": [
    {
      id: "sk-1-q1", nodeId: "sk-1",
      textEn: "The MOST important factor when deciding to rent vs buy in the UAE is:",
      textAr: "أهم عامل عند اتخاذ قرار الإيجار مقابل الشراء في الإمارات:",
      choices: [
        { id: "a", textEn: "The colour of the building's exterior",           textAr: "لون واجهة المبنى"                             },
        { id: "b", textEn: "Whether the developer has a famous brand name",   textAr: "هل المطور لديه اسم علامة تجارية مشهور"        },
        { id: "c", textEn: "How long you plan to stay in the UAE",            textAr: "المدة التي تخطط للبقاء فيها في الإمارات"      },
        { id: "d", textEn: "Whether the apartment has a sea view",            textAr: "هل الشقة تطل على البحر"                       },
      ],
      correctId: "c",
      explanationCorrectEn: "Buying in the UAE involves transaction costs of ~7–8% (DLD fees, mortgage fees, agent fees). You need enough time to offset these costs with capital growth. Under 3–5 years? Renting often wins.",
      explanationCorrectAr: "الشراء في الإمارات ينطوي على تكاليف معاملات ~٧–٨٪ (رسوم دائرة الأراضي ورسوم الرهن ورسوم الوكيل). تحتاج وقتاً كافياً لتعويض هذه التكاليف بنمو رأس المال. أقل من ٣–٥ سنوات؟ الإيجار غالباً يفوز.",
      explanationWrongEn: "Tenure is king. Transaction costs in Dubai are ~7–8%. If you're staying less than 3–5 years, renting is almost always cheaper after accounting for all costs.",
      explanationWrongAr: "المدة هي الملك. تكاليف المعاملات في دبي ~٧–٨٪. إذا كنت ستبقى أقل من ٣–٥ سنوات، الإيجار دائماً تقريباً أرخص بعد احتساب جميع التكاليف.",
    },
    {
      id: "sk-1-q2", nodeId: "sk-1",
      textEn: "In Dubai, expatriates CAN purchase freehold property in designated areas. This means:",
      textAr: "في دبي، يمكن للأجانب شراء عقارات تملّك حر في مناطق محددة. هذا يعني:",
      choices: [
        { id: "a", textEn: "They can only rent, never truly own",                    textAr: "يمكنهم الإيجار فقط وليس التملّك حقاً"            },
        { id: "b", textEn: "They own the property and land outright",                textAr: "يمتلكون العقار والأرض بشكل كامل"                 },
        { id: "c", textEn: "They lease for 99 years only",                           textAr: "يؤجّرون لمدة ٩٩ عاماً فقط"                      },
        { id: "d", textEn: "Only Muslims can buy freehold property in the UAE",      textAr: "المسلمون فقط يمكنهم شراء عقارات تملّك حر في الإمارات" },
      ],
      correctId: "b",
      explanationCorrectEn: "Freehold = full ownership of property and land. Dubai has ~50+ designated freehold areas open to non-nationals. This makes Dubai one of the most accessible property markets in the Gulf.",
      explanationCorrectAr: "التملّك الحر = ملكية كاملة للعقار والأرض. تضم دبي أكثر من ٥٠ منطقة تملّك حر مفتوحة لغير المواطنين. هذا يجعل دبي من أكثر أسواق العقارات سهولة في الوصول بالخليج.",
      explanationWrongEn: "Freehold = full legal ownership. Unlike leasehold (99 years), freehold gives you the land too. Dubai has many designated freehold areas open to expatriates.",
      explanationWrongAr: "التملّك الحر = ملكية قانونية كاملة. خلافاً لحق الانتفاع (٩٩ عاماً)، التملّك الحر يمنحك الأرض أيضاً. دبي لديها مناطق تملّك حر عديدة مفتوحة للأجانب.",
    },
    {
      id: "sk-1-q3", nodeId: "sk-1",
      textEn: "Annual rent for an apartment is AED 72,000. Purchase price: AED 1.44 million. What is the price-to-rent ratio?",
      textAr: "الإيجار السنوي لشقة ٧٢٬٠٠٠ درهم. سعر الشراء: ١.٤٤ مليون درهم. ما نسبة السعر إلى الإيجار؟",
      choices: [
        { id: "a", textEn: "10", textAr: "١٠" },
        { id: "b", textEn: "15", textAr: "١٥" },
        { id: "c", textEn: "20", textAr: "٢٠" },
        { id: "d", textEn: "25", textAr: "٢٥" },
      ],
      correctId: "c",
      explanationCorrectEn: "1,440,000 ÷ 72,000 = 20. A ratio above 20 generally favours renting; below 15 favours buying. At 20, it's a borderline call — tenure and mortgage rate matter.",
      explanationCorrectAr: "١٬٤٤٠٬٠٠٠ ÷ ٧٢٬٠٠٠ = ٢٠. نسبة فوق ٢٠ تفضّل عموماً الإيجار؛ تحت ١٥ تفضّل الشراء. عند ٢٠، القرار حدّي — المدة ومعدل الرهن مهمان.",
      explanationWrongEn: "Price-to-rent = purchase price ÷ annual rent = 1,440,000 ÷ 72,000 = 20. Above 20 typically favours renting in most markets.",
      explanationWrongAr: "نسبة السعر إلى الإيجار = سعر الشراء ÷ الإيجار السنوي = ١٬٤٤٠٬٠٠٠ ÷ ٧٢٬٠٠٠ = ٢٠. فوق ٢٠ يفضّل عادةً الإيجار في معظم الأسواق.",
    },
  ],

  // ── Skyline Keys — sk-2: "Mortgages & Financing" ─────────────────────────────
  "sk-2": [
    {
      id: "sk-2-q1", nodeId: "sk-2",
      textEn: "The Dubai Land Department (DLD) transfer fee when buying property in Dubai is:",
      textAr: "رسوم نقل الملكية لدائرة الأراضي والأملاك في دبي عند شراء عقار:",
      choices: [
        { id: "a", textEn: "1%", textAr: "١٪" },
        { id: "b", textEn: "2%", textAr: "٢٪" },
        { id: "c", textEn: "4%", textAr: "٤٪" },
        { id: "d", textEn: "6%", textAr: "٦٪" },
      ],
      correctId: "c",
      explanationCorrectEn: "DLD transfer fee = 4% of the purchase price. On a AED 1M property, that's AED 40,000 in fees alone. Add mortgage fees (~1%), agent fee (~2%), and registration — buying is expensive upfront.",
      explanationCorrectAr: "رسوم نقل دائرة الأراضي = ٤٪ من سعر الشراء. على عقار بـ١ مليون درهم، هذا ٤٠٬٠٠٠ درهم رسوماً فقط. أضف رسوم الرهن (~١٪) ورسوم الوكيل (~٢٪) والتسجيل — الشراء مكلف مسبقاً.",
      explanationWrongEn: "DLD fee = 4% in Dubai. On a AED 2M property: AED 80,000 just in transfer fees. These upfront costs are why you need to stay long enough to benefit.",
      explanationWrongAr: "رسوم دائرة الأراضي = ٤٪ في دبي. على عقار بـ٢ مليون درهم: ٨٠٬٠٠٠ درهم رسوم نقل فقط. هذه التكاليف المسبقة هي سبب حاجتك للبقاء طويلاً بما يكفي للاستفادة.",
    },
    {
      id: "sk-2-q2", nodeId: "sk-2",
      textEn: "For expatriate first-time buyers of properties under AED 5 million, the maximum Loan-to-Value (LTV) in the UAE is typically:",
      textAr: "لأول مشترٍ أجنبي لعقارات أقل من ٥ ملايين درهم، الحد الأقصى لنسبة القرض إلى القيمة في الإمارات عادةً:",
      choices: [
        { id: "a", textEn: "60%", textAr: "٦٠٪" },
        { id: "b", textEn: "75%", textAr: "٧٥٪" },
        { id: "c", textEn: "80%", textAr: "٨٠٪" },
        { id: "d", textEn: "90%", textAr: "٩٠٪" },
      ],
      correctId: "b",
      explanationCorrectEn: "UAE Central Bank caps expat first-time buyer LTV at 80% for under AED 5M — meaning a minimum 20% down payment. The 75% option often comes from banks offering slightly conservative terms.",
      explanationCorrectAr: "يُحدد البنك المركزي الإماراتي نسبة القرض إلى القيمة للمشتري الأجنبي لأول مرة بـ٨٠٪ لأقل من ٥ ملايين درهم — مما يعني دفعة أولى لا تقل عن ٢٠٪.",
      explanationWrongEn: "UAE Central Bank rules: expats can borrow up to 80% LTV for their first property under AED 5M. This means a minimum 20% down payment required.",
      explanationWrongAr: "قواعد البنك المركزي الإماراتي: يمكن للأجانب اقتراض حتى ٨٠٪ من القيمة لأول عقار أقل من ٥ ملايين درهم. هذا يعني دفعة أولى لا تقل عن ٢٠٪.",
    },
    {
      id: "sk-2-q3", nodeId: "sk-2",
      textEn: "An off-plan property purchase in the UAE means:",
      textAr: "شراء عقار على الخارطة في الإمارات يعني:",
      choices: [
        { id: "a", textEn: "Buying a fully completed, ready-to-move-in property",      textAr: "شراء عقار مكتمل تماماً جاهز للسكن"                  },
        { id: "b", textEn: "Buying based on developer plans before construction is done", textAr: "الشراء بناءً على خطط المطور قبل اكتمال البناء"     },
        { id: "c", textEn: "A rent-to-own arrangement over 5 years",                   textAr: "ترتيب إيجار مع خيار شراء على ٥ سنوات"               },
        { id: "d", textEn: "Purchasing only commercial property",                      textAr: "شراء العقارات التجارية فقط"                          },
      ],
      correctId: "b",
      explanationCorrectEn: "Off-plan = buying from a plan/model before the building exists. Potential upside: lower price and capital growth during construction. Risks: delays, developer insolvency, finished product differing from plans.",
      explanationCorrectAr: "على الخارطة = الشراء من خطة/نموذج قبل وجود المبنى. الإيجابيات المحتملة: سعر أقل ونمو رأس مال أثناء البناء. المخاطر: تأخيرات وإعسار المطور واختلاف المنتج النهائي عن الخطط.",
      explanationWrongEn: "Off-plan = pre-construction purchase. Positives: often lower price with instalments during construction. Negatives: completion risk, developer risk, no guaranteed delivery date.",
      explanationWrongAr: "على الخارطة = شراء قبل البناء. الإيجابيات: سعر أقل في الغالب مع أقساط أثناء البناء. السلبيات: مخاطر الإتمام والمطور وعدم وجود تاريخ تسليم مضمون.",
    },
  ],

  // ── Skyline Keys — sk-5: "Real Estate Boss" (boss) ───────────────────────────
  "sk-5": [
    {
      id: "sk-5-q1", nodeId: "sk-5",
      textEn: "A mortgage on AED 900,000 at 4.5% over 25 years has a monthly payment of ~AED 5,000. Total amount paid over the full term?",
      textAr: "رهن على ٩٠٠٬٠٠٠ درهم بـ٤.٥٪ لمدة ٢٥ عاماً بقسط شهري ~٥٬٠٠٠ درهم. إجمالي المبلغ المدفوع على مدى المدة الكاملة؟",
      choices: [
        { id: "a", textEn: "AED 900,000",   textAr: "٩٠٠٬٠٠٠ درهم"   },
        { id: "b", textEn: "AED 1,200,000", textAr: "١٬٢٠٠٬٠٠٠ درهم" },
        { id: "c", textEn: "AED 1,500,000", textAr: "١٬٥٠٠٬٠٠٠ درهم" },
        { id: "d", textEn: "AED 1,800,000", textAr: "١٬٨٠٠٬٠٠٠ درهم" },
      ],
      correctId: "c",
      explanationCorrectEn: "AED 5,000 × 12 months × 25 years = AED 1,500,000. You pay AED 600,000 in interest on a AED 900,000 loan. This is why making extra payments early saves significant money.",
      explanationCorrectAr: "٥٬٠٠٠ × ١٢ × ٢٥ = ١٬٥٠٠٬٠٠٠ درهم. تدفع ٦٠٠٬٠٠٠ درهم فائدة على قرض ٩٠٠٬٠٠٠ درهم. لهذا السبب الدفعات الإضافية المبكرة توفّر مالاً كبيراً.",
      explanationWrongEn: "5,000/month × 12 × 25 = 1,500,000. The extra 600,000 beyond the principal is pure interest. Making one extra payment per year can reduce a 25-year mortgage to ~22 years.",
      explanationWrongAr: "٥٬٠٠٠/شهر × ١٢ × ٢٥ = ١٬٥٠٠٬٠٠٠. الـ٦٠٠٬٠٠٠ الإضافية فوق رأس المال فائدة صرفة. دفعة إضافية واحدة سنوياً يمكن أن تخفّض رهن ٢٥ عاماً إلى ~٢٢ عاماً.",
    },
    {
      id: "sk-5-q2", nodeId: "sk-5",
      textEn: "'Negative equity' in real estate occurs when:",
      textAr: "يحدث 'السلبي في حقوق الملكية' في العقارات عندما:",
      choices: [
        { id: "a", textEn: "You make a profit when property values fall",                   textAr: "تحقق ربحاً عند انخفاض قيم العقارات"                     },
        { id: "b", textEn: "You owe more on your mortgage than the property is worth",      textAr: "تدين برهن أكثر مما تستحقه العقارة"                      },
        { id: "c", textEn: "Your rental income exceeds your mortgage payment",              textAr: "دخلك من الإيجار يتجاوز قسط الرهن"                       },
        { id: "d", textEn: "The property generates negative cash flow only in year one",    textAr: "العقار يولّد تدفقاً نقدياً سلبياً في السنة الأولى فقط"   },
      ],
      correctId: "b",
      explanationCorrectEn: "Negative equity = mortgage > current property value. If you need to sell, you can't cover the loan. This is why a large down payment provides a buffer against market declines.",
      explanationCorrectAr: "السلبي في حقوق الملكية = الرهن > القيمة الحالية للعقار. إذا احتجت للبيع، لا يمكنك تغطية القرض. لهذا السبب الدفعة الأولى الكبيرة توفّر هامش أمان ضد انخفاض السوق.",
      explanationWrongEn: "Negative equity = owe more than it's worth. If property drops from AED 1M to AED 750K but your mortgage is AED 850K, you're AED 100K underwater. Big down payments reduce this risk.",
      explanationWrongAr: "السلبي في حقوق الملكية = تدين بأكثر مما تستحقه. إذا انخفض العقار من ١ مليون إلى ٧٥٠ ألف لكن رهنك ٨٥٠ ألف، أنت غارق بـ١٠٠ ألف. الدفعات الأولى الكبيرة تقلل هذه المخاطرة.",
    },
    {
      id: "sk-5-q3", nodeId: "sk-5",
      textEn: "Buying an AED 1.5M property with 20% down in Dubai. Total upfront cash needed (including 4% DLD + ~1% mortgage fee + ~2% agent fee)?",
      textAr: "شراء عقار بـ١.٥ مليون درهم بدفعة أولى ٢٠٪ في دبي. إجمالي النقد المطلوب مقدماً (شاملاً ٤٪ دائرة الأراضي + ~١٪ رسوم رهن + ~٢٪ رسوم وكيل)؟",
      choices: [
        { id: "a", textEn: "AED 300,000", textAr: "٣٠٠٬٠٠٠ درهم" },
        { id: "b", textEn: "AED 360,000", textAr: "٣٦٠٬٠٠٠ درهم" },
        { id: "c", textEn: "AED 405,000", textAr: "٤٠٥٬٠٠٠ درهم" },
        { id: "d", textEn: "AED 450,000", textAr: "٤٥٠٬٠٠٠ درهم" },
      ],
      correctId: "c",
      explanationCorrectEn: "Down payment: 20% × 1.5M = 300,000. DLD: 4% × 1.5M = 60,000. Mortgage fee: 1% × 1.2M = 12,000. Agent: 2% × 1.5M = 30,000. Approx. total: ~AED 402,000–405,000.",
      explanationCorrectAr: "الدفعة الأولى: ٢٠٪ × ١.٥ مليون = ٣٠٠٬٠٠٠. دائرة الأراضي: ٤٪ × ١.٥ مليون = ٦٠٬٠٠٠. رسوم الرهن: ١٪ × ١.٢ مليون = ١٢٬٠٠٠. الوكيل: ٢٪ × ١.٥ مليون = ٣٠٬٠٠٠. الإجمالي التقريبي: ~٤٠٢٬٠٠٠–٤٠٥٬٠٠٠ درهم.",
      explanationWrongEn: "Down payment (300K) + DLD (60K) + mortgage fee (12K) + agent (30K) ≈ AED 402,000. Never budget just the down payment — transaction costs add 7–8% to the purchase price.",
      explanationWrongAr: "الدفعة الأولى (٣٠٠ ألف) + دائرة الأراضي (٦٠ ألف) + رسوم الرهن (١٢ ألف) + الوكيل (٣٠ ألف) ≈ ٤٠٢٬٠٠٠ درهم. لا تضع ميزانية بالدفعة الأولى فقط — تكاليف المعاملات تضيف ٧–٨٪ من سعر الشراء.",
    },
  ],
};
