import type { QuizQuestion } from "./quiz-types";

export const QUESTIONS_W6_W7: Record<string, QuizQuestion[]> = {

  // ── Card Canyon — cc-1: "Credit Card Basics" ─────────────────────────────────
  "cc-1": [
    {
      id: "cc-1-q1", nodeId: "cc-1",
      textEn: "What happens if you pay only the minimum payment on your credit card each month?",
      textAr: "ماذا يحدث إذا دفعت الحد الأدنى فقط على بطاقتك الائتمانية كل شهر؟",
      choices: [
        { id: "a", textEn: "Your balance decreases quickly",                        textAr: "رصيدك ينخفض بسرعة"                               },
        { id: "b", textEn: "You avoid all interest charges",                        textAr: "تتجنب جميع رسوم الفائدة"                          },
        { id: "c", textEn: "Interest accrues on the remaining balance, costing far more", textAr: "تتراكم الفائدة على الرصيد المتبقي بتكلفة أعلى بكثير" },
        { id: "d", textEn: "The bank rewards you with a lower interest rate",       textAr: "يكافئك البنك بمعدل فائدة أقل"                     },
      ],
      correctId: "c",
      explanationCorrectEn: "Minimum payments barely cover the interest. Most of your balance stays, accruing more interest. A AED 5,000 balance at 36% APR paying only AED 200/month takes years to clear.",
      explanationCorrectAr: "المدفوعات الدنيا بالكاد تغطي الفائدة. معظم رصيدك يبقى، تتراكم عليه فائدة أكثر. رصيد ٥٬٠٠٠ درهم بـ٣٦٪ سنوياً بدفع ٢٠٠ درهم فقط يستغرق سنوات للتصفية.",
      explanationWrongEn: "Minimum payments are designed to keep you in debt longer. Interest accrues on the unpaid balance — pay in full every month to avoid interest entirely.",
      explanationWrongAr: "الحد الأدنى للمدفوعات مصمم لإبقائك مديناً لفترة أطول. تتراكم الفائدة على الرصيد غير المدفوع — ادفع بالكامل كل شهر لتجنب الفائدة كلياً.",
    },
    {
      id: "cc-1-q2", nodeId: "cc-1",
      textEn: "A credit card 'grace period' is:",
      textAr: "'فترة السماح' لبطاقة الائتمان هي:",
      choices: [
        { id: "a", textEn: "The time after the due date before a late fee applies",           textAr: "الوقت بعد تاريخ الاستحقاق قبل تطبيق رسوم التأخير"     },
        { id: "b", textEn: "Interest-free window between purchase and due date if paid in full", textAr: "نافذة بلا فائدة بين الشراء وتاريخ الاستحقاق إذا دفعت بالكامل" },
        { id: "c", textEn: "A promotional 0% interest period on balance transfers",           textAr: "فترة ترويجية بفائدة ٠٪ على تحويلات الرصيد"               },
        { id: "d", textEn: "A waiting period before you can use your new card",              textAr: "فترة انتظار قبل أن تتمكن من استخدام بطاقتك الجديدة"    },
      ],
      correctId: "b",
      explanationCorrectEn: "The grace period (typically 20–55 days) lets you use the card interest-free if you pay the FULL balance by the due date. Carry a balance and you lose the grace period.",
      explanationCorrectAr: "فترة السماح (عادةً ٢٠–٥٥ يوماً) تتيح لك استخدام البطاقة بلا فائدة إذا دفعت الرصيد الكامل بحلول تاريخ الاستحقاق. احتفظ برصيد وستفقد فترة السماح.",
      explanationWrongEn: "Grace period = interest-free window if you pay in full. It's not about late fees. Once you carry a balance, interest starts accumulating from the purchase date.",
      explanationWrongAr: "فترة السماح = نافذة بلا فائدة إذا دفعت بالكامل. ليست عن رسوم التأخير. بمجرد احتفاظك برصيد، تبدأ الفائدة في التراكم من تاريخ الشراء.",
    },
    {
      id: "cc-1-q3", nodeId: "cc-1",
      textEn: "Credit card APR in the UAE can reach as high as:",
      textAr: "يمكن أن يصل معدل النسبة السنوية لبطاقات الائتمان في الإمارات إلى:",
      choices: [
        { id: "a", textEn: "5–8%",   textAr: "٥–٨٪"   },
        { id: "b", textEn: "10–15%", textAr: "١٠–١٥٪" },
        { id: "c", textEn: "25–36%", textAr: "٢٥–٣٦٪" },
        { id: "d", textEn: "50%+",   textAr: "٥٠٪ وأكثر" },
      ],
      correctId: "c",
      explanationCorrectEn: "UAE credit cards commonly charge 25–36% APR on revolving balances. At 36%, a AED 10,000 balance costs AED 3,600/year in interest if you never pay it down.",
      explanationCorrectAr: "تفرض بطاقات الائتمان الإماراتية عادةً ٢٥–٣٦٪ سنوياً على الأرصدة المتجددة. عند ٣٦٪، رصيد ١٠٬٠٠٠ درهم يكلّف ٣٬٦٠٠ درهم سنوياً في الفائدة إذا لم تسدده أبداً.",
      explanationWrongEn: "UAE credit card rates are high — typically 25–36% APR. This is why paying in full every month is critical. Carrying even a small balance becomes expensive quickly.",
      explanationWrongAr: "معدلات بطاقات الائتمان في الإمارات مرتفعة — عادةً ٢٥–٣٦٪ سنوياً. لهذا السبب الدفع الكامل كل شهر أمر بالغ الأهمية. حتى رصيد صغير يصبح مكلفاً بسرعة.",
    },
  ],

  // ── Card Canyon — cc-2: "The Interest Trap" ──────────────────────────────────
  "cc-2": [
    {
      id: "cc-2-q1", nodeId: "cc-2",
      textEn: "Ahmad has a AED 10,000 credit card balance at 36% APR. If he pays AED 300/month (minimum), how long approximately to pay it off?",
      textAr: "لدى أحمد رصيد بطاقة ائتمان ١٠٬٠٠٠ درهم بمعدل ٣٦٪ سنوياً. إذا دفع ٣٠٠ درهم شهرياً (الحد الأدنى)، كم يستغرق السداد تقريباً؟",
      choices: [
        { id: "a", textEn: "About 2 years",  textAr: "حوالي سنتين"    },
        { id: "b", textEn: "About 4 years",  textAr: "حوالي ٤ سنوات" },
        { id: "c", textEn: "Over 6 years",   textAr: "أكثر من ٦ سنوات" },
        { id: "d", textEn: "About 10 years", textAr: "حوالي ١٠ سنوات" },
      ],
      correctId: "c",
      explanationCorrectEn: "At 36% APR, monthly interest on AED 10,000 is ~AED 300. Paying AED 300/month barely covers the interest — the balance barely moves for years. This is the minimum payment trap.",
      explanationCorrectAr: "عند ٣٦٪ سنوياً، الفائدة الشهرية على ١٠٬٠٠٠ درهم حوالي ٣٠٠ درهم. دفع ٣٠٠ درهم شهرياً بالكاد يغطي الفائدة — الرصيد بالكاد يتحرك لسنوات. هذا هو فخ الحد الأدنى.",
      explanationWrongEn: "At 36% APR, AED 10,000 accrues ~AED 300/month in interest. A AED 300 minimum payment barely moves the needle — it can take 6+ years to clear. Pay more aggressively.",
      explanationWrongAr: "عند ٣٦٪ سنوياً، ١٠٬٠٠٠ درهم يتراكم ~٣٠٠ درهم شهرياً في فائدة. دفع ٣٠٠ درهم كحد أدنى بالكاد يحرّك الإبرة — قد يستغرق ٦+ سنوات للتصفية. ادفع بشكل أكثر عدوانية.",
    },
    {
      id: "cc-2-q2", nodeId: "cc-2",
      textEn: "Your 'credit utilization ratio' is:",
      textAr: "'نسبة استخدام الائتمان' هي:",
      choices: [
        { id: "a", textEn: "Number of credit cards you own divided by income",  textAr: "عدد بطاقاتك الائتمانية مقسوماً على دخلك"     },
        { id: "b", textEn: "Your current balance divided by your credit limit",  textAr: "رصيدك الحالي مقسوماً على حد ائتمانك"          },
        { id: "c", textEn: "How many times per month you use your card",        textAr: "عدد مرات استخدامك للبطاقة في الشهر"           },
        { id: "d", textEn: "Your credit score as a percentage of maximum",      textAr: "درجة ائتمانك كنسبة مئوية من الحد الأقصى"      },
      ],
      correctId: "b",
      explanationCorrectEn: "Utilization = balance ÷ credit limit. A AED 3,000 balance on a AED 10,000 limit = 30% utilization. Keeping this below 30% is important for a healthy credit score.",
      explanationCorrectAr: "الاستخدام = الرصيد ÷ حد الائتمان. رصيد ٣٬٠٠٠ درهم على حد ١٠٬٠٠٠ = ٣٠٪ استخدام. الحفاظ على هذا تحت ٣٠٪ مهم لدرجة ائتمان صحية.",
      explanationWrongEn: "Utilization = how much of your available credit you're using. Formula: balance ÷ limit. Below 30% is considered healthy by lenders.",
      explanationWrongAr: "الاستخدام = مقدار الائتمان المتاح الذي تستخدمه. الصيغة: الرصيد ÷ الحد. أقل من ٣٠٪ يُعتبر صحياً من قِبل المقرضين.",
    },
    {
      id: "cc-2-q3", nodeId: "cc-2",
      textEn: "Reem has a AED 20,000 credit limit and a balance of AED 6,500. What is her credit utilization?",
      textAr: "لدى ريم حد ائتمان ٢٠٬٠٠٠ درهم ورصيد ٦٬٥٠٠ درهم. ما نسبة استخدامها للائتمان؟",
      choices: [
        { id: "a", textEn: "26.5%", textAr: "٢٦.٥٪" },
        { id: "b", textEn: "30.0%", textAr: "٣٠.٠٪" },
        { id: "c", textEn: "32.5%", textAr: "٣٢.٥٪" },
        { id: "d", textEn: "35.0%", textAr: "٣٥.٠٪" },
      ],
      correctId: "c",
      explanationCorrectEn: "6,500 ÷ 20,000 = 32.5%. She's slightly above the ideal 30% threshold. Paying down AED 500 more would bring her under 30% — potentially improving her credit score.",
      explanationCorrectAr: "٦٬٥٠٠ ÷ ٢٠٬٠٠٠ = ٣٢.٥٪. هي أعلى قليلاً من الحد المثالي ٣٠٪. سداد ٥٠٠ درهم إضافي سيجعلها تحت ٣٠٪ — مما يحتمل تحسين درجتها الائتمانية.",
      explanationWrongEn: "6,500 ÷ 20,000 = 0.325 = 32.5%. Just above the 30% ideal. Aim to keep utilization below 30% for the best credit score impact.",
      explanationWrongAr: "٦٬٥٠٠ ÷ ٢٠٬٠٠٠ = ٠.٣٢٥ = ٣٢.٥٪. أعلى قليلاً من المثالي ٣٠٪. احرص على إبقاء الاستخدام تحت ٣٠٪ لأفضل تأثير على درجة الائتمان.",
    },
  ],

  // ── Card Canyon — cc-5: "Credit Boss" (boss) ─────────────────────────────────
  "cc-5": [
    {
      id: "cc-5-q1", nodeId: "cc-5",
      textEn: "The safest credit card habit is:",
      textAr: "أأمن عادة لبطاقة الائتمان هي:",
      choices: [
        { id: "a", textEn: "Spending to your full credit limit to maximise rewards",   textAr: "الإنفاق حتى حد ائتمانك الكامل لزيادة المكافآت"       },
        { id: "b", textEn: "Paying your full statement balance before the due date",    textAr: "دفع رصيد كشفك الكامل قبل تاريخ الاستحقاق"           },
        { id: "c", textEn: "Carrying a small balance to show lenders you use credit",  textAr: "الاحتفاظ برصيد صغير لإظهار استخدامك للائتمان للمقرضين" },
        { id: "d", textEn: "Using multiple cards to spread your balance",              textAr: "استخدام بطاقات متعددة لتوزيع رصيدك"                   },
      ],
      correctId: "b",
      explanationCorrectEn: "Pay in full every month = zero interest, use the grace period freely, earn rewards with no cost. You don't need to carry a balance to build credit — on-time payments do that.",
      explanationCorrectAr: "ادفع بالكامل كل شهر = صفر فائدة، استخدم فترة السماح بحرية، اكسب مكافآت بلا تكلفة. لا تحتاج إلى حمل رصيد لبناء الائتمان — المدفوعات في الوقت المحدد تفعل ذلك.",
      explanationWrongEn: "Full payment every month is the gold standard. You never pay interest, you earn rewards for free, and your credit score benefits from on-time payments and low utilization.",
      explanationWrongAr: "الدفع الكامل كل شهر هو المعيار الذهبي. لا تدفع فائدة أبداً وتكسب المكافآت مجاناً ودرجتك الائتمانية تستفيد من المدفوعات في الوقت المحدد والاستخدام المنخفض.",
    },
    {
      id: "cc-5-q2", nodeId: "cc-5",
      textEn: "'Buy Now, Pay Later' (BNPL) services can be risky because:",
      textAr: "خدمات 'اشترِ الآن وادفع لاحقاً' (BNPL) قد تكون محفوفة بالمخاطر لأن:",
      choices: [
        { id: "a", textEn: "They always charge the same rate as bank loans",         textAr: "تفرض دائماً نفس معدل القروض البنكية"              },
        { id: "b", textEn: "Late fees and interest apply if you miss instalments",   textAr: "تنطبق رسوم التأخير والفائدة إذا فاتتك أقساط"    },
        { id: "c", textEn: "They are banned in the UAE",                             textAr: "محظورة في الإمارات"                                },
        { id: "d", textEn: "They require a credit card to activate",                textAr: "تتطلب بطاقة ائتمان للتفعيل"                       },
      ],
      correctId: "b",
      explanationCorrectEn: "BNPL can trap you: miss a payment and fees apply; split a large purchase into 4 and you may forget. BNPL inflates what you can spend today — which is the exact problem it should solve.",
      explanationCorrectAr: "BNPL يمكن أن يستدرجك: فوّت دفعة وتنطبق الرسوم؛ قسّم شراء كبير إلى ٤ وقد تنسى. BNPL يُضخّم ما يمكنك إنفاقه اليوم — وهذه هي المشكلة بالضبط التي يُفترض أن يحلها.",
      explanationWrongEn: "BNPL isn't banned and isn't always as cheap as advertised. Read the full terms: late fees can be steep, and some charge interest retroactively if you miss a payment.",
      explanationWrongAr: "BNPL ليس محظوراً وليس دائماً رخيصاً كما يُعلَن. اقرأ الشروط الكاملة: رسوم التأخير قد تكون باهظة، وبعضها يفرض فائدة بأثر رجعي إذا فاتتك دفعة.",
    },
    {
      id: "cc-5-q3", nodeId: "cc-5",
      textEn: "To avoid interest on a credit card entirely, you must:",
      textAr: "لتجنب الفائدة على بطاقة الائتمان كلياً، يجب عليك:",
      choices: [
        { id: "a", textEn: "Never use the card",                                          textAr: "لا تستخدم البطاقة أبداً"                               },
        { id: "b", textEn: "Pay only the minimum each month",                             textAr: "ادفع الحد الأدنى فقط كل شهر"                          },
        { id: "c", textEn: "Pay the full statement balance by the due date every month",   textAr: "ادفع الرصيد الكامل للكشف بحلول تاريخ الاستحقاق كل شهر" },
        { id: "d", textEn: "Use the card only for purchases under AED 200",               textAr: "استخدم البطاقة للمشتريات أقل من ٢٠٠ درهم فقط"         },
      ],
      correctId: "c",
      explanationCorrectEn: "Full balance payment by due date = zero interest, always. The grace period only works when you clear the entire statement balance — not just the minimum.",
      explanationCorrectAr: "دفع الرصيد الكامل بحلول تاريخ الاستحقاق = صفر فائدة، دائماً. فترة السماح تعمل فقط عندما تصفي رصيد الكشف بالكامل — وليس الحد الأدنى فقط.",
      explanationWrongEn: "Interest-free credit card use = pay FULL statement balance by due date every single month. Not the minimum. Not most of it. The full amount.",
      explanationWrongAr: "استخدام بطاقة ائتمان بلا فائدة = دفع الرصيد الكامل للكشف بحلول تاريخ الاستحقاق كل شهر. ليس الحد الأدنى. ليس معظمه. المبلغ الكامل.",
    },
  ],

  // ── Oasis of Insurance — oi-1: "Why Insurance?" ──────────────────────────────
  "oi-1": [
    {
      id: "oi-1-q1", nodeId: "oi-1",
      textEn: "The primary purpose of insurance is to:",
      textAr: "الغرض الأساسي من التأمين هو:",
      choices: [
        { id: "a", textEn: "Build long-term wealth through premiums",                   textAr: "بناء ثروة طويلة الأجل من خلال الأقساط"               },
        { id: "b", textEn: "Transfer financial risk to an insurer in exchange for premiums", textAr: "نقل المخاطر المالية إلى شركة تأمين مقابل أقساط"    },
        { id: "c", textEn: "Avoid paying for any expenses at all",                     textAr: "تجنب دفع أي مصروفات على الإطلاق"                      },
        { id: "d", textEn: "Guarantee investment returns above inflation",             textAr: "ضمان عوائد استثمارية فوق التضخم"                      },
      ],
      correctId: "b",
      explanationCorrectEn: "Insurance transfers a large unpredictable risk (a AED 200,000 medical bill) to an insurer in exchange for a small, predictable premium. You're paying for certainty, not profit.",
      explanationCorrectAr: "التأمين ينقل مخاطرة كبيرة غير متوقعة (فاتورة طبية ٢٠٠٬٠٠٠ درهم) إلى شركة التأمين مقابل قسط صغير ومتوقع. أنت تدفع مقابل اليقين، وليس الربح.",
      explanationWrongEn: "Insurance isn't an investment — it's risk transfer. You pay a small, predictable premium to avoid a large, unpredictable financial hit.",
      explanationWrongAr: "التأمين ليس استثماراً — إنه نقل مخاطر. تدفع قسطاً صغيراً ومتوقعاً لتجنب ضربة مالية كبيرة وغير متوقعة.",
    },
    {
      id: "oi-1-q2", nodeId: "oi-1",
      textEn: "A 'premium' in insurance refers to:",
      textAr: "'القسط' في التأمين يشير إلى:",
      choices: [
        { id: "a", textEn: "The amount the insurer pays when you claim",          textAr: "المبلغ الذي تدفعه شركة التأمين عند المطالبة" },
        { id: "b", textEn: "The regular payment you make to maintain coverage",   textAr: "الدفعة المنتظمة التي تدفعها للحفاظ على التغطية" },
        { id: "c", textEn: "The maximum coverage your policy provides",           textAr: "الحد الأقصى للتغطية التي تقدمها وثيقتك"       },
        { id: "d", textEn: "A loyalty bonus after 5 years with the same insurer", textAr: "مكافأة ولاء بعد ٥ سنوات مع نفس المؤمِّن"       },
      ],
      correctId: "b",
      explanationCorrectEn: "Premium = the cost you pay for coverage. Monthly or annually. Stop paying and coverage lapses. Think of it as the price of your protection.",
      explanationCorrectAr: "القسط = التكلفة التي تدفعها مقابل التغطية. شهرياً أو سنوياً. توقف عن الدفع وتنتهي التغطية. فكّر فيه كسعر حمايتك.",
      explanationWrongEn: "Premium = your regular payment to keep the policy active. The claim payout is different — that's what you receive when something goes wrong.",
      explanationWrongAr: "القسط = دفعتك المنتظمة للحفاظ على نشاط الوثيقة. مدفوعات المطالبة مختلفة — هذا ما تستلمه عندما يحدث خطأ ما.",
    },
    {
      id: "oi-1-q3", nodeId: "oi-1",
      textEn: "In the UAE, which insurance is mandatory by law for vehicle owners?",
      textAr: "في الإمارات، أي تأمين إلزامي قانوناً لأصحاب المركبات؟",
      choices: [
        { id: "a", textEn: "Comprehensive vehicle insurance only",      textAr: "تأمين شامل للمركبة فقط"           },
        { id: "b", textEn: "Third-party liability insurance at minimum", textAr: "تأمين المسؤولية تجاه الغير كحد أدنى" },
        { id: "c", textEn: "Personal accident insurance only",          textAr: "تأمين الحوادث الشخصية فقط"         },
        { id: "d", textEn: "No vehicle insurance is required by law",   textAr: "لا يُشترط أي تأمين للمركبة قانوناً" },
      ],
      correctId: "b",
      explanationCorrectEn: "Third-party liability is the legal minimum in the UAE. It covers damage you cause to other people and their property. Comprehensive adds coverage for your own vehicle too.",
      explanationCorrectAr: "تأمين المسؤولية تجاه الغير هو الحد الأدنى القانوني في الإمارات. يغطي الأضرار التي تسببها للآخرين وممتلكاتهم. التأمين الشامل يضيف تغطية لمركبتك أيضاً.",
      explanationWrongEn: "UAE law requires at least third-party liability cover. Without it, you cannot register or renew your vehicle. Comprehensive is optional but recommended for newer cars.",
      explanationWrongAr: "يشترط قانون الإمارات على الأقل تغطية المسؤولية تجاه الغير. بدونها لا يمكنك تسجيل مركبتك أو تجديدها. التأمين الشامل اختياري لكن موصى به للسيارات الحديثة.",
    },
  ],

  // ── Oasis of Insurance — oi-2: "Types of Coverage" ───────────────────────────
  "oi-2": [
    {
      id: "oi-2-q1", nodeId: "oi-2",
      textEn: "A 'deductible' in an insurance policy is:",
      textAr: "'الاشتراك الشخصي' (التحمّل) في وثيقة التأمين هو:",
      choices: [
        { id: "a", textEn: "A discount on your premium for good behaviour",           textAr: "خصم على قسطك مقابل سلوك جيد"                   },
        { id: "b", textEn: "The portion of a claim you pay before insurance covers the rest", textAr: "الجزء من المطالبة الذي تدفعه قبل أن يغطي التأمين الباقي" },
        { id: "c", textEn: "The maximum amount the insurer will ever pay you",        textAr: "الحد الأقصى لما ستدفعه لك شركة التأمين"         },
        { id: "d", textEn: "A tax deduction you get for buying insurance",            textAr: "خصم ضريبي تحصل عليه لشراء التأمين"              },
      ],
      correctId: "b",
      explanationCorrectEn: "A AED 500 deductible means you pay the first AED 500 of any claim. Higher deductibles lower your premium but increase your out-of-pocket cost when you claim.",
      explanationCorrectAr: "تحمّل ٥٠٠ درهم يعني أنك تدفع أول ٥٠٠ درهم من أي مطالبة. التحمّل الأعلى يخفّض قسطك لكن يزيد تكلفتك من جيبك عند المطالبة.",
      explanationWrongEn: "Deductible = your share of each claim before insurance pays. Higher deductible = lower premium. Choose based on how much you can afford to pay out-of-pocket.",
      explanationWrongAr: "التحمّل = حصتك من كل مطالبة قبل أن يدفع التأمين. تحمّل أعلى = قسط أقل. اختر بناءً على مقدار ما يمكنك تحمّله من جيبك.",
    },
    {
      id: "oi-2-q2", nodeId: "oi-2",
      textEn: "Health insurance in the UAE for expatriate employees:",
      textAr: "التأمين الصحي في الإمارات للموظفين الأجانب:",
      choices: [
        { id: "a", textEn: "Is entirely optional — your choice whether to get it",       textAr: "اختياري تماماً — قرارك هل تحصل عليه"              },
        { id: "b", textEn: "Is mandatory in Abu Dhabi and Dubai; recommended elsewhere", textAr: "إلزامي في أبوظبي ودبي؛ موصى به في بقية الإمارات" },
        { id: "c", textEn: "Is provided free by the UAE government to all residents",    textAr: "تقدمه حكومة الإمارات مجاناً لجميع المقيمين"      },
        { id: "d", textEn: "Only applies to government sector employees",               textAr: "ينطبق فقط على موظفي القطاع الحكومي"               },
      ],
      correctId: "b",
      explanationCorrectEn: "Dubai and Abu Dhabi require employers to provide health insurance for employees and their dependents. Other emirates have similar frameworks. Without it, medical costs can be catastrophic.",
      explanationCorrectAr: "تُلزم دبي وأبوظبي أصحاب العمل بتوفير تأمين صحي للموظفين ومعاليهم. بقية الإمارات لديها أطر مماثلة. بدونه، يمكن أن تكون التكاليف الطبية كارثية.",
      explanationWrongEn: "Dubai and Abu Dhabi mandate employer-provided health insurance. If your employer doesn't provide it, you may need to arrange your own — especially important given UAE healthcare costs.",
      explanationWrongAr: "تُلزم دبي وأبوظبي أصحاب العمل بتوفير التأمين الصحي. إذا لم يوفره صاحب عملك، قد تحتاج إلى ترتيبه بنفسك — مهم بشكل خاص نظراً لتكاليف الرعاية الصحية في الإمارات.",
    },
    {
      id: "oi-2-q3", nodeId: "oi-2",
      textEn: "Sara's car has a market value of AED 22,000. Comprehensive cover costs AED 3,300/year; third-party costs AED 750/year. For a low-value car, which makes more sense?",
      textAr: "قيمة سيارة سارة السوقية ٢٢٬٠٠٠ درهم. التأمين الشامل بـ٣٬٣٠٠ درهم/سنة؛ تأمين الغير بـ٧٥٠ درهم/سنة. لسيارة منخفضة القيمة، أيهما أمثل؟",
      choices: [
        { id: "a", textEn: "Comprehensive — it covers everything",                       textAr: "الشامل — يغطي كل شيء"                                 },
        { id: "b", textEn: "Third-party — premium is proportionally too high for the car's value", textAr: "تأمين الغير — القسط مرتفع نسبياً مقارنة بقيمة السيارة" },
        { id: "c", textEn: "Both are equal in value",                                    textAr: "كلاهما متكافئان في القيمة"                              },
        { id: "d", textEn: "Drive without any insurance to save money",                  textAr: "اقود بدون تأمين لتوفير المال"                          },
      ],
      correctId: "b",
      explanationCorrectEn: "Comprehensive costs AED 3,300 = 15% of the car's value per year. Over 3 years, you'd pay more than half the car's value in premiums. Third-party is often better for older/cheaper cars.",
      explanationCorrectAr: "التأمين الشامل يكلف ٣٬٣٠٠ درهم = ١٥٪ من قيمة السيارة سنوياً. على مدى ٣ سنوات ستدفع أكثر من نصف قيمة السيارة في أقساط. تأمين الغير غالباً أفضل للسيارات القديمة/الأرخص.",
      explanationWrongEn: "3,300 ÷ 22,000 = 15% of car value per year. Comprehensive rarely makes sense when the premium exceeds ~8–10% of the car's value annually.",
      explanationWrongAr: "٣٬٣٠٠ ÷ ٢٢٬٠٠٠ = ١٥٪ من قيمة السيارة سنوياً. التأمين الشامل نادراً ما يكون منطقياً عندما يتجاوز القسط ~٨–١٠٪ من قيمة السيارة سنوياً.",
    },
  ],

  // ── Oasis of Insurance — oi-5: "Insurance Boss" (boss) ───────────────────────
  "oi-5": [
    {
      id: "oi-5-q1", nodeId: "oi-5",
      textEn: "An 'exclusion' in an insurance policy is:",
      textAr: "'الاستثناء' في وثيقة التأمين هو:",
      choices: [
        { id: "a", textEn: "A type of bonus coverage you earn over time",              textAr: "نوع من التغطية الإضافية تكسبها بمرور الوقت"         },
        { id: "b", textEn: "A specific situation or item NOT covered by the policy",   textAr: "موقف أو عنصر محدد غير مشمول بالوثيقة"               },
        { id: "c", textEn: "A premium discount for bundling multiple policies",        textAr: "خصم على القسط عند تجميع وثائق متعددة"                },
        { id: "d", textEn: "Coverage that only activates after a waiting period",      textAr: "تغطية لا تنشط إلا بعد فترة انتظار"                  },
      ],
      correctId: "b",
      explanationCorrectEn: "Exclusions define what your policy won't cover. Always read them before signing. Common exclusions: pre-existing conditions (health), racing (auto), flood (home in some areas).",
      explanationCorrectAr: "الاستثناءات تحدد ما لن تغطيه وثيقتك. اقرأها دائماً قبل التوقيع. الاستثناءات الشائعة: الحالات السابقة (الصحة)، السباق (السيارات)، الفيضانات (المنزل في بعض المناطق).",
      explanationWrongEn: "Exclusions are the 'not covered' clauses. They're as important as the coverage — knowing what's excluded prevents nasty surprises when you file a claim.",
      explanationWrongAr: "الاستثناءات هي بنود 'غير المشمول'. إنها بنفس أهمية التغطية — معرفة ما هو مستثنى تمنع المفاجآت السيئة عند تقديم مطالبة.",
    },
    {
      id: "oi-5-q2", nodeId: "oi-5",
      textEn: "Yousef pays AED 2,400/year for health insurance. He never claims. After 3 years, he thinks about cancelling. The best financial thinking here is:",
      textAr: "يدفع يوسف ٢٬٤٠٠ درهم/سنة للتأمين الصحي. لم يُطالب قط. بعد ٣ سنوات يفكر في الإلغاء. أفضل تفكير مالي هنا:",
      choices: [
        { id: "a", textEn: "Cancel — he's paid AED 7,200 with no return",                   textAr: "ألغِه — دفع ٧٬٢٠٠ درهم بلا عائد"                               },
        { id: "b", textEn: "Keep it — he paid AED 7,200 to avoid a potentially AED 200,000+ claim", textAr: "احتفظ به — دفع ٧٬٢٠٠ درهم لتجنب مطالبة قد تبلغ ٢٠٠٬٠٠٠ درهم أو أكثر" },
        { id: "c", textEn: "Downgrade to no coverage to save money",                        textAr: "تراجع إلى عدم التغطية لتوفير المال"                              },
        { id: "d", textEn: "The 3 years of 'no claims' means his health risk is zero",     textAr: "سنوات عدم المطالبة الثلاث تعني أن مخاطره الصحية صفر"             },
      ],
      correctId: "b",
      explanationCorrectEn: "Not claiming means everything went well — it's not a wasted cost. You paid for protection, not a service you use. A single hospitalisation can cost AED 100,000+.",
      explanationCorrectAr: "عدم المطالبة يعني أن كل شيء سار بخير — إنها ليست تكلفة ضائعة. دفعت مقابل الحماية، وليس خدمة تستخدمها. دخول مستشفى واحد يمكن أن يكلف ١٠٠٬٠٠٠ درهم أو أكثر.",
      explanationWrongEn: "Insurance you 'never use' is doing its job. The premium buys peace of mind and protection against a catastrophic cost. One serious illness can wipe out years of premiums saved.",
      explanationWrongAr: "التأمين الذي 'لا تستخدمه أبداً' يقوم بعمله. القسط يشتري راحة البال والحماية من تكلفة كارثية. مرض واحد خطير يمكن أن يمحو سنوات من الأقساط الموفَّرة.",
    },
    {
      id: "oi-5-q3", nodeId: "oi-5",
      textEn: "The term 'sum insured' means:",
      textAr: "مصطلح 'مبلغ التأمين' يعني:",
      choices: [
        { id: "a", textEn: "The total premiums you have paid so far",                 textAr: "إجمالي الأقساط التي دفعتها حتى الآن"                    },
        { id: "b", textEn: "The maximum amount the insurer will pay out under your policy", textAr: "الحد الأقصى للمبلغ الذي ستدفعه شركة التأمين بموجب وثيقتك" },
        { id: "c", textEn: "Your deductible multiplied by the number of claims",     textAr: "تحمّلك مضروباً في عدد المطالبات"                        },
        { id: "d", textEn: "The sum of all policies you own combined",               textAr: "مجموع جميع وثائقك مجتمعة"                              },
      ],
      correctId: "b",
      explanationCorrectEn: "Sum insured = the cap on what your insurer will pay. Make sure it's high enough — underinsured means you absorb the gap between the sum insured and actual loss yourself.",
      explanationCorrectAr: "مبلغ التأمين = الحد الأقصى لما ستدفعه شركتك. تأكد من أنه مرتفع بما يكفي — التأمين الناقص يعني أنك تتحمل الفجوة بين مبلغ التأمين والخسارة الفعلية بنفسك.",
      explanationWrongEn: "Sum insured is your policy's maximum payout. If your car is worth AED 100,000 but insured for AED 60,000, you absorb the AED 40,000 difference in a total loss.",
      explanationWrongAr: "مبلغ التأمين هو الحد الأقصى للدفع في وثيقتك. إذا كانت سيارتك بقيمة ١٠٠٬٠٠٠ درهم لكنها مؤمّنة بـ٦٠٬٠٠٠ درهم، فإنك تتحمل فرق ٤٠٬٠٠٠ درهم في حالة الخسارة الكاملة.",
    },
  ],
};
