import type { QuizQuestion } from "./quiz-types";

export const QUESTIONS_W4_W5: Record<string, QuizQuestion[]> = {

  // ── Dirham Desert — dd-1: "Your Income" ──────────────────────────────────────
  "dd-1": [
    {
      id: "dd-1-q1", nodeId: "dd-1",
      textEn: "What is the difference between gross salary and net salary?",
      textAr: "ما الفرق بين الراتب الإجمالي والراتب الصافي؟",
      choices: [
        { id: "a", textEn: "Gross includes overtime; net does not",            textAr: "الإجمالي يشمل العمل الإضافي؛ الصافي لا يشمله"    },
        { id: "b", textEn: "Gross is before deductions; net is what you receive", textAr: "الإجمالي قبل الاستقطاعات؛ الصافي ما تستلمه فعلاً" },
        { id: "c", textEn: "Net salary is always higher than gross",            textAr: "الراتب الصافي دائماً أعلى من الإجمالي"             },
        { id: "d", textEn: "They are the same in the UAE since there is no tax", textAr: "هما نفس الشيء في الإمارات لأنه لا توجد ضريبة"    },
      ],
      correctId: "b",
      explanationCorrectEn: "Gross is your total package before any deductions (DEWS, insurance, loans). Net is what lands in your bank account. Always budget from net — not gross.",
      explanationCorrectAr: "الإجمالي هو حزمتك الكاملة قبل أي استقطاعات (DEWS والتأمين والقروض). الصافي هو ما يصل إلى حسابك البنكي. ابنِ ميزانيتك دائماً على الصافي — لا الإجمالي.",
      explanationWrongEn: "Gross comes first; deductions (pension, insurance, loans) reduce it to net. In UAE, no income tax — but other deductions still apply for many employees.",
      explanationWrongAr: "الإجمالي أولاً؛ الاستقطاعات (المعاش والتأمين والقروض) تخفضه إلى الصافي. في الإمارات لا ضريبة دخل — لكن استقطاعات أخرى تنطبق على كثير من الموظفين.",
    },
    {
      id: "dd-1-q2", nodeId: "dd-1",
      textEn: "In the UAE, which deduction does NOT apply to most private-sector expatriate employees?",
      textAr: "في الإمارات، أي استقطاع لا ينطبق على معظم الموظفين الأجانب في القطاع الخاص؟",
      choices: [
        { id: "a", textEn: "DEWS workplace savings contributions (for some schemes)", textAr: "مساهمات نظام ادخار DEWS (لبعض الأنظمة)"   },
        { id: "b", textEn: "Employer-deducted medical insurance",                    textAr: "التأمين الطبي المستقطع من صاحب العمل"        },
        { id: "c", textEn: "Personal income tax",                                    textAr: "ضريبة الدخل الشخصي"                          },
        { id: "d", textEn: "Voluntary savings plan deductions",                      textAr: "استقطاعات خطة الادخار الطوعية"               },
      ],
      correctId: "c",
      explanationCorrectEn: "The UAE has no personal income tax for employees — one of the biggest financial benefits of working here. Your gross and net are much closer than in most countries.",
      explanationCorrectAr: "لا توجد ضريبة دخل شخصي للموظفين في الإمارات — من أكبر الفوائد المالية للعمل هنا. إجماليك وصافيك أقرب بكثير مما هو عليه في معظم البلدان.",
      explanationWrongEn: "There is no personal income tax in the UAE — that's a key financial advantage here. DEWS, insurance, and voluntary savings plans may still appear on payslips.",
      explanationWrongAr: "لا توجد ضريبة دخل شخصي في الإمارات — وهذه ميزة مالية رئيسية هنا. DEWS والتأمين وخطط الادخار الطوعية قد لا تزال تظهر في كشوف الرواتب.",
    },
    {
      id: "dd-1-q3", nodeId: "dd-1",
      textEn: "Khalid's gross salary is AED 15,000. Deductions: AED 750 (DEWS) + AED 500 (medical). His net salary is:",
      textAr: "راتب خالد الإجمالي ١٥٬٠٠٠ درهم. الاستقطاعات: ٧٥٠ (DEWS) + ٥٠٠ (طبي). راتبه الصافي:",
      choices: [
        { id: "a", textEn: "AED 15,000", textAr: "١٥٬٠٠٠ درهم" },
        { id: "b", textEn: "AED 14,250", textAr: "١٤٬٢٥٠ درهم" },
        { id: "c", textEn: "AED 13,750", textAr: "١٣٬٧٥٠ درهم" },
        { id: "d", textEn: "AED 14,500", textAr: "١٤٬٥٠٠ درهم" },
      ],
      correctId: "c",
      explanationCorrectEn: "AED 15,000 − AED 750 − AED 500 = AED 13,750. Always check your payslip to understand what you actually take home — and budget from that number.",
      explanationCorrectAr: "١٥٬٠٠٠ − ٧٥٠ − ٥٠٠ = ١٣٬٧٥٠ درهم. تحقق دائماً من كشف راتبك لتفهم ما تستلمه فعلاً — وابنِ ميزانيتك على هذا الرقم.",
      explanationWrongEn: "15,000 − 750 − 500 = 13,750. Khalid's take-home is AED 13,750 — that's the number his budget should be built on.",
      explanationWrongAr: "١٥٬٠٠٠ − ٧٥٠ − ٥٠٠ = ١٣٬٧٥٠. دخل خالد المنزلي ١٣٬٧٥٠ درهم — هذا هو الرقم الذي يجب أن تُبنى عليه ميزانيته.",
    },
  ],

  // ── Dirham Desert — dd-2: "Tracking Expenses" ────────────────────────────────
  "dd-2": [
    {
      id: "dd-2-q1", nodeId: "dd-2",
      textEn: "Which expense tracking habit has the most impact on changing spending behaviour?",
      textAr: "أي عادة في تتبع المصروفات لها أكبر تأثير على تغيير سلوك الإنفاق؟",
      choices: [
        { id: "a", textEn: "Making mental notes as you spend",                         textAr: "عمل ملاحظات ذهنية أثناء الإنفاق"                  },
        { id: "b", textEn: "Reviewing bank statements once a year",                    textAr: "مراجعة كشوف البنك مرة في السنة"                    },
        { id: "c", textEn: "Categorising and reviewing all spending monthly",          textAr: "تصنيف ومراجعة جميع المصروفات شهرياً"               },
        { id: "d", textEn: "Tracking only cash transactions",                          textAr: "تتبع المعاملات النقدية فقط"                        },
      ],
      correctId: "c",
      explanationCorrectEn: "Monthly categorised reviews reveal patterns you can act on: where money leaks, what's growing, what to cut. Monthly is frequent enough to course-correct without being obsessive.",
      explanationCorrectAr: "المراجعات الشهرية المصنّفة تكشف الأنماط التي يمكنك التصرف عليها: أين يتسرب المال وما الذي ينمو وما الذي يجب تخفيضه. الشهري متكرر بما يكفي للتصحيح دون أن يكون مهووساً.",
      explanationWrongEn: "Mental notes are unreliable. Annual reviews are too late to catch patterns. Categorised monthly tracking gives you the data to make real changes.",
      explanationWrongAr: "الملاحظات الذهنية غير موثوقة. المراجعات السنوية متأخرة جداً لرصد الأنماط. التتبع الشهري المصنّف يمنحك البيانات لإجراء تغييرات حقيقية.",
    },
    {
      id: "dd-2-q2", nodeId: "dd-2",
      textEn: "Fixed expenses are best described as:",
      textAr: "المصروفات الثابتة يُوصف بها بشكل أفضل:",
      choices: [
        { id: "a", textEn: "Costs that can never change under any circumstances",        textAr: "تكاليف لا يمكن تغييرها أبداً تحت أي ظرف"          },
        { id: "b", textEn: "Regular, predictable costs like rent and subscriptions",     textAr: "تكاليف منتظمة ومتوقعة كالإيجار والاشتراكات"      },
        { id: "c", textEn: "One-time purchases above AED 500",                           textAr: "مشتريات لمرة واحدة فوق ٥٠٠ درهم"                 },
        { id: "d", textEn: "Expenses that require bank approval",                        textAr: "مصروفات تتطلب موافقة البنك"                        },
      ],
      correctId: "b",
      explanationCorrectEn: "Fixed expenses — rent, loan repayments, insurance, subscriptions — are the same each month. They're easier to plan but harder to reduce quickly.",
      explanationCorrectAr: "المصروفات الثابتة — الإيجار وأقساط القروض والتأمين والاشتراكات — هي نفسها كل شهر. أسهل في التخطيط لكن أصعب في التخفيض السريع.",
      explanationWrongEn: "Fixed = predictable and recurring (rent, insurance, loans). Variable = changes month to month (groceries, dining, fuel). Knowing both lets you find where to cut.",
      explanationWrongAr: "الثابت = متوقع ومتكرر (إيجار وتأمين وقروض). المتغير = يتغير من شهر لآخر (بقالة وطعام ووقود). معرفة كليهما يتيح لك العثور على أين تقطع.",
    },
    {
      id: "dd-2-q3", nodeId: "dd-2",
      textEn: "Sara cuts food delivery by 40% (from AED 800/month). How much does she save per year?",
      textAr: "تخفّض سارة توصيل الطعام بنسبة ٤٠٪ (من ٨٠٠ درهم شهرياً). كم توفّر سنوياً؟",
      choices: [
        { id: "a", textEn: "AED 320",   textAr: "٣٢٠ درهم"  },
        { id: "b", textEn: "AED 2,880", textAr: "٢٬٨٨٠ درهم" },
        { id: "c", textEn: "AED 3,840", textAr: "٣٬٨٤٠ درهم" },
        { id: "d", textEn: "AED 4,800", textAr: "٤٬٨٠٠ درهم" },
      ],
      correctId: "c",
      explanationCorrectEn: "Monthly saving = AED 800 × 40% = AED 320. Annual = AED 320 × 12 = AED 3,840. Redirected to savings, this builds a meaningful fund within a year.",
      explanationCorrectAr: "التوفير الشهري = ٨٠٠ × ٤٠٪ = ٣٢٠ درهم. السنوي = ٣٢٠ × ١٢ = ٣٬٨٤٠ درهم. إذا وُجِّه للمدخرات، يبني صندوقاً مهماً خلال سنة.",
      explanationWrongEn: "800 × 0.40 = 320/month saved. 320 × 12 = 3,840/year. Small habit changes in variable spending add up to thousands annually.",
      explanationWrongAr: "٨٠٠ × ٠.٤٠ = ٣٢٠/شهر توفير. ٣٢٠ × ١٢ = ٣٬٨٤٠/سنة. التغييرات الصغيرة في الإنفاق المتغير تصل إلى آلاف سنوياً.",
    },
  ],

  // ── Dirham Desert — dd-5: "Desert Boss" (boss) ────────────────────────────────
  "dd-5": [
    {
      id: "dd-5-q1", nodeId: "dd-5",
      textEn: "'Zero-based budgeting' means every dirham of income is assigned to a category so that income minus all allocations equals zero. This approach:",
      textAr: "'الميزنة الصفرية' تعني تخصيص كل درهم من الدخل لفئة بحيث الدخل ناقص جميع التخصيصات يساوي صفراً. هذا النهج:",
      choices: [
        { id: "a", textEn: "Means you spend everything and save nothing",             textAr: "يعني أنك تنفق كل شيء ولا تدّخر شيئاً"              },
        { id: "b", textEn: "Gives every dirham a purpose, including savings",        textAr: "يمنح كل درهم غرضاً، بما فيه المدخرات"               },
        { id: "c", textEn: "Only works if you earn more than AED 20,000/month",      textAr: "يعمل فقط إذا كنت تكسب أكثر من ٢٠٬٠٠٠ درهم شهرياً" },
        { id: "d", textEn: "Requires a professional accountant to set up",           textAr: "يتطلب محاسباً محترفاً للإعداد"                      },
      ],
      correctId: "b",
      explanationCorrectEn: "Zero-based budgeting means giving every dirham a job — including savings, investments, and fun money. 'Zero' means no dirham is unaccounted for, not that savings is zero.",
      explanationCorrectAr: "الميزنة الصفرية تعني إعطاء كل درهم وظيفة — بما فيه المدخرات والاستثمارات وأموال الترفيه. 'الصفر' يعني عدم وجود درهم غير محسوب، لا أن المدخرات صفر.",
      explanationWrongEn: "Zero-based doesn't mean zero savings — savings is one of the categories. Every dirham is intentionally assigned, leaving nothing 'floating' and unaccounted for.",
      explanationWrongAr: "الصفرية لا تعني صفر مدخرات — المدخرات إحدى الفئات. كل درهم مخصص بشكل مقصود ولا يوجد شيء 'عائم' وغير محسوب.",
    },
    {
      id: "dd-5-q2", nodeId: "dd-5",
      textEn: "Income AED 10,000. Rent AED 3,500, groceries AED 800, transport AED 600, utilities AED 400, dining AED 700, savings AED 1,500. What is unaccounted for?",
      textAr: "الدخل ١٠٬٠٠٠ درهم. إيجار ٣٬٥٠٠، بقالة ٨٠٠، مواصلات ٦٠٠، مرافق ٤٠٠، مطاعم ٧٠٠، مدخرات ١٬٥٠٠. ما المبلغ غير المحسوب؟",
      choices: [
        { id: "a", textEn: "AED 500",   textAr: "٥٠٠ درهم"  },
        { id: "b", textEn: "AED 1,000", textAr: "١٬٠٠٠ درهم" },
        { id: "c", textEn: "AED 2,500", textAr: "٢٬٥٠٠ درهم" },
        { id: "d", textEn: "AED 3,000", textAr: "٣٬٠٠٠ درهم" },
      ],
      correctId: "c",
      explanationCorrectEn: "Total allocated: 3,500+800+600+400+700+1,500 = AED 7,500. Income AED 10,000 − AED 7,500 = AED 2,500 unaccounted. In a zero-based budget, assign this to a category before you spend it.",
      explanationCorrectAr: "إجمالي المخصص: ٣٥٠٠+٨٠٠+٦٠٠+٤٠٠+٧٠٠+١٥٠٠ = ٧٬٥٠٠ درهم. الدخل ١٠٬٠٠٠ − ٧٬٥٠٠ = ٢٬٥٠٠ درهم غير محسوب. في الميزنة الصفرية، خصّص هذا لفئة قبل إنفاقه.",
      explanationWrongEn: "3,500+800+600+400+700+1,500 = 7,500. 10,000−7,500 = 2,500 left to allocate. This unassigned money often disappears — give it a job.",
      explanationWrongAr: "٣٥٠٠+٨٠٠+٦٠٠+٤٠٠+٧٠٠+١٥٠٠ = ٧٬٥٠٠. ١٠٬٠٠٠−٧٬٥٠٠ = ٢٬٥٠٠ متبقية للتخصيص. هذا المال غير المخصص غالباً ما يختفي — أعطه وظيفة.",
    },
    {
      id: "dd-5-q3", nodeId: "dd-5",
      textEn: "A 'sinking fund' is:",
      textAr: "'صندوق التراكم' هو:",
      choices: [
        { id: "a", textEn: "An emergency fund that has been depleted",                   textAr: "صندوق طوارئ تم استنزافه"                              },
        { id: "b", textEn: "Money set aside monthly for a known upcoming expense",       textAr: "أموال تُودع شهرياً لمصروف معروف قادم"                },
        { id: "c", textEn: "A savings account that loses value over time",               textAr: "حساب ادخار يفقد قيمته مع الوقت"                      },
        { id: "d", textEn: "A government fund for low-income households",                textAr: "صندوق حكومي للأسر ذات الدخل المنخفض"                 },
      ],
      correctId: "b",
      explanationCorrectEn: "Sinking funds prevent 'irregular expense shock' — car insurance, school fees, Eid gifts. Save a small amount monthly and the big bill becomes just another planned expense.",
      explanationCorrectAr: "صناديق التراكم تمنع 'صدمة المصروف غير المنتظم' — تأمين السيارة ورسوم المدرسة وهدايا العيد. ادّخر مبلغاً صغيراً شهرياً ويصبح الفاتورة الكبيرة مجرد مصروف مخطط.",
      explanationWrongEn: "A sinking fund is purposeful saving for predictable irregular expenses. Examples: AED 200/month for car insurance, AED 300/month for annual holidays.",
      explanationWrongAr: "صندوق التراكم ادخار هادف للمصروفات غير المنتظمة المتوقعة. أمثلة: ٢٠٠ درهم/شهر لتأمين السيارة، ٣٠٠ درهم/شهر للعطلات السنوية.",
    },
  ],

  // ── Loan Lighthouse — ll-1: "What Is a Loan?" ────────────────────────────────
  "ll-1": [
    {
      id: "ll-1-q1", nodeId: "ll-1",
      textEn: "When you take a personal loan, your total repayment includes:",
      textAr: "عندما تأخذ قرضاً شخصياً، يشمل إجمالي سدادك:",
      choices: [
        { id: "a", textEn: "Only the principal (amount borrowed)",           textAr: "رأس المال فقط (المبلغ المقترض)"          },
        { id: "b", textEn: "The principal plus interest",                    textAr: "رأس المال زائد الفائدة"                  },
        { id: "c", textEn: "Interest only — principal is forgiven",          textAr: "الفائدة فقط — رأس المال يُعفى منه"       },
        { id: "d", textEn: "A flat fee regardless of how long you take",     textAr: "رسوم ثابتة بغض النظر عن مدة السداد"     },
      ],
      correctId: "b",
      explanationCorrectEn: "You always repay the principal (what you borrowed) plus interest (the bank's fee for lending it). The longer the term, the more interest you pay in total.",
      explanationCorrectAr: "تسدد دائماً رأس المال (ما اقترضته) زائد الفائدة (رسوم البنك على الإقراض). كلما طالت المدة، كلما دفعت فائدة أكثر في المجموع.",
      explanationWrongEn: "Principal + interest = total repayment. The bank lends you money as a service — interest is the price of that service.",
      explanationWrongAr: "رأس المال + الفائدة = إجمالي السداد. البنك يقرضك مالاً كخدمة — الفائدة هي سعر تلك الخدمة.",
    },
    {
      id: "ll-1-q2", nodeId: "ll-1",
      textEn: "The 'principal' in a loan refers to:",
      textAr: "'رأس المال' في القرض يشير إلى:",
      choices: [
        { id: "a", textEn: "The total amount repaid over the loan's full life",  textAr: "إجمالي المبلغ المسدّد على مدى القرض كاملاً" },
        { id: "b", textEn: "The original sum borrowed, not including interest",  textAr: "المبلغ الأصلي المقترض، لا يشمل الفائدة"     },
        { id: "c", textEn: "The monthly interest charge only",                   textAr: "رسوم الفائدة الشهرية فقط"                  },
        { id: "d", textEn: "The bank's profit on the entire loan",               textAr: "ربح البنك على القرض بأكمله"               },
      ],
      correctId: "b",
      explanationCorrectEn: "Principal = the amount you borrowed. Interest is added on top. Each repayment reduces the principal — the faster you reduce it, the less interest you pay overall.",
      explanationCorrectAr: "رأس المال = المبلغ الذي اقترضته. الفائدة تُضاف فوقه. كل سداد يخفض رأس المال — كلما خفضته أسرع، كلما دفعت فائدة أقل في المجموع.",
      explanationWrongEn: "Principal is the base loan amount. Interest is calculated on the outstanding principal, which is why early payments save you more money.",
      explanationWrongAr: "رأس المال هو مبلغ القرض الأساسي. تُحسب الفائدة على الرصيد القائم من رأس المال، ولهذا السبب المدفوعات المبكرة توفّر لك المزيد من المال.",
    },
    {
      id: "ll-1-q3", nodeId: "ll-1",
      textEn: "Omar borrows AED 20,000 at 12% per year (simple interest) over 2 years. Approximate total interest paid?",
      textAr: "يقترض عمر ٢٠٬٠٠٠ درهم بفائدة ١٢٪ سنوياً (فائدة بسيطة) لمدة سنتين. الفائدة الإجمالية التقريبية؟",
      choices: [
        { id: "a", textEn: "AED 1,200", textAr: "١٬٢٠٠ درهم" },
        { id: "b", textEn: "AED 2,400", textAr: "٢٬٤٠٠ درهم" },
        { id: "c", textEn: "AED 4,800", textAr: "٤٬٨٠٠ درهم" },
        { id: "d", textEn: "AED 240",   textAr: "٢٤٠ درهم"   },
      ],
      correctId: "c",
      explanationCorrectEn: "Simple interest: 20,000 × 12% × 2 = AED 4,800. Total repayment: AED 24,800. Always calculate total repayment — not just the monthly installment — before signing.",
      explanationCorrectAr: "الفائدة البسيطة: ٢٠٬٠٠٠ × ١٢٪ × ٢ = ٤٬٨٠٠ درهم. إجمالي السداد: ٢٤٬٨٠٠ درهم. احسب دائماً إجمالي السداد — ليس القسط الشهري فقط — قبل التوقيع.",
      explanationWrongEn: "20,000 × 0.12 × 2 = 4,800. You repay AED 24,800 in total. Always look at total repayment amount, not just the monthly payment, when comparing loans.",
      explanationWrongAr: "٢٠٬٠٠٠ × ٠.١٢ × ٢ = ٤٬٨٠٠. تسدد ٢٤٬٨٠٠ درهم إجمالاً. انظر دائماً إلى إجمالي مبلغ السداد، وليس القسط الشهري فقط، عند مقارنة القروض.",
    },
  ],

  // ── Loan Lighthouse — ll-2: "Interest Rates" ─────────────────────────────────
  "ll-2": [
    {
      id: "ll-2-q1", nodeId: "ll-2",
      textEn: "The Annual Percentage Rate (APR) on a loan represents:",
      textAr: "معدل النسبة السنوية (APR) على القرض يمثّل:",
      choices: [
        { id: "a", textEn: "The bank's annual profit margin",                     textAr: "هامش ربح البنك السنوي"                       },
        { id: "b", textEn: "The yearly cost of borrowing, including all fees",    textAr: "التكلفة السنوية الكاملة للاقتراض شاملة الرسوم" },
        { id: "c", textEn: "The monthly repayment amount",                        textAr: "مبلغ السداد الشهري"                          },
        { id: "d", textEn: "The government-set maximum interest rate",            textAr: "الحد الأقصى للفائدة المحدد حكومياً"           },
      ],
      correctId: "b",
      explanationCorrectEn: "APR is the true annual cost of borrowing — it includes the interest rate AND all fees. Always compare APR (not just the advertised rate) when choosing between loans.",
      explanationCorrectAr: "معدل النسبة السنوية هو التكلفة الحقيقية للاقتراض — يشمل معدل الفائدة وجميع الرسوم. قارن دائماً معدل النسبة السنوية (وليس السعر المُعلن فقط) عند الاختيار بين القروض.",
      explanationWrongEn: "APR = interest rate + fees, expressed annually. Two loans with the same interest rate can have very different APRs depending on processing fees and insurance requirements.",
      explanationWrongAr: "معدل النسبة السنوية = معدل الفائدة + الرسوم، معبّراً عنه سنوياً. قرضان بنفس معدل الفائدة يمكن أن يكون لهما معدلات نسبة سنوية مختلفة جداً بحسب رسوم المعالجة ومتطلبات التأمين.",
    },
    {
      id: "ll-2-q2", nodeId: "ll-2",
      textEn: "Compound interest on a loan differs from simple interest because:",
      textAr: "تختلف الفائدة المركّبة على القرض عن الفائدة البسيطة لأن:",
      choices: [
        { id: "a", textEn: "Simple interest grows faster since it's always calculated on the full principal", textAr: "الفائدة البسيطة تنمو أسرع لأنها تُحسب دائماً على رأس المال الكامل" },
        { id: "b", textEn: "Compound interest is calculated on principal plus accumulated interest",          textAr: "الفائدة المركّبة تُحسب على رأس المال زائد الفائدة المتراكمة"          },
        { id: "c", textEn: "Compound interest is always lower for the borrower",                             textAr: "الفائدة المركّبة أقل دائماً للمقترض"                                  },
        { id: "d", textEn: "They are calculated identically — only the name differs",                       textAr: "يُحسبان بشكل متطابق — فقط الاسم يختلف"                               },
      ],
      correctId: "b",
      explanationCorrectEn: "Compound interest charges interest on unpaid interest — the balance grows faster than simple interest. This is why credit card debt spirals so quickly if you only pay the minimum.",
      explanationCorrectAr: "الفائدة المركّبة تفرض فائدة على الفائدة غير المدفوعة — الرصيد ينمو أسرع من الفائدة البسيطة. لهذا السبب تتفاقم ديون بطاقات الائتمان بسرعة إذا دفعت الحد الأدنى فقط.",
      explanationWrongEn: "Compound = interest on interest. It makes savings grow faster but makes debt grow faster too. On loans, compound interest is more expensive than simple interest.",
      explanationWrongAr: "المركّبة = فائدة على فائدة. تجعل المدخرات تنمو أسرع لكنها تجعل الديون تنمو أسرع أيضاً. على القروض، الفائدة المركّبة أغلى من الفائدة البسيطة.",
    },
    {
      id: "ll-2-q3", nodeId: "ll-2",
      textEn: "Loan A: 15% APR. Loan B: 7% flat rate. Which is likely MORE expensive?",
      textAr: "قرض أ: ١٥٪ معدل نسبة سنوية. قرض ب: ٧٪ معدل ثابت. أيهما على الأرجح أغلى؟",
      choices: [
        { id: "a", textEn: "Loan A — 15% is higher than 7%",                              textAr: "قرض أ — ١٥٪ أعلى من ٧٪"                          },
        { id: "b", textEn: "Loan B — flat rates calculate on original principal throughout", textAr: "قرض ب — المعدل الثابت يُحسب على رأس المال الأصلي طوال المدة" },
        { id: "c", textEn: "They are equivalent",                                          textAr: "هما متكافئان"                                     },
        { id: "d", textEn: "Not enough information to compare",                            textAr: "معلومات غير كافية للمقارنة"                       },
      ],
      correctId: "b",
      explanationCorrectEn: "A 7% flat rate is calculated on the ORIGINAL principal every year, even as you pay it down. This is roughly equivalent to ~13–14% APR. Always convert to APR to compare properly.",
      explanationCorrectAr: "المعدل الثابت ٧٪ يُحسب على رأس المال الأصلي كل عام، حتى عندما تسدّده. هذا يعادل تقريباً ١٣–١٤٪ معدل نسبة سنوية. حوّل دائماً إلى معدل النسبة السنوية للمقارنة الصحيحة.",
      explanationWrongEn: "A flat rate sounds lower but is calculated on the original amount throughout. A 7% flat rate roughly equals 13–14% APR. Always use APR to compare loans fairly.",
      explanationWrongAr: "المعدل الثابت يبدو أقل لكنه يُحسب على المبلغ الأصلي طوال المدة. معدل ثابت ٧٪ يعادل تقريباً ١٣–١٤٪ معدل نسبة سنوية. استخدم دائماً معدل النسبة السنوية لمقارنة القروض بشكل عادل.",
    },
  ],

  // ── Loan Lighthouse — ll-5: "Loan Boss" (boss) ────────────────────────────────
  "ll-5": [
    {
      id: "ll-5-q1", nodeId: "ll-5",
      textEn: "The 'debt avalanche' repayment strategy means:",
      textAr: "استراتيجية سداد 'انهيار الدين' تعني:",
      choices: [
        { id: "a", textEn: "Paying off the smallest balance first for quick wins",  textAr: "سداد أصغر رصيد أولاً لتحقيق انتصارات سريعة" },
        { id: "b", textEn: "Paying the highest interest rate loan first to minimise total interest", textAr: "سداد القرض ذو أعلى معدل فائدة أولاً لتقليل إجمالي الفائدة" },
        { id: "c", textEn: "Making only minimum payments on all debts",             textAr: "دفع الحد الأدنى فقط على جميع الديون"        },
        { id: "d", textEn: "Consolidating all debts before making any payment",    textAr: "دمج جميع الديون قبل أي سداد"               },
      ],
      correctId: "b",
      explanationCorrectEn: "Debt avalanche = attack the highest-rate debt first. This saves the most money in interest over time. The 'snowball' method (smallest balance first) is slower but motivates some people.",
      explanationCorrectAr: "انهيار الدين = الهجوم على الدين ذي أعلى معدل أولاً. هذا يوفّر أكثر من حيث الفائدة بمرور الوقت. طريقة 'كرة الثلج' (أصغر رصيد أولاً) أبطأ لكنها تحفّز بعض الناس.",
      explanationWrongEn: "Avalanche = highest rate first (most mathematically optimal). Snowball = smallest balance first (most psychologically motivating). Both work — avalanche saves more money.",
      explanationWrongAr: "الانهيار = أعلى معدل أولاً (الأمثل رياضياً). كرة الثلج = أصغر رصيد أولاً (الأكثر تحفيزاً نفسياً). كلاهما يعمل — الانهيار يوفّر مالاً أكثر.",
    },
    {
      id: "ll-5-q2", nodeId: "ll-5",
      textEn: "Layla has a salary advance (0% interest) and a credit card balance at 36% APR — both AED 5,000. Which should she pay first?",
      textAr: "لدى ليلى سلفة راتب (٠٪ فائدة) ورصيد بطاقة ائتمان بمعدل ٣٦٪ سنوياً — كلاهما ٥٬٠٠٠ درهم. أيهما تسدد أولاً؟",
      choices: [
        { id: "a", textEn: "Salary advance — it was from her employer",          textAr: "سلفة الراتب — كانت من صاحب عملها"              },
        { id: "b", textEn: "Credit card — 36% APR makes it far more expensive",  textAr: "بطاقة الائتمان — ٣٦٪ سنوياً يجعلها أغلى بكثير" },
        { id: "c", textEn: "Split 50/50 each month",                             textAr: "قسّمها ٥٠/٥٠ كل شهر"                          },
        { id: "d", textEn: "Invest the money — returns will cover the interest", textAr: "استثمر المال — العوائد ستغطي الفائدة"          },
      ],
      correctId: "b",
      explanationCorrectEn: "36% APR costs AED 150/month in interest on AED 5,000. The salary advance costs nothing. Always pay off the most expensive debt first — regardless of its source.",
      explanationCorrectAr: "٣٦٪ سنوياً تكلّف ١٥٠ درهم شهرياً في فائدة على ٥٬٠٠٠ درهم. سلفة الراتب لا تكلف شيئاً. ادفع دائماً الدين الأغلى أولاً — بغض النظر عن مصدره.",
      explanationWrongEn: "Always compare interest rates. 36% APR on AED 5,000 = AED 150/month in interest. The salary advance at 0% costs nothing to carry — attack the expensive debt first.",
      explanationWrongAr: "قارن دائماً معدلات الفائدة. ٣٦٪ سنوياً على ٥٬٠٠٠ درهم = ١٥٠ درهم شهرياً فائدة. سلفة الراتب بـ٠٪ لا تكلف شيئاً للحمل — هاجم الدين الغالي أولاً.",
    },
    {
      id: "ll-5-q3", nodeId: "ll-5",
      textEn: "Debt consolidation is most beneficial when:",
      textAr: "دمج الديون يكون أكثر فائدة عندما:",
      choices: [
        { id: "a", textEn: "You want to have more loans at once",                             textAr: "تريد الحصول على المزيد من القروض في آنٍ واحد"        },
        { id: "b", textEn: "The new consolidated loan has a lower total interest cost",        textAr: "القرض الموحّد الجديد له تكلفة فائدة إجمالية أقل"   },
        { id: "c", textEn: "You want to reduce the number of payments (regardless of cost)",  textAr: "تريد تقليل عدد المدفوعات (بغض النظر عن التكلفة)"   },
        { id: "d", textEn: "Your credit score is already perfect",                            textAr: "درجة ائتمانك ممتازة بالفعل"                         },
      ],
      correctId: "b",
      explanationCorrectEn: "Consolidation is only a win if the total interest paid over the life of the new loan is less than your current combined debt costs. Simplifying payments at a higher rate is a step backward.",
      explanationCorrectAr: "الدمج فائدة فقط إذا كانت إجمالي الفائدة المدفوعة على مدى القرض الجديد أقل من تكاليف ديونك المجمّعة الحالية. تبسيط المدفوعات بمعدل أعلى خطوة للوراء.",
      explanationWrongEn: "Only consolidate if the new rate saves you money overall. Calculate total repayment — not just monthly payment — before deciding.",
      explanationWrongAr: "دمج فقط إذا وفّر لك المعدل الجديد مالاً بشكل عام. احسب إجمالي السداد — وليس القسط الشهري فقط — قبل القرار.",
    },
  ],
};
