import type { QuizQuestion } from "./quiz-types";

export const QUESTIONS_W14_W15: Record<string, QuizQuestion[]> = {

  // ── Scam Sentinel — ss-1: "Spotting Scams" ────────────────────────────────────
  "ss-1": [
    {
      id: "ss-1-q1", nodeId: "ss-1",
      textEn: "You receive a call from someone claiming to be your bank asking for your OTP (One-Time Password). You should:",
      textAr: "تلقّيت اتصالاً من شخص يدّعي أنه بنكك ويطلب كلمة المرور لمرة واحدة (OTP). يجب عليك:",
      choices: [
        { id: "a", textEn: "Provide it only if they know your account number",         textAr: "تعطيها فقط إذا عرفوا رقم حسابك"                    },
        { id: "b", textEn: "Never share OTPs — legitimate banks never ask for them",   textAr: "لا تشارك OTP أبداً — البنوك الشرعية لا تطلبها"     },
        { id: "c", textEn: "Share it only if the call comes from the bank's number",   textAr: "شاركها فقط إذا جاء الاتصال من رقم البنك"           },
        { id: "d", textEn: "Ask them to send a confirmation email first",              textAr: "اطلب منهم إرسال بريد تأكيد أولاً"                  },
      ],
      correctId: "b",
      explanationCorrectEn: "Banks NEVER ask for your OTP, PIN, or full card number over the phone or by message. An OTP is a one-time authorisation only you should use. Sharing it hands over full account access.",
      explanationCorrectAr: "البنوك لا تطلب NEVER رمز OTP أو رقم PIN أو الرقم الكامل للبطاقة عبر الهاتف أو الرسالة. رمز OTP هو تفويض لمرة واحدة يجب أن تستخدمه أنت فقط. مشاركته تسلّم وصولاً كاملاً للحساب.",
      explanationWrongEn: "No legitimate bank ever asks for your OTP. The number on caller ID can be spoofed. Hang up and call your bank on the official number on the back of your card.",
      explanationWrongAr: "لا يطلب أي بنك شرعي رمز OTP الخاص بك. يمكن انتحال رقم معرّف المتصل. أغلق الخط واتصل ببنكك على الرقم الرسمي المدوّن على ظهر بطاقتك.",
    },
    {
      id: "ss-1-q2", nodeId: "ss-1",
      textEn: "A 'phishing' message typically:",
      textAr: "رسالة 'التصيد الاحتيالي' عادةً:",
      choices: [
        { id: "a", textEn: "Only arrives through WhatsApp",                                   textAr: "تصل عبر واتساب فقط"                                    },
        { id: "b", textEn: "Mimics a trusted organisation to steal personal data",            textAr: "تقلّد جهة موثوقة لسرقة البيانات الشخصية"               },
        { id: "c", textEn: "Always contains obvious spelling errors",                         textAr: "تحتوي دائماً على أخطاء إملائية واضحة"                  },
        { id: "d", textEn: "Is only sent from unknown email domains",                         textAr: "تُرسَل فقط من نطاقات بريد إلكتروني مجهولة"             },
      ],
      correctId: "b",
      explanationCorrectEn: "Phishing mimics banks, DEWA, du/Etisalat, the RTA, Amazon — any trusted brand. Modern phishing is sophisticated: real logos, correct spelling, fake but convincing URLs.",
      explanationCorrectAr: "التصيد يقلّد البنوك وهيئة كهرباء ودبي ودو/اتصالات وهيئة الطرق والمواصلات وأمازون — أي علامة تجارية موثوقة. التصيد الحديث متطور: شعارات حقيقية وإملاء صحيح وعناوين URL مزيفة لكن مقنعة.",
      explanationWrongEn: "Phishing attacks now arrive via email, SMS, WhatsApp, Instagram DM, and fake calls. Always verify independently — never click links in unsolicited messages.",
      explanationWrongAr: "هجمات التصيد تصل الآن عبر البريد الإلكتروني والرسائل القصيرة وواتساب ورسائل إنستغرام المباشرة والمكالمات المزيفة. تحقق دائماً بشكل مستقل — لا تنقر أبداً على روابط في رسائل غير مطلوبة.",
    },
    {
      id: "ss-1-q3", nodeId: "ss-1",
      textEn: "Which of these is a RED FLAG in a financial message you receive?",
      textAr: "أيٌّ من التالي علامة تحذير حمراء في رسالة مالية تتلقّاها؟",
      choices: [
        { id: "a", textEn: "Your name is spelled correctly in the message",                  textAr: "اسمك مكتوب بشكل صحيح في الرسالة"                        },
        { id: "b", textEn: "Extreme urgency: 'Act NOW — account closes in 1 hour!'",        textAr: "إلحاح مفرط: 'تصرّف الآن — حسابك يُغلق خلال ساعة!'"     },
        { id: "c", textEn: "The message uses the sender's official logo",                   textAr: "الرسالة تستخدم الشعار الرسمي للمرسِل"                    },
        { id: "d", textEn: "A phone number is included in the message",                     textAr: "رقم هاتف مضمَّن في الرسالة"                              },
      ],
      correctId: "b",
      explanationCorrectEn: "Manufactured urgency is a hallmark of scams — it bypasses your rational thinking. Legitimate organisations don't pressure you into acting within minutes or hours.",
      explanationCorrectAr: "الإلحاح المصطنع هو سمة مميزة للنصب — يتجاوز تفكيرك العقلاني. المنظمات الشرعية لا تضغط عليك للتصرف خلال دقائق أو ساعات.",
      explanationWrongEn: "Real urgency = red flag. Scammers create pressure to prevent you from thinking clearly. If a message says 'act now or lose everything', slow down — it's almost always a scam.",
      explanationWrongAr: "الإلحاح الحقيقي = علامة حمراء. المحتالون يخلقون ضغطاً لمنعك من التفكير بوضوح. إذا قالت رسالة 'تصرّف الآن أو ستخسر كل شيء'، تمهّل — إنها دائماً تقريباً عملية نصب.",
    },
  ],

  // ── Scam Sentinel — ss-2: "Common UAE Scams" ─────────────────────────────────
  "ss-2": [
    {
      id: "ss-2-q1", nodeId: "ss-2",
      textEn: "Investment scams typically promise:",
      textAr: "عمليات النصب الاستثمارية تعد عادةً بـ:",
      choices: [
        { id: "a", textEn: "Returns slightly above savings accounts (4–5%)",      textAr: "عوائد أعلى قليلاً من حسابات الادخار (٤–٥٪)"    },
        { id: "b", textEn: "Guaranteed high returns with little or no risk",       textAr: "عوائد مرتفعة مضمونة مع مخاطرة ضئيلة أو معدومة" },
        { id: "c", textEn: "Returns regulated and verified by the UAE government", textAr: "عوائد منظَّمة ومتحقق منها من قِبل حكومة الإمارات" },
        { id: "d", textEn: "Returns tied to official UAE bank deposit rates",      textAr: "عوائد مرتبطة بأسعار الودائع البنكية الرسمية"    },
      ],
      correctId: "b",
      explanationCorrectEn: "No legitimate investment guarantees high returns with no risk. Real investments involve real risk. 'Guaranteed 30% monthly returns' is the classic fraud formula.",
      explanationCorrectAr: "لا استثمار شرعي يضمن عوائد مرتفعة بلا مخاطرة. الاستثمارات الحقيقية تنطوي على مخاطرة حقيقية. 'عوائد شهرية مضمونة ٣٠٪' هي الصيغة الاحتيالية الكلاسيكية.",
      explanationWrongEn: "Real investments = real risk. The higher the promised return, the higher the suspicion should be. If it sounds too good to be true — it is.",
      explanationWrongAr: "الاستثمارات الحقيقية = مخاطرة حقيقية. كلما زاد العائد الموعود، كلما ارتفع الشك. إذا بدا أفضل مما ينبغي — فهو كذلك.",
    },
    {
      id: "ss-2-q2", nodeId: "ss-2",
      textEn: "If you suspect you've been scammed in the UAE, you should FIRST:",
      textAr: "إذا اشتبهت في تعرّضك للنصب في الإمارات، يجب عليك أولاً:",
      choices: [
        { id: "a", textEn: "Stay quiet to avoid embarrassment",                               textAr: "الصمت تجنّباً للإحراج"                                 },
        { id: "b", textEn: "Try to recover the money yourself by sending more",               textAr: "محاولة استرداد المال بنفسك بإرسال المزيد"              },
        { id: "c", textEn: "Report immediately to your bank AND Dubai/Abu Dhabi Police",      textAr: "الإبلاغ فوراً لبنكك وشرطة دبي/أبوظبي"                  },
        { id: "d", textEn: "Wait 30 days to see if the situation resolves itself",            textAr: "الانتظار ٣٠ يوماً لمعرفة إذا كان الوضع يحل نفسه"       },
      ],
      correctId: "c",
      explanationCorrectEn: "Speed is critical. Report to your bank immediately (they can sometimes reverse transfers). File a police report at eCrime (Dubai Police cybercrime portal). Every hour matters.",
      explanationCorrectAr: "السرعة حاسمة. أبلغ بنكك فوراً (يمكنهم أحياناً عكس التحويلات). قدّم بلاغاً للشرطة على بوابة eCrime (بوابة جرائم الإنترنت لشرطة دبي). كل ساعة مهمة.",
      explanationWrongEn: "Act immediately: contact bank + police. Time matters for reversing transactions. Dubai Police eCrime portal, Abu Dhabi Police — report quickly. Don't be embarrassed; this happens to many people.",
      explanationWrongAr: "تصرّف فوراً: تواصل مع البنك + الشرطة. الوقت مهم لعكس المعاملات. بوابة eCrime لشرطة دبي وشرطة أبوظبي — أبلغ بسرعة. لا تستحِ؛ يحدث هذا لكثير من الناس.",
    },
    {
      id: "ss-2-q3", nodeId: "ss-2",
      textEn: "A WhatsApp message from an unknown number says 'I'm stuck abroad, please send AED 2,000 urgently — I'll repay you tomorrow.' Your best response:",
      textAr: "رسالة واتساب من رقم مجهول تقول: 'أنا عالق في الخارج، أرسل ٢٬٠٠٠ درهم بشكل عاجل — سأردّها غداً.' أفضل ردّ:",
      choices: [
        { id: "a", textEn: "Send it — they know your number so they must know you",     textAr: "أرسلها — يعرفون رقمك إذن هم يعرفونك"               },
        { id: "b", textEn: "Verify by calling the person directly through a known contact method", textAr: "تحقق بالاتصال المباشر بالشخص عبر طريقة تواصل معروفة" },
        { id: "c", textEn: "Send half the amount to reduce your risk",                  textAr: "أرسل نصف المبلغ لتقليل مخاطرتك"                    },
        { id: "d", textEn: "Block the number without responding",                       textAr: "احظر الرقم دون الرد"                                },
      ],
      correctId: "b",
      explanationCorrectEn: "This is a classic 'stranded traveller' scam. Before sending any money, independently verify via a phone call to the person's real number or by contacting a mutual friend.",
      explanationCorrectAr: "هذه عملية نصب 'المسافر المحاصر' الكلاسيكية. قبل إرسال أي مال، تحقق بشكل مستقل عبر اتصال هاتفي بالرقم الحقيقي للشخص أو بالتواصل مع صديق مشترك.",
      explanationWrongEn: "Never send money without independent verification. Call the person on a number you already have. Scammers send this to thousands of numbers hoping someone has the 'right' contact.",
      explanationWrongAr: "لا ترسل مالاً دون تحقق مستقل. اتصل بالشخص على رقم لديك بالفعل. يرسل المحتالون هذا إلى آلاف الأرقام على أمل أن يكون لدى شخص ما جهة الاتصال 'الصحيحة'.",
    },
  ],

  // ── Scam Sentinel — ss-5: "Scam Boss" (boss) ─────────────────────────────────
  "ss-5": [
    {
      id: "ss-5-q1", nodeId: "ss-5",
      textEn: "A message says: 'Congratulations! You've won AED 50,000. Send AED 500 to release your prize.' This is:",
      textAr: "رسالة تقول: 'مبروك! لقد فزت بـ٥٠٬٠٠٠ درهم. أرسل ٥٠٠ درهم لتحرير جائزتك.' هذه:",
      choices: [
        { id: "a", textEn: "Possibly legitimate — prize draws are common in the UAE",  textAr: "ربما شرعية — سحوبات الجوائز شائعة في الإمارات"  },
        { id: "b", textEn: "An advance-fee scam — you never win what you didn't enter", textAr: "عملية نصب بالرسوم المسبقة — لا تفوز بما لم تدخله" },
        { id: "c", textEn: "Legal if the sending company is registered",               textAr: "قانونية إذا كانت الشركة المرسِلة مسجَّلة"         },
        { id: "d", textEn: "Worth following up to verify before deciding",             textAr: "تستحق المتابعة للتحقق قبل القرار"                 },
      ],
      correctId: "b",
      explanationCorrectEn: "Advance-fee scams: you pay a small fee to unlock a large prize that doesn't exist. You can never win a lottery you didn't enter. The AED 500 is the scam — the AED 50,000 never comes.",
      explanationCorrectAr: "عمليات نصب الرسوم المسبقة: تدفع رسوماً صغيرة لفتح جائزة كبيرة غير موجودة. لا يمكنك الفوز بيانصيب لم تشترك فيه. الـ٥٠٠ درهم هي عملية النصب — الـ٥٠٬٠٠٠ درهم لا تأتي أبداً.",
      explanationWrongEn: "You can't win a competition you never entered. 'Pay to claim a prize' is always a scam. Delete and block.",
      explanationWrongAr: "لا يمكنك الفوز في مسابقة لم تدخلها. 'ادفع للمطالبة بجائزة' دائماً عملية نصب. احذف وواحظر.",
    },
    {
      id: "ss-5-q2", nodeId: "ss-5",
      textEn: "Which security measure BEST protects your online banking from unauthorised access?",
      textAr: "أي إجراء أمني يحمي بشكل أفضل مصرفيتك الإلكترونية من الوصول غير المصرّح به؟",
      choices: [
        { id: "a", textEn: "Using the same strong password on all financial accounts",  textAr: "استخدام كلمة مرور قوية واحدة لجميع الحسابات المالية" },
        { id: "b", textEn: "Enabling multi-factor authentication (MFA) on your banking app", textAr: "تفعيل المصادقة متعددة العوامل (MFA) على تطبيقك البنكي" },
        { id: "c", textEn: "Never logging into your bank on a smartphone",            textAr: "عدم تسجيل الدخول لبنكك على هاتف ذكي أبداً"          },
        { id: "d", textEn: "Sharing login details only with trusted family members",   textAr: "مشاركة بيانات تسجيل الدخول مع أفراد العائلة الموثوقين فقط" },
      ],
      correctId: "b",
      explanationCorrectEn: "MFA = even if a scammer has your password, they can't log in without the second factor (biometric, OTP, push notification). It's the single most effective account protection available.",
      explanationCorrectAr: "المصادقة متعددة العوامل = حتى لو كان للمحتال كلمة مرورك، لا يمكنه تسجيل الدخول دون العامل الثاني (البيومتري أو OTP أو الإشعار الدفعي). إنها أكثر حماية الحسابات فاعلية المتاحة.",
      explanationWrongEn: "MFA is the gold standard. Even if your password leaks, the attacker still can't access your account without the second factor. Enable it on every financial account.",
      explanationWrongAr: "المصادقة متعددة العوامل هي المعيار الذهبي. حتى لو تسرّبت كلمة مرورك، لا يزال المهاجم غير قادر على الوصول لحسابك دون العامل الثاني. فعّلها على كل حساب مالي.",
    },
    {
      id: "ss-5-q3", nodeId: "ss-5",
      textEn: "A 'romance scam' typically works by:",
      textAr: "عملية 'نصب العلاقات العاطفية' تعمل عادةً عبر:",
      choices: [
        { id: "a", textEn: "Someone overcharging at a restaurant or hotel",               textAr: "شخص يفرض رسوماً زائدة في مطعم أو فندق"                 },
        { id: "b", textEn: "A fake online persona that builds trust over time, then requests money", textAr: "شخصية مزيفة عبر الإنترنت تبني ثقة مع الوقت ثم تطلب مالاً" },
        { id: "c", textEn: "Counterfeit goods sold as genuine items",                      textAr: "سلع مزيفة تُباع كبضائع أصلية"                         },
        { id: "d", textEn: "Fake travel deals with non-existent bookings",                textAr: "عروض سفر مزيفة بحجوزات غير موجودة"                    },
      ],
      correctId: "b",
      explanationCorrectEn: "Romance scammers build a relationship over weeks or months, then manufacture a crisis ('stuck abroad', 'medical emergency', 'business deal gone wrong') and ask for money transfers.",
      explanationCorrectAr: "محتالو العلاقات يبنون علاقة على مدى أسابيع أو أشهر، ثم يصطنعون أزمة ('عالق في الخارج' أو 'طارئ طبي' أو 'صفقة عمل فاشلة') ويطلبون تحويلات مالية.",
      explanationWrongEn: "Romance scammers invest months building trust before asking for money. Warning signs: never meets in person, always has a crisis, pushes for money transfers rather than meeting.",
      explanationWrongAr: "محتالو العلاقات يستثمرون أشهراً في بناء الثقة قبل طلب المال. علامات التحذير: لا يلتقي شخصياً أبداً، لديه دائماً أزمة، يدفع نحو تحويلات مالية بدلاً من الاجتماع.",
    },
  ],

  // ── Goal Garden — gol-1: "Setting Financial Goals" ───────────────────────────
  "gol-1": [
    {
      id: "gol-1-q1", nodeId: "gol-1",
      textEn: "A SMART financial goal is one that is:",
      textAr: "الهدف المالي الذكي (SMART) هو الذي يكون:",
      choices: [
        { id: "a", textEn: "Simple, Manageable, Achievable, Relevant, Timely",          textAr: "بسيطاً وقابلاً للإدارة وقابلاً للتحقيق وذا صلة وفي الوقت المناسب" },
        { id: "b", textEn: "Specific, Measurable, Achievable, Relevant, Time-bound",    textAr: "محدداً وقابلاً للقياس وقابلاً للتحقيق وذا صلة ومحدد بوقت"          },
        { id: "c", textEn: "Systematic, Monthly, Automated, Reviewed, Tracked",         textAr: "منهجياً وشهرياً ومؤتمتاً ومراجَعاً ومتتبَّعاً"                     },
        { id: "d", textEn: "Savings-focused, Minimalist, Accountable, Realistic, Thoughtful", textAr: "موجَّهاً للادخار وبسيطاً ومسؤولاً وواقعياً وعميقاً"              },
      ],
      correctId: "b",
      explanationCorrectEn: "SMART = Specific, Measurable, Achievable, Relevant, Time-bound. Each letter transforms a vague wish into an actionable plan. Without SMART, goals stay aspirations.",
      explanationCorrectAr: "SMART = محدد وقابل للقياس وقابل للتحقيق وذو صلة ومحدد بوقت. كل حرف يحوّل أمنية غامضة إلى خطة قابلة للتنفيذ. بدون SMART، تبقى الأهداف تطلعات.",
      explanationWrongEn: "SMART: Specific (not 'save more'), Measurable (AED amount), Achievable (realistic), Relevant (matters to you), Time-bound (by when). All 5 elements are required.",
      explanationWrongAr: "SMART: محدد (ليس 'ادّخر أكثر')، قابل للقياس (مبلغ بالدرهم)، قابل للتحقيق (واقعي)، ذو صلة (يهمك)، محدد بوقت (بحلول متى). جميع العناصر الخمسة مطلوبة.",
    },
    {
      id: "gol-1-q2", nodeId: "gol-1",
      textEn: "Which is a SMART version of the vague goal 'I want to save more money'?",
      textAr: "أيٌّ من التالي نسخة ذكية (SMART) من الهدف الغامض 'أريد ادخار المزيد من المال'؟",
      choices: [
        { id: "a", textEn: "I will try to save AED 200 sometimes when I remember",                    textAr: "سأحاول ادخار ٢٠٠ درهم أحياناً عندما أتذكر"                                 },
        { id: "b", textEn: "I will save AED 500/month for 12 months to build a AED 6,000 fund",      textAr: "سأدّخر ٥٠٠ درهم/شهر لمدة ١٢ شهراً لبناء صندوق ٦٬٠٠٠ درهم"               },
        { id: "c", textEn: "I want to be financially secure by the end of the year",                  textAr: "أريد أن أكون آمناً مالياً بنهاية العام"                                   },
        { id: "d", textEn: "Saving is my top priority this year",                                     textAr: "الادخار هو أولويتي القصوى هذا العام"                                     },
      ],
      correctId: "b",
      explanationCorrectEn: "Option B is SMART: Specific (AED 500/month), Measurable (AED 6,000), Achievable (500/month is a fixed action), Relevant (building savings), Time-bound (12 months).",
      explanationCorrectAr: "الخيار ب ذكي: محدد (٥٠٠ درهم/شهر)، قابل للقياس (٦٬٠٠٠ درهم)، قابل للتحقيق (٥٠٠/شهر إجراء ثابت)، ذو صلة (بناء مدخرات)، محدد بوقت (١٢ شهراً).",
      explanationWrongEn: "'Try sometimes when I remember' is not a goal. 'Be financially secure' is not measurable. Only option B has all 5 SMART components: amount, timeframe, specific action.",
      explanationWrongAr: "'حاول أحياناً عندما تتذكر' ليس هدفاً. 'كن آمناً مالياً' غير قابل للقياس. فقط الخيار ب يحتوي على جميع المكونات الخمسة لـSMART: مبلغ وإطار زمني وإجراء محدد.",
    },
    {
      id: "gol-1-q3", nodeId: "gol-1",
      textEn: "Automating your savings means:",
      textAr: "أتمتة مدخراتك تعني:",
      choices: [
        { id: "a", textEn: "Using a robo-advisor to pick investments for you",               textAr: "استخدام مستشار آلي لاختيار الاستثمارات نيابةً عنك"     },
        { id: "b", textEn: "Setting up an auto-transfer to savings on your salary date",     textAr: "إعداد تحويل تلقائي للمدخرات في تاريخ راتبك"           },
        { id: "c", textEn: "Letting the bank manage your finances entirely",                textAr: "السماح للبنك بإدارة ماليّاتك بالكامل"                 },
        { id: "d", textEn: "Saving only in digital currencies automatically",               textAr: "الادخار تلقائياً في العملات الرقمية فقط"              },
      ],
      correctId: "b",
      explanationCorrectEn: "Automate the transfer the moment your salary lands. You never see the money — you can't spend what you don't have access to. The most powerful savings habit is removing the decision entirely.",
      explanationCorrectAr: "أتمت التحويل في اللحظة التي يصل فيها راتبك. لا ترى المال أبداً — لا يمكنك إنفاق ما ليس لديك وصول إليه. أقوى عادة في الادخار هي إزالة القرار كلياً.",
      explanationWrongEn: "Automation = schedule the transfer for the same day as payday. Remove the decision. The biggest savings mistake is 'I'll transfer what's left at the end of the month' — nothing's left.",
      explanationWrongAr: "الأتمتة = جدوِل التحويل في نفس يوم الراتب. أزِل القرار. أكبر خطأ في الادخار هو 'سأحوّل ما تبقّى في نهاية الشهر' — لا يتبقى شيء.",
    },
  ],

  // ── Goal Garden — gol-2: "Short, Medium & Long-Term" ─────────────────────────
  "gol-2": [
    {
      id: "gol-2-q1", nodeId: "gol-2",
      textEn: "A 'short-term financial goal' typically refers to a target within:",
      textAr: "الهدف المالي 'قصير الأجل' يشير عادةً إلى هدف ضمن:",
      choices: [
        { id: "a", textEn: "10–30 years",        textAr: "١٠–٣٠ عاماً" },
        { id: "b", textEn: "5–10 years",         textAr: "٥–١٠ سنوات" },
        { id: "c", textEn: "Up to 1–2 years",    textAr: "حتى ١–٢ سنوات" },
        { id: "d", textEn: "Exactly 6 months",   textAr: "٦ أشهر بالضبط" },
      ],
      correctId: "c",
      explanationCorrectEn: "Short-term = 1–2 years (emergency fund, holiday, car). Medium-term = 3–7 years (house deposit, education). Long-term = 10+ years (retirement). Knowing the horizon determines where to put the money.",
      explanationCorrectAr: "قصير الأجل = ١–٢ سنوات (صندوق طوارئ وعطلة وسيارة). متوسط الأجل = ٣–٧ سنوات (دفعة منزل وتعليم). طويل الأجل = ١٠+ سنوات (تقاعد). معرفة الأفق تحدد أين تضع المال.",
      explanationWrongEn: "Short-term ≈ 1–2 years. These goals should be kept in cash or near-cash (savings accounts), not investments that can lose value right when you need to withdraw.",
      explanationWrongAr: "قصير الأجل ≈ ١–٢ سنوات. يجب الاحتفاظ بهذه الأهداف في نقد أو قريب من النقد (حسابات ادخار)، وليس في استثمارات يمكن أن تخسر قيمتها في الوقت الذي تحتاج فيه للسحب.",
    },
    {
      id: "gol-2-q2", nodeId: "gol-2",
      textEn: "Which is a 'long-term' financial goal?",
      textAr: "أيٌّ من التالي هدف مالي 'طويل الأجل'؟",
      choices: [
        { id: "a", textEn: "Saving for Eid gifts next month",            textAr: "الادخار لهدايا العيد الشهر القادم"          },
        { id: "b", textEn: "Building a 3-month emergency fund this year", textAr: "بناء صندوق طوارئ لمدة ٣ أشهر هذا العام"    },
        { id: "c", textEn: "Paying off a car loan in 18 months",         textAr: "سداد قرض سيارة في ١٨ شهراً"                },
        { id: "d", textEn: "Retirement savings over the next 25 years",  textAr: "مدخرات التقاعد على مدى ٢٥ عاماً القادمة"   },
      ],
      correctId: "d",
      explanationCorrectEn: "25-year retirement savings is quintessentially long-term. Long-term goals can weather investment volatility — time lets compound growth work fully. Equities are appropriate for 10+ year horizons.",
      explanationCorrectAr: "مدخرات التقاعد على ٢٥ عاماً هي نموذج الأهداف طويلة الأجل. الأهداف طويلة الأجل تستطيع تحمّل تذبذب الاستثمار — الوقت يتيح للنمو المركّب أن يعمل بالكامل. الأسهم مناسبة لآفاق ١٠+ سنوات.",
      explanationWrongEn: "Long-term = 10+ years. Only retirement savings (25 years) qualifies. The others are short-term or medium-term, requiring more liquid, less volatile savings vehicles.",
      explanationWrongAr: "طويل الأجل = ١٠+ سنوات. فقط مدخرات التقاعد (٢٥ عاماً) تستوفي الشرط. البقية قصيرة أو متوسطة الأجل، تتطلب وسائل ادخار أكثر سيولة وأقل تذبذباً.",
    },
    {
      id: "gol-2-q3", nodeId: "gol-2",
      textEn: "Mariam wants AED 60,000 for a car in 2 years. She has AED 12,000 saved. How much must she save monthly?",
      textAr: "تريد مريم ٦٠٬٠٠٠ درهم لسيارة في سنتين. لديها ١٢٬٠٠٠ درهم مدخرة. كم يجب أن تدّخر شهرياً؟",
      choices: [
        { id: "a", textEn: "AED 1,500", textAr: "١٬٥٠٠ درهم" },
        { id: "b", textEn: "AED 2,000", textAr: "٢٬٠٠٠ درهم" },
        { id: "c", textEn: "AED 2,500", textAr: "٢٬٥٠٠ درهم" },
        { id: "d", textEn: "AED 3,000", textAr: "٣٬٠٠٠ درهم" },
      ],
      correctId: "b",
      explanationCorrectEn: "Remaining needed: AED 60,000 − AED 12,000 = AED 48,000. Over 24 months: AED 48,000 ÷ 24 = AED 2,000/month. This is the power of a SMART goal — it tells you exactly what to do.",
      explanationCorrectAr: "المبلغ المطلوب المتبقي: ٦٠٬٠٠٠ − ١٢٬٠٠٠ = ٤٨٬٠٠٠ درهم. على مدى ٢٤ شهراً: ٤٨٬٠٠٠ ÷ ٢٤ = ٢٬٠٠٠ درهم/شهر. هذه قوة الهدف الذكي — يخبرك بالضبط ماذا تفعل.",
      explanationWrongEn: "Needed: 60,000 − 12,000 = 48,000. Months: 2 × 12 = 24. Monthly: 48,000 ÷ 24 = 2,000. Breaking goals into monthly actions removes the mystery from saving.",
      explanationWrongAr: "المطلوب: ٦٠٬٠٠٠ − ١٢٬٠٠٠ = ٤٨٬٠٠٠. الأشهر: ٢ × ١٢ = ٢٤. الشهري: ٤٨٬٠٠٠ ÷ ٢٤ = ٢٬٠٠٠. تقسيم الأهداف إلى إجراءات شهرية يزيل الغموض من الادخار.",
    },
  ],

  // ── Goal Garden — gol-5: "Goal Master" (boss) ────────────────────────────────
  "gol-5": [
    {
      id: "gol-5-q1", nodeId: "gol-5",
      textEn: "The recommended priority order for building financial stability is:",
      textAr: "ترتيب الأولوية الموصى به لبناء الاستقرار المالي هو:",
      choices: [
        { id: "a", textEn: "Invest first, then save, then pay off debt",                          textAr: "استثمر أولاً، ثم ادّخر، ثم اسدد الديون"                              },
        { id: "b", textEn: "Spend freely first, save what's left at month end",                   textAr: "أنفق بحرية أولاً، ادّخر ما تبقّى في نهاية الشهر"                     },
        { id: "c", textEn: "Emergency fund → high-interest debt → retirement → other goals",      textAr: "صندوق طوارئ → ديون مرتفعة الفائدة → تقاعد → أهداف أخرى"             },
        { id: "d", textEn: "Personal goals first, financial stability comes later",               textAr: "الأهداف الشخصية أولاً، الاستقرار المالي يأتي لاحقاً"                  },
      ],
      correctId: "c",
      explanationCorrectEn: "The proven sequence: 1) Build emergency fund (protection). 2) Kill high-interest debt (guaranteed return = rate saved). 3) Fund retirement (time = compound magic). 4) Everything else.",
      explanationCorrectAr: "التسلسل المثبت: ١) بناء صندوق الطوارئ (حماية). ٢) إزالة الديون مرتفعة الفائدة (عائد مضمون = معدل موفَّر). ٣) تمويل التقاعد (الوقت = سحر التركيب). ٤) كل شيء آخر.",
      explanationWrongEn: "Emergency fund first (you need protection before growth). Then expensive debt. Then retirement. Then everything else. This order prevents catastrophic setbacks.",
      explanationWrongAr: "صندوق الطوارئ أولاً (تحتاج للحماية قبل النمو). ثم الديون الغالية. ثم التقاعد. ثم كل شيء آخر. هذا الترتيب يمنع النكسات الكارثية.",
    },
    {
      id: "gol-5-q2", nodeId: "gol-5",
      textEn: "To track progress on a savings goal effectively, the best habit is:",
      textAr: "لتتبع التقدم نحو هدف ادخاري بفاعلية، أفضل عادة هي:",
      choices: [
        { id: "a", textEn: "Check once at the end of each year",                                  textAr: "تحقق مرة واحدة في نهاية كل عام"                                    },
        { id: "b", textEn: "Review monthly and adjust contributions if life changes",              textAr: "راجع شهرياً وعدّل المساهمات إذا تغيّرت الحياة"                       },
        { id: "c", textEn: "Never review — checking creates anxiety",                              textAr: "لا تراجع أبداً — التحقق يخلق قلقاً"                                },
        { id: "d", textEn: "Check daily — the more often the better",                             textAr: "تحقق يومياً — كلما تكرر كلما كان أفضل"                              },
      ],
      correctId: "b",
      explanationCorrectEn: "Monthly reviews keep you on track and allow adjustment. If you got a raise, increase contributions. If an expense spiked, you can recalibrate. Annual is too infrequent; daily is obsessive.",
      explanationCorrectAr: "المراجعات الشهرية تبقيك على المسار وتتيح التعديل. إذا حصلت على زيادة، ارفع المساهمات. إذا ارتفع مصروف، يمكنك إعادة الضبط. السنوي نادر جداً؛ اليومي وسواسي.",
      explanationWrongEn: "Monthly check-ins are the sweet spot: frequent enough to course-correct, not so frequent that you're obsessing. Review: am I on track? Do I need to adjust?",
      explanationWrongAr: "المراجعات الشهرية هي النقطة المثالية: متكررة بما يكفي للتصحيح، وليست متكررة جداً بحيث تصبح وسواساً. راجع: هل أنا على المسار؟ هل أحتاج إلى تعديل؟",
    },
    {
      id: "gol-5-q3", nodeId: "gol-5",
      textEn: "The single most effective way to ensure you actually reach your savings goals is:",
      textAr: "الطريقة الأكثر فاعلية والأفضل لضمان تحقيق أهداف ادخارك فعلاً هي:",
      choices: [
        { id: "a", textEn: "Read financial books every week",                                     textAr: "قراءة كتب مالية كل أسبوع"                                         },
        { id: "b", textEn: "Set up automatic transfers to dedicated savings on payday",            textAr: "إعداد تحويلات تلقائية لمدخرات مخصصة في يوم الراتب"                  },
        { id: "c", textEn: "Set a reminder to transfer savings at the end of the month",          textAr: "ضبط تذكير لتحويل المدخرات في نهاية الشهر"                           },
        { id: "d", textEn: "Tell your friends about your savings goals for accountability",       textAr: "أخبر أصدقاءك بأهدافك الادخارية لتكون محاسَباً"                      },
      ],
      correctId: "b",
      explanationCorrectEn: "Automation removes willpower from the equation. A reminder at month-end means you save only if money is left. Automation on payday means you save first, spend what's left — guaranteed.",
      explanationCorrectAr: "الأتمتة تزيل الإرادة من المعادلة. تذكير في نهاية الشهر يعني الادخار فقط إذا بقي مال. الأتمتة في يوم الراتب تعني ادخار أولاً وإنفاق ما تبقّى — مضمون.",
      explanationWrongEn: "Automation is the #1 wealth habit. Remove the decision: schedule the transfer for payday. Books, reminders, and social accountability all help — but automation is the most reliable.",
      explanationWrongAr: "الأتمتة هي عادة الثروة الأولى. أزِل القرار: جدوِل التحويل ليوم الراتب. الكتب والتذكيرات والمساءلة الاجتماعية تساعد كلها — لكن الأتمتة هي الأكثر موثوقية.",
    },
  ],
};
