import type { QuizQuestion } from "./quiz-types";

export const QUESTIONS_W10_W11: Record<string, QuizQuestion[]> = {

  // ── Halal Harbour — hh-1: "Islamic Finance Basics" ───────────────────────────
  "hh-1": [
    {
      id: "hh-1-q1", nodeId: "hh-1",
      textEn: "The core principle that distinguishes Islamic finance from conventional finance is:",
      textAr: "المبدأ الأساسي الذي يميّز التمويل الإسلامي عن التمويل التقليدي هو:",
      choices: [
        { id: "a", textEn: "Lower interest rates than conventional banks",           textAr: "أسعار فائدة أقل من البنوك التقليدية"             },
        { id: "b", textEn: "The prohibition of riba (interest/usury)",               textAr: "تحريم الربا (الفائدة/الغش)"                     },
        { id: "c", textEn: "Only Muslims are allowed to use Islamic banks",          textAr: "فقط المسلمون مسموح لهم باستخدام البنوك الإسلامية" },
        { id: "d", textEn: "It operates completely without any form of regulation",  textAr: "يعمل دون أي شكل من أشكال التنظيم"               },
      ],
      correctId: "b",
      explanationCorrectEn: "Islamic finance prohibits riba (interest), excessive uncertainty (gharar), and investment in prohibited activities (alcohol, gambling). Money must be tied to real economic activity.",
      explanationCorrectAr: "التمويل الإسلامي يحرّم الربا (الفائدة) والغرر المفرط (الغرر) والاستثمار في الأنشطة المحرّمة (الخمر والقمار). يجب أن يرتبط المال بالنشاط الاقتصادي الحقيقي.",
      explanationWrongEn: "The prohibition of riba (interest) is the cornerstone. Islamic banks make profit through ownership, leasing, and profit-sharing — not charging interest on loans.",
      explanationWrongAr: "تحريم الربا (الفائدة) هو حجر الأساس. البنوك الإسلامية تحقق الربح من خلال الملكية والتأجير وتقاسم الأرباح — وليس تحصيل الفائدة على القروض.",
    },
    {
      id: "hh-1-q2", nodeId: "hh-1",
      textEn: "'Murabaha' is a common Islamic financing structure where:",
      textAr: "'المرابحة' هي هيكل تمويل إسلامي شائع حيث:",
      choices: [
        { id: "a", textEn: "The bank lends money at zero profit",                              textAr: "البنك يقرض المال بصفر ربح"                               },
        { id: "b", textEn: "The bank buys an asset and sells it at a disclosed markup, payable in instalments", textAr: "البنك يشتري الأصل ويبيعه بهامش ربح معلوم، يُسدَّد على أقساط" },
        { id: "c", textEn: "Interest is hidden within the profit margin",                     textAr: "الفائدة مخفية ضمن هامش الربح"                            },
        { id: "d", textEn: "Only used for personal loans under AED 50,000",                   textAr: "تُستخدم فقط للقروض الشخصية أقل من ٥٠٬٠٠٠ درهم"          },
      ],
      correctId: "b",
      explanationCorrectEn: "Murabaha: the bank buys the asset (e.g., car, property) then sells it to you at cost + a disclosed profit margin, payable in instalments. No hidden interest — the profit is pre-agreed.",
      explanationCorrectAr: "المرابحة: البنك يشتري الأصل (مثل سيارة أو عقار) ثم يبيعه لك بالتكلفة + هامش ربح معلوم، يُسدَّد على أقساط. لا فائدة مخفية — الربح متفق عليه مسبقاً.",
      explanationWrongEn: "Murabaha is transparency-based: the bank discloses its exact profit margin. This differs from conventional interest because the profit is fixed at sale, not accruing over time.",
      explanationWrongAr: "المرابحة قائمة على الشفافية: البنك يكشف عن هامش ربحه بالضبط. يختلف هذا عن الفائدة التقليدية لأن الربح ثابت عند البيع وليس متراكماً مع الوقت.",
    },
    {
      id: "hh-1-q3", nodeId: "hh-1",
      textEn: "'Sukuk' are best described as:",
      textAr: "'الصكوك' يُوصف بها بشكل أفضل بأنها:",
      choices: [
        { id: "a", textEn: "Conventional bonds issued by Muslim-majority governments",      textAr: "سندات تقليدية تُصدرها حكومات ذات أغلبية مسلمة"           },
        { id: "b", textEn: "Islamic certificates representing ownership in tangible assets", textAr: "شهادات إسلامية تمثّل ملكية في أصول ملموسة"                },
        { id: "c", textEn: "Savings accounts with guaranteed profit sharing",               textAr: "حسابات ادخار مع مشاركة أرباح مضمونة"                     },
        { id: "d", textEn: "A type of Islamic currency used in the GCC",                   textAr: "نوع من العملة الإسلامية المستخدمة في دول الخليج"           },
      ],
      correctId: "b",
      explanationCorrectEn: "Sukuk are Islamic bonds. Instead of paying interest, they give holders ownership of (or beneficial interest in) a real asset. Returns come from the asset's performance, not from interest.",
      explanationCorrectAr: "الصكوك سندات إسلامية. بدلاً من دفع الفائدة، تمنح الحاملين ملكية في (أو مصلحة مستفيدة من) أصل حقيقي. تأتي العوائد من أداء الأصل وليس من الفائدة.",
      explanationWrongEn: "Sukuk = Islamic bonds backed by real assets. Returns are rental income or profit from the underlying asset, not interest. The UAE and GCC are major sukuk issuers globally.",
      explanationWrongAr: "الصكوك = سندات إسلامية مدعومة بأصول حقيقية. العوائد دخل إيجاري أو ربح من الأصل الأساسي وليس فائدة. الإمارات ودول الخليج من أكبر مُصدِري الصكوك عالمياً.",
    },
  ],

  // ── Halal Harbour — hh-2: "Halal Investing" ──────────────────────────────────
  "hh-2": [
    {
      id: "hh-2-q1", nodeId: "hh-2",
      textEn: "Which sector would typically be EXCLUDED from a halal investment portfolio?",
      textAr: "أي قطاع سيُستبعد عادةً من محفظة استثمارية حلال؟",
      choices: [
        { id: "a", textEn: "Healthcare and pharmaceuticals",   textAr: "الرعاية الصحية والأدوية"  },
        { id: "b", textEn: "Renewable energy",                textAr: "الطاقة المتجددة"          },
        { id: "c", textEn: "Alcohol production and retail",   textAr: "إنتاج الكحول وبيعه بالتجزئة" },
        { id: "d", textEn: "Technology and software",         textAr: "التكنولوجيا والبرمجيات"   },
      ],
      correctId: "c",
      explanationCorrectEn: "Halal investing screens out: alcohol, tobacco, gambling, adult content, conventional banking (interest-based), and arms manufacturing. Healthcare, renewables, and tech are generally halal.",
      explanationCorrectAr: "الاستثمار الحلال يستبعد: الكحول والتبغ والقمار والمحتوى للبالغين والمصرفية التقليدية (القائمة على الفائدة) وتصنيع الأسلحة. الرعاية الصحية والطاقة المتجددة والتكنولوجيا حلال بشكل عام.",
      explanationWrongEn: "Haram sectors: alcohol, tobacco, gambling, adult entertainment, weapons, conventional banking. Many global companies pass halal screening — it's a growing investment universe.",
      explanationWrongAr: "القطاعات الحرام: الكحول والتبغ والقمار والترفيه للبالغين والأسلحة والمصرفية التقليدية. كثير من الشركات العالمية تجتاز الفحص الحلال — إنه كون استثماري متنامٍ.",
    },
    {
      id: "hh-2-q2", nodeId: "hh-2",
      textEn: "'Musharakah' in Islamic finance refers to:",
      textAr: "'المشاركة' في التمويل الإسلامي تشير إلى:",
      choices: [
        { id: "a", textEn: "A loan with a fixed repayment schedule",              textAr: "قرض بجدول سداد ثابت"                              },
        { id: "b", textEn: "A joint venture where profit AND loss are shared",    textAr: "مشروع مشترك تتقاسم فيه الأرباح والخسائر"         },
        { id: "c", textEn: "A type of Islamic insurance for businesses",          textAr: "نوع من التأمين الإسلامي للشركات"                  },
        { id: "d", textEn: "A currency exchange service with no markup",          textAr: "خدمة صرف عملات بدون هامش ربح"                   },
      ],
      correctId: "b",
      explanationCorrectEn: "Musharakah = partnership. All parties contribute capital and share profit AND loss proportionally. Risk is shared — not just reward — making it more equitable than interest-based lending.",
      explanationCorrectAr: "المشاركة = شراكة. جميع الأطراف يساهمون برأس المال ويتقاسمون الأرباح والخسائر بشكل متناسب. المخاطرة مشتركة — وليس المكافأة فقط — مما يجعلها أكثر عدالة من الإقراض القائم على الفائدة.",
      explanationWrongEn: "Musharakah = profit-AND-loss sharing partnership. All partners bear risk proportionally. This aligns Islamic finance with real economic outcomes rather than guaranteed returns.",
      explanationWrongAr: "المشاركة = شراكة مشاركة في الأرباح والخسائر. جميع الشركاء يتحملون المخاطرة بشكل متناسب. هذا يوائم التمويل الإسلامي مع النتائج الاقتصادية الحقيقية بدلاً من العوائد المضمونة.",
    },
    {
      id: "hh-2-q3", nodeId: "hh-2",
      textEn: "'Takaful' is the Islamic equivalent of:",
      textAr: "'التكافل' هو ما يعادل إسلامياً:",
      choices: [
        { id: "a", textEn: "A savings account",     textAr: "حساب الادخار"    },
        { id: "b", textEn: "A stock exchange",      textAr: "سوق الأوراق المالية" },
        { id: "c", textEn: "Insurance",             textAr: "التأمين"          },
        { id: "d", textEn: "A retirement fund",     textAr: "صندوق التقاعد"    },
      ],
      correctId: "c",
      explanationCorrectEn: "Takaful = mutual guarantee. Members pool contributions to cover each other's losses. Unlike conventional insurance (which involves interest and uncertainty), takaful is based on mutual contribution and donation.",
      explanationCorrectAr: "التكافل = الضمان المتبادل. الأعضاء يجمعون المساهمات لتغطية خسائر بعضهم البعض. خلافاً للتأمين التقليدي (الذي ينطوي على فائدة وغرر)، التكافل قائم على المساهمة والتبرع المتبادل.",
      explanationWrongEn: "Takaful is the halal alternative to conventional insurance. It operates on shared responsibility — members collectively protect each other rather than paying a company for profit-based coverage.",
      explanationWrongAr: "التكافل هو البديل الحلال للتأمين التقليدي. يعمل على المسؤولية المشتركة — الأعضاء يحمون بعضهم البعض بشكل جماعي بدلاً من الدفع لشركة مقابل تغطية قائمة على الربح.",
    },
  ],

  // ── Halal Harbour — hh-5: "Halal Finance Boss" (boss) ────────────────────────
  "hh-5": [
    {
      id: "hh-5-q1", nodeId: "hh-5",
      textEn: "Islamic banking assets in the UAE represent approximately what share of total banking assets?",
      textAr: "أصول المصرفية الإسلامية في الإمارات تمثّل تقريباً ما يلي من إجمالي أصول القطاع المصرفي:",
      choices: [
        { id: "a", textEn: "Less than 5%",   textAr: "أقل من ٥٪"  },
        { id: "b", textEn: "About 10–15%",   textAr: "حوالي ١٠–١٥٪" },
        { id: "c", textEn: "Around 25–35%",  textAr: "حوالي ٢٥–٣٥٪" },
        { id: "d", textEn: "Over 70%",       textAr: "أكثر من ٧٠٪"  },
      ],
      correctId: "c",
      explanationCorrectEn: "Islamic banking in the UAE represents ~25–35% of total banking assets, making it one of the world's top Islamic finance hubs alongside Malaysia and Saudi Arabia.",
      explanationCorrectAr: "المصرفية الإسلامية في الإمارات تمثّل ~٢٥–٣٥٪ من إجمالي أصول القطاع المصرفي، مما يجعلها من أكبر مراكز التمويل الإسلامي في العالم إلى جانب ماليزيا والمملكة العربية السعودية.",
      explanationWrongEn: "UAE Islamic banks hold ~25–35% of total banking assets. The UAE is a leading global hub for Islamic finance, sukuk issuance, and halal investment products.",
      explanationWrongAr: "تمتلك البنوك الإسلامية الإماراتية ~٢٥–٣٥٪ من إجمالي أصول القطاع المصرفي. الإمارات مركز عالمي رائد للتمويل الإسلامي وإصدار الصكوك والمنتجات الاستثمارية الحلال.",
    },
    {
      id: "hh-5-q2", nodeId: "hh-5",
      textEn: "'Ijarah' is an Islamic finance contract used for:",
      textAr: "'الإجارة' عقد تمويل إسلامي يُستخدم لـ:",
      choices: [
        { id: "a", textEn: "Trade financing for import/export",                  textAr: "تمويل التجارة للاستيراد/التصدير"              },
        { id: "b", textEn: "Leasing an asset while the bank retains ownership",  textAr: "تأجير أصل بينما يحتفظ البنك بالملكية"         },
        { id: "c", textEn: "Charitable giving (zakat) management",               textAr: "إدارة التبرعات الخيرية (الزكاة)"              },
        { id: "d", textEn: "Currency exchange at market rate",                   textAr: "صرف العملات بسعر السوق"                      },
      ],
      correctId: "b",
      explanationCorrectEn: "Ijarah = Islamic lease. The bank buys the asset (car, property) and leases it to you. You pay rental instalments. At the end, you may have the option to purchase — similar to conventional leasing but structured to avoid riba.",
      explanationCorrectAr: "الإجارة = إيجار إسلامي. البنك يشتري الأصل (سيارة أو عقار) ويؤجّره لك. تدفع أقساط الإيجار. في النهاية، قد يكون لديك خيار الشراء — مشابه للتأجير التقليدي لكن مهيكل لتجنب الربا.",
      explanationWrongEn: "Ijarah is a lease contract: bank owns, you use and pay rent. You don't pay interest — you pay for the use of the asset. Common for cars and home financing in Islamic banks.",
      explanationWrongAr: "الإجارة عقد إيجار: البنك يمتلك، أنت تستخدم وتدفع إيجاراً. لا تدفع فائدة — تدفع مقابل استخدام الأصل. شائع لتمويل السيارات والمنازل في البنوك الإسلامية.",
    },
    {
      id: "hh-5-q3", nodeId: "hh-5",
      textEn: "Which statement about Islamic finance is TRUE?",
      textAr: "أي عبارة عن التمويل الإسلامي صحيحة؟",
      choices: [
        { id: "a", textEn: "It is always slower and more expensive than conventional banking",  textAr: "إنه دائماً أبطأ وأغلى من المصرفية التقليدية"              },
        { id: "b", textEn: "Only Muslims can open Islamic bank accounts in the UAE",           textAr: "فقط المسلمون يمكنهم فتح حسابات بنكية إسلامية في الإمارات" },
        { id: "c", textEn: "Islamic finance products can be used by non-Muslims",              textAr: "منتجات التمويل الإسلامي يمكن لغير المسلمين استخدامها"      },
        { id: "d", textEn: "Islamic finance does not allow any form of profit",                textAr: "التمويل الإسلامي لا يسمح بأي شكل من أشكال الربح"           },
      ],
      correctId: "c",
      explanationCorrectEn: "Islamic finance is open to everyone. Many non-Muslim customers choose Islamic banking for ethical reasons, competitive products, or simply because the products work well for them.",
      explanationCorrectAr: "التمويل الإسلامي مفتوح للجميع. كثير من العملاء غير المسلمين يختارون المصرفية الإسلامية لأسباب أخلاقية أو منتجات تنافسية أو ببساطة لأن المنتجات تناسبهم.",
      explanationWrongEn: "Islamic banks welcome all customers regardless of religion. Products must be shariah-compliant — but the customer doesn't need to be Muslim to benefit.",
      explanationWrongAr: "البنوك الإسلامية ترحّب بجميع العملاء بغض النظر عن الدين. يجب أن تكون المنتجات متوافقة مع الشريعة — لكن العميل لا يحتاج إلى أن يكون مسلماً للاستفادة.",
    },
  ],

  // ── Gratuity Garden — gg-1: "What Is Gratuity?" ──────────────────────────────
  "gg-1": [
    {
      id: "gg-1-q1", nodeId: "gg-1",
      textEn: "Under UAE Labour Law, end-of-service gratuity is paid to:",
      textAr: "بموجب قانون العمل الإماراتي، تُدفع مكافأة نهاية الخدمة لـ:",
      choices: [
        { id: "a", textEn: "UAE nationals only",                                  textAr: "المواطنين الإماراتيين فقط"                          },
        { id: "b", textEn: "All employees who complete at least one year of service", textAr: "جميع الموظفين الذين أتمّوا سنة خدمة على الأقل" },
        { id: "c", textEn: "Only employees who are terminated (not those who resign)", textAr: "الموظفين الذين يُفصَلون فقط (وليس من يستقيلون)"    },
        { id: "d", textEn: "Employees earning above AED 10,000/month only",      textAr: "الموظفون الذين يكسبون فوق ١٠٬٠٠٠ درهم شهرياً فقط"  },
      ],
      correctId: "b",
      explanationCorrectEn: "Under the 2022 UAE Labour Law, any employee (regardless of nationality or salary) who completes 1+ year is entitled to gratuity. The old resignation penalty was removed.",
      explanationCorrectAr: "بموجب قانون العمل الإماراتي لعام ٢٠٢٢، أي موظف (بغض النظر عن الجنسية أو الراتب) يُتمّ سنة أو أكثر يستحق مكافأة نهاية الخدمة. تم إلغاء عقوبة الاستقالة القديمة.",
      explanationWrongEn: "UAE Labour Law 2022: all employees with 1+ year service get gratuity — whether they resign or are terminated. The old 1/3 reduction for early resignation was removed.",
      explanationWrongAr: "قانون العمل الإماراتي ٢٠٢٢: جميع الموظفين الذين خدموا سنة أو أكثر يحصلون على مكافأة — سواء استقالوا أو أُنهيت خدمتهم. تم إلغاء التخفيض القديم البالغ ثلث المبلغ عند الاستقالة المبكرة.",
    },
    {
      id: "gg-1-q2", nodeId: "gg-1",
      textEn: "UAE end-of-service gratuity is calculated based on:",
      textAr: "تُحسب مكافأة نهاية الخدمة الإماراتية على أساس:",
      choices: [
        { id: "a", textEn: "Your total salary including all allowances and bonuses", textAr: "إجمالي راتبك شاملاً جميع البدلات والمكافآت" },
        { id: "b", textEn: "Your basic salary only",                                 textAr: "راتبك الأساسي فقط"                          },
        { id: "c", textEn: "Your gross salary including housing allowance",          textAr: "راتبك الإجمالي شاملاً بدل السكن"            },
        { id: "d", textEn: "A government-set flat daily rate",                       textAr: "معدل يومي ثابت محدد حكومياً"               },
      ],
      correctId: "b",
      explanationCorrectEn: "Gratuity = based on basic salary. Transport, housing, and other allowances are NOT included. Always check your employment contract to identify your exact basic salary component.",
      explanationCorrectAr: "المكافأة تُحسب على أساس الراتب الأساسي. بدلات النقل والسكن وغيرها غير مشمولة. تحقق دائماً من عقد عملك لمعرفة مكوّن راتبك الأساسي بالضبط.",
      explanationWrongEn: "Gratuity is on basic salary ONLY. If your total package is AED 15,000 but basic is AED 8,000, gratuity is calculated on AED 8,000. Check your contract.",
      explanationWrongAr: "المكافأة على الراتب الأساسي فقط. إذا كانت حزمتك الإجمالية ١٥٬٠٠٠ درهم لكن الأساسي ٨٬٠٠٠ درهم، تُحسب المكافأة على ٨٬٠٠٠ درهم. تحقق من عقدك.",
    },
    {
      id: "gg-1-q3", nodeId: "gg-1",
      textEn: "For the first 5 years of service, an employee earns gratuity of:",
      textAr: "للسنوات الخمس الأولى من الخدمة، يكسب الموظف مكافأة:",
      choices: [
        { id: "a", textEn: "30 days of basic salary per year",  textAr: "٣٠ يوماً من الراتب الأساسي سنوياً" },
        { id: "b", textEn: "21 days of basic salary per year",  textAr: "٢١ يوماً من الراتب الأساسي سنوياً" },
        { id: "c", textEn: "14 days of basic salary per year",  textAr: "١٤ يوماً من الراتب الأساسي سنوياً" },
        { id: "d", textEn: "7 days of basic salary per year",   textAr: "٧ أيام من الراتب الأساسي سنوياً"   },
      ],
      correctId: "b",
      explanationCorrectEn: "Years 1–5: 21 calendar days' basic salary per year. After 5 years: 30 days per year. Daily rate = basic monthly salary ÷ 30.",
      explanationCorrectAr: "السنوات ١–٥: ٢١ يوماً تقويمياً من الراتب الأساسي سنوياً. بعد ٥ سنوات: ٣٠ يوماً سنوياً. المعدل اليومي = الراتب الأساسي الشهري ÷ ٣٠.",
      explanationWrongEn: "First 5 years = 21 days/year. Beyond 5 years = 30 days/year. Daily rate = basic salary ÷ 30. Simple formula, significant money — worth calculating.",
      explanationWrongAr: "أول ٥ سنوات = ٢١ يوم/سنة. ما فوق ٥ سنوات = ٣٠ يوم/سنة. المعدل اليومي = الراتب الأساسي ÷ ٣٠. صيغة بسيطة ومال كبير — يستحق الحساب.",
    },
  ],

  // ── Gratuity Garden — gg-2: "Calculating Gratuity" ───────────────────────────
  "gg-2": [
    {
      id: "gg-2-q1", nodeId: "gg-2",
      textEn: "Fatima has a basic salary of AED 9,000/month. Her daily gratuity rate is approximately:",
      textAr: "لدى فاطمة راتب أساسي ٩٬٠٠٠ درهم شهرياً. معدلها اليومي للمكافأة تقريباً:",
      choices: [
        { id: "a", textEn: "AED 150/day", textAr: "١٥٠ درهم/يوم" },
        { id: "b", textEn: "AED 300/day", textAr: "٣٠٠ درهم/يوم" },
        { id: "c", textEn: "AED 450/day", textAr: "٤٥٠ درهم/يوم" },
        { id: "d", textEn: "AED 600/day", textAr: "٦٠٠ درهم/يوم" },
      ],
      correctId: "b",
      explanationCorrectEn: "Daily rate = basic salary ÷ 30 = AED 9,000 ÷ 30 = AED 300/day. This is the building block of the entire gratuity calculation.",
      explanationCorrectAr: "المعدل اليومي = الراتب الأساسي ÷ ٣٠ = ٩٬٠٠٠ ÷ ٣٠ = ٣٠٠ درهم/يوم. هذا هو اللبنة الأساسية لحساب المكافأة كاملاً.",
      explanationWrongEn: "Daily rate = 9,000 ÷ 30 = AED 300/day. Multiply by 21 (first 5 years) or 30 (beyond 5 years) per year of service.",
      explanationWrongAr: "المعدل اليومي = ٩٬٠٠٠ ÷ ٣٠ = ٣٠٠ درهم/يوم. اضرب في ٢١ (أول ٥ سنوات) أو ٣٠ (ما فوق ٥ سنوات) لكل سنة خدمة.",
    },
    {
      id: "gg-2-q2", nodeId: "gg-2",
      textEn: "Using 21 days/year, what is Fatima's gratuity after 4 complete years of service?",
      textAr: "باستخدام ٢١ يوماً/سنة، ما مكافأة فاطمة بعد ٤ سنوات خدمة كاملة؟",
      choices: [
        { id: "a", textEn: "AED 18,000", textAr: "١٨٬٠٠٠ درهم" },
        { id: "b", textEn: "AED 25,200", textAr: "٢٥٬٢٠٠ درهم" },
        { id: "c", textEn: "AED 36,000", textAr: "٣٦٬٠٠٠ درهم" },
        { id: "d", textEn: "AED 12,600", textAr: "١٢٬٦٠٠ درهم" },
      ],
      correctId: "b",
      explanationCorrectEn: "AED 300/day × 21 days × 4 years = AED 25,200. A significant amount that often surprises employees who never track it.",
      explanationCorrectAr: "٣٠٠ درهم/يوم × ٢١ يوماً × ٤ سنوات = ٢٥٬٢٠٠ درهم. مبلغ كبير كثيراً ما يفاجئ الموظفين الذين لم يتتبعوه.",
      explanationWrongEn: "300 × 21 × 4 = 25,200. Always know your running gratuity total — it's part of your total compensation.",
      explanationWrongAr: "٣٠٠ × ٢١ × ٤ = ٢٥٬٢٠٠. اعرف دائماً إجمالي مكافأتك المتراكمة — إنها جزء من إجمالي تعويضك.",
    },
    {
      id: "gg-2-q3", nodeId: "gg-2",
      textEn: "Ali has worked 7 years. Basic salary AED 12,000/month (daily rate AED 400). Total gratuity:",
      textAr: "عمل علي ٧ سنوات. الراتب الأساسي ١٢٬٠٠٠ درهم/شهر (معدل يومي ٤٠٠ درهم). إجمالي المكافأة:",
      choices: [
        { id: "a", textEn: "AED 42,000", textAr: "٤٢٬٠٠٠ درهم" },
        { id: "b", textEn: "AED 58,000", textAr: "٥٨٬٠٠٠ درهم" },
        { id: "c", textEn: "AED 66,000", textAr: "٦٦٬٠٠٠ درهم" },
        { id: "d", textEn: "AED 84,000", textAr: "٨٤٬٠٠٠ درهم" },
      ],
      correctId: "c",
      explanationCorrectEn: "First 5 years: 400 × 21 × 5 = AED 42,000. Next 2 years (beyond 5): 400 × 30 × 2 = AED 24,000. Total: AED 66,000.",
      explanationCorrectAr: "أول ٥ سنوات: ٤٠٠ × ٢١ × ٥ = ٤٢٬٠٠٠ درهم. السنتان التاليتان (ما فوق ٥): ٤٠٠ × ٣٠ × ٢ = ٢٤٬٠٠٠ درهم. الإجمالي: ٦٦٬٠٠٠ درهم.",
      explanationWrongEn: "Years 1–5: 400 × 21 × 5 = 42,000. Years 6–7: 400 × 30 × 2 = 24,000. Total = 66,000. Note the higher rate kicks in after year 5.",
      explanationWrongAr: "السنوات ١–٥: ٤٠٠ × ٢١ × ٥ = ٤٢٬٠٠٠. السنوات ٦–٧: ٤٠٠ × ٣٠ × ٢ = ٢٤٬٠٠٠. الإجمالي = ٦٦٬٠٠٠. لاحظ أن المعدل الأعلى يبدأ بعد السنة الخامسة.",
    },
  ],

  // ── Gratuity Garden — gg-5: "Benefits Boss" (boss) ───────────────────────────
  "gg-5": [
    {
      id: "gg-5-q1", nodeId: "gg-5",
      textEn: "Under the 2022 UAE Labour Law, if you resign after 2 years of service, your gratuity entitlement is:",
      textAr: "بموجب قانون العمل الإماراتي ٢٠٢٢، إذا استقلت بعد سنتين من الخدمة، استحقاقك للمكافأة:",
      choices: [
        { id: "a", textEn: "Nothing — you forfeit gratuity when you resign",    textAr: "لا شيء — تتنازل عن المكافأة عند الاستقالة"           },
        { id: "b", textEn: "One-third of the full gratuity amount",             textAr: "ثلث مبلغ المكافأة الكامل"                            },
        { id: "c", textEn: "Full gratuity — the resignation penalty was removed", textAr: "المكافأة الكاملة — تم إلغاء عقوبة الاستقالة"       },
        { id: "d", textEn: "Double gratuity as a loyalty bonus",                textAr: "ضعف المكافأة كمكافأة ولاء"                           },
      ],
      correctId: "c",
      explanationCorrectEn: "The 2022 UAE Labour Law abolished the old resignation penalty. Employees who complete 1+ year now receive full gratuity whether they resign or are terminated.",
      explanationCorrectAr: "أبطل قانون العمل الإماراتي ٢٠٢٢ عقوبة الاستقالة القديمة. الموظفون الذين يُتمّون سنة أو أكثر يتلقون الآن المكافأة الكاملة سواء استقالوا أو أُنهيت خدمتهم.",
      explanationWrongEn: "New law (2022): full gratuity for all employees with 1+ year, regardless of how they leave. The old 1/3 rule for early resigners was removed entirely.",
      explanationWrongAr: "القانون الجديد (٢٠٢٢): مكافأة كاملة لجميع الموظفين الذين خدموا سنة أو أكثر، بغض النظر عن طريقة مغادرتهم. تم إلغاء قاعدة الثلث القديمة للمستقيلين مبكراً كلياً.",
    },
    {
      id: "gg-5-q2", nodeId: "gg-5",
      textEn: "The DEWS (Workplace Savings) scheme in the UAE was designed to:",
      textAr: "نظام ادخار مكان العمل (DEWS) في الإمارات صُمِّم لـ:",
      choices: [
        { id: "a", textEn: "Replace end-of-service gratuity with a funded savings plan",  textAr: "استبدال مكافأة نهاية الخدمة بخطة ادخار ممولة"    },
        { id: "b", textEn: "Provide free government pensions to all expatriates",          textAr: "توفير معاشات حكومية مجانية لجميع الأجانب"         },
        { id: "c", textEn: "Create mandatory investment accounts for UAE nationals only",  textAr: "إنشاء حسابات استثمارية إلزامية للمواطنين فقط"     },
        { id: "d", textEn: "Fund employer health insurance contributions",                 textAr: "تمويل مساهمات تأمين صحي صاحب العمل"               },
      ],
      correctId: "a",
      explanationCorrectEn: "DEWS is a government-backed alternative to gratuity in DIFC (and other free zones). Instead of a lump sum at the end, the employer contributes monthly to a portable savings account. Better for employees who change jobs.",
      explanationCorrectAr: "DEWS بديل حكومي للمكافأة في مركز دبي المالي العالمي (ومناطق حرة أخرى). بدلاً من مبلغ مقطوع في النهاية، يساهم صاحب العمل شهرياً في حساب ادخار قابل للنقل. أفضل للموظفين الذين يغيّرون وظائفهم.",
      explanationWrongEn: "DEWS = monthly contributions to a portable savings account instead of accumulating a lump-sum liability. It protects employees if the employer goes bankrupt and allows portability between jobs.",
      explanationWrongAr: "DEWS = مساهمات شهرية في حساب ادخار قابل للنقل بدلاً من تراكم التزام مبلغ مقطوع. يحمي الموظفين إذا أفلس صاحب العمل ويتيح إمكانية النقل بين الوظائف.",
    },
    {
      id: "gg-5-q3", nodeId: "gg-5",
      textEn: "The smartest way to treat your gratuity entitlement while employed is:",
      textAr: "الطريقة الأذكى للتعامل مع استحقاقك للمكافأة أثناء العمل:",
      choices: [
        { id: "a", textEn: "Ignore it — it's paid only when you leave",                  textAr: "تجاهلها — تُدفع فقط عند المغادرة"                     },
        { id: "b", textEn: "Track it annually and factor it into your total compensation", textAr: "تتبعها سنوياً وتضمينها في إجمالي تعويضاتك"            },
        { id: "c", textEn: "Spend it immediately when received",                          textAr: "إنفاقها فوراً عند استلامها"                           },
        { id: "d", textEn: "Request it monthly as part of your salary",                  textAr: "طلبها شهرياً كجزء من راتبك"                          },
      ],
      correctId: "b",
      explanationCorrectEn: "Know your running total. It's part of your total compensation — useful when comparing job offers, planning career moves, or negotiating salary. Many employees leave significant money behind by not understanding this.",
      explanationCorrectAr: "اعرف إجمالك المتراكم. إنه جزء من إجمالي تعويضاتك — مفيد عند مقارنة عروض العمل أو التخطيط للتحركات المهنية أو التفاوض على الراتب. كثير من الموظفين يتركون أموالاً كبيرة وراءهم لعدم فهم هذا.",
      explanationWrongEn: "Treat gratuity as deferred compensation — part of what you're earning each month. Track it, factor it into job comparisons, and plan how you'll use it when you eventually receive it.",
      explanationWrongAr: "تعامل مع المكافأة كتعويض مؤجّل — جزء مما تكسبه كل شهر. تتبعها وضمّنها في مقارنات الوظائف وخطّط كيف ستستخدمها عند استلامها في نهاية المطاف.",
    },
  ],
};
