import type { QuizQuestion } from "./quiz-types";

export const QUESTIONS_W12_W13: Record<string, QuizQuestion[]> = {

  // ── Family Majlis — fm-1: "Joint Finances" ────────────────────────────────────
  "fm-1": [
    {
      id: "fm-1-q1", nodeId: "fm-1",
      textEn: "The main advantage of a joint account for a couple is:",
      textAr: "الميزة الرئيسية للحساب المشترك للزوجين هي:",
      choices: [
        { id: "a", textEn: "It always earns a higher interest rate",                       textAr: "يكسب دائماً معدل فائدة أعلى"                          },
        { id: "b", textEn: "Transparency and easier management of shared household expenses", textAr: "الشفافية وسهولة إدارة مصروفات المنزل المشتركة"         },
        { id: "c", textEn: "Neither partner can spend without the other's approval",        textAr: "لا يمكن لأي شريك الإنفاق دون موافقة الآخر"            },
        { id: "d", textEn: "One person's credit score automatically improves the other's",  textAr: "درجة ائتمان شخص واحد تحسّن تلقائياً درجة الآخر"      },
      ],
      correctId: "b",
      explanationCorrectEn: "A joint account for shared expenses makes household bills, rent, and groceries transparent and easy to split. Both partners can see what's coming in and going out.",
      explanationCorrectAr: "الحساب المشترك للمصروفات المشتركة يجعل فواتير المنزل والإيجار والبقالة شفافة وسهلة التقسيم. يمكن لكلا الشريكين رؤية ما يدخل ويخرج.",
      explanationWrongEn: "Joint accounts provide transparency and shared responsibility for household expenses. Most couples also maintain individual accounts for personal spending — the 'joint + personal' model works well.",
      explanationWrongAr: "الحسابات المشتركة توفّر الشفافية والمسؤولية المشتركة لمصروفات المنزل. معظم الأزواج يحتفظون أيضاً بحسابات فردية للإنفاق الشخصي — نموذج 'المشترك + الشخصي' يعمل بشكل جيد.",
    },
    {
      id: "fm-1-q2", nodeId: "fm-1",
      textEn: "A 'beneficiary' on a financial account is:",
      textAr: "'المستفيد' في الحساب المالي هو:",
      choices: [
        { id: "a", textEn: "Someone who profits from your investment decisions",     textAr: "شخص يستفيد من قراراتك الاستثمارية"              },
        { id: "b", textEn: "The person designated to receive the account balance upon your death", textAr: "الشخص المُعيَّن لاستلام رصيد الحساب عند وفاتك" },
        { id: "c", textEn: "A financial advisor managing your accounts",            textAr: "مستشار مالي يدير حساباتك"                        },
        { id: "d", textEn: "An alternate account holder with full spending authority", textAr: "حامل حساب بديل بصلاحية إنفاق كاملة"             },
      ],
      correctId: "b",
      explanationCorrectEn: "Designating a beneficiary ensures your savings go to the right person without going through a lengthy legal process. Every account should have an up-to-date beneficiary.",
      explanationCorrectAr: "تعيين مستفيد يضمن ذهاب مدخراتك إلى الشخص المناسب دون المرور بإجراء قانوني طويل. يجب أن يكون لكل حساب مستفيد محدَّث.",
      explanationWrongEn: "Beneficiary = the person who inherits the account. Without a named beneficiary, assets may be frozen or go through probate — which in UAE can be complex for expatriates.",
      explanationWrongAr: "المستفيد = الشخص الذي يرث الحساب. بدون مستفيد مُعيَّن، قد تُجمَّد الأصول أو تمر بإجراءات الوصاية — وهو ما قد يكون معقداً في الإمارات للأجانب.",
    },
    {
      id: "fm-1-q3", nodeId: "fm-1",
      textEn: "'Financial infidelity' in a relationship means:",
      textAr: "'الخيانة المالية' في العلاقة تعني:",
      choices: [
        { id: "a", textEn: "Cheating on investment returns",                           textAr: "الغش في عوائد الاستثمار"                          },
        { id: "b", textEn: "Hiding financial decisions, debts, or spending from a partner", textAr: "إخفاء القرارات المالية أو الديون أو الإنفاق عن الشريك" },
        { id: "c", textEn: "Having savings accounts in multiple banks",               textAr: "امتلاك حسابات ادخار في بنوك متعددة"                },
        { id: "d", textEn: "Investing in assets your partner doesn't understand",     textAr: "الاستثمار في أصول لا يفهمها شريكك"               },
      ],
      correctId: "b",
      explanationCorrectEn: "Financial infidelity — hiding secret accounts, debt, or spending — is one of the leading causes of relationship breakdowns. Financial transparency builds trust.",
      explanationCorrectAr: "الخيانة المالية — إخفاء حسابات سرية أو ديون أو إنفاق — من الأسباب الرئيسية لانهيار العلاقات. الشفافية المالية تبني الثقة.",
      explanationWrongEn: "Financial infidelity = hiding money matters from a partner. It's not about multiple banks or complex investments — it's about secret decisions that affect the household.",
      explanationWrongAr: "الخيانة المالية = إخفاء الأمور المالية عن الشريك. ليست عن بنوك متعددة أو استثمارات معقدة — إنها عن قرارات سرية تؤثر على المنزل.",
    },
  ],

  // ── Family Majlis — fm-2: "Family Budgeting" ─────────────────────────────────
  "fm-2": [
    {
      id: "fm-2-q1", nodeId: "fm-2",
      textEn: "When building a family budget with two incomes, a conservative approach is to:",
      textAr: "عند بناء ميزانية أسرية بدخلين، النهج المحافظ هو:",
      choices: [
        { id: "a", textEn: "Budget based on only one income and treat the second as surplus",  textAr: "الميزنة على دخل واحد فقط وتعامل الثاني كفائض"         },
        { id: "b", textEn: "Always spend up to the combined income total",                    textAr: "الإنفاق دائماً حتى الدخل المجمّع الكامل"             },
        { id: "c", textEn: "Let only the higher earner manage all finances",                  textAr: "السماح للكاسب الأعلى فقط بإدارة جميع الماليات"       },
        { id: "d", textEn: "Keep finances completely separate and never discuss money",       textAr: "إبقاء الماليات منفصلة تماماً وعدم مناقشة المال أبداً" },
      ],
      correctId: "a",
      explanationCorrectEn: "Budget on one income; save the second. If one partner loses their job, your lifestyle is already built around one income. The second becomes an accelerated savings or investment fund.",
      explanationCorrectAr: "ابنِ الميزانية على دخل واحد؛ وفِّر الثاني. إذا فقد أحد الشريكين وظيفته، أسلوب حياتك مبني بالفعل على دخل واحد. الثاني يصبح صندوق ادخار أو استثمار متسارع.",
      explanationWrongEn: "Building a lifestyle on both incomes means job loss halves your budget. Build on one, invest the other. This one decision transforms financial security dramatically.",
      explanationWrongAr: "بناء أسلوب حياة على كلا الدخلين يعني أن فقدان الوظيفة يُنصّف ميزانيتك. ابنِ على واحد واستثمر الآخر. هذا القرار الواحد يحوّل الأمن المالي بشكل درامي.",
    },
    {
      id: "fm-2-q2", nodeId: "fm-2",
      textEn: "Hassan and Layla earn AED 25,000 combined. They save AED 4,000/month. What percentage of income do they save?",
      textAr: "يكسب حسن وليلى ٢٥٬٠٠٠ درهم مجتمعَين. يدّخران ٤٬٠٠٠ درهم شهرياً. ما نسبة الادخار من الدخل؟",
      choices: [
        { id: "a", textEn: "12%", textAr: "١٢٪" },
        { id: "b", textEn: "16%", textAr: "١٦٪" },
        { id: "c", textEn: "20%", textAr: "٢٠٪" },
        { id: "d", textEn: "25%", textAr: "٢٥٪" },
      ],
      correctId: "b",
      explanationCorrectEn: "AED 4,000 ÷ AED 25,000 = 16%. This is above the 10% baseline recommended for most households — they're doing well. Targeting 20% would be excellent.",
      explanationCorrectAr: "٤٬٠٠٠ ÷ ٢٥٬٠٠٠ = ١٦٪. هذا أعلى من الحد الأدنى الموصى به ١٠٪ لمعظم الأسر — يسيران بشكل جيد. استهداف ٢٠٪ سيكون ممتازاً.",
      explanationWrongEn: "4,000 ÷ 25,000 = 0.16 = 16%. Healthy savings rate. The general target is 20% for long-term financial security.",
      explanationWrongAr: "٤٬٠٠٠ ÷ ٢٥٬٠٠٠ = ٠.١٦ = ١٦٪. معدل ادخار صحي. الهدف العام ٢٠٪ للأمن المالي طويل الأجل.",
    },
    {
      id: "fm-2-q3", nodeId: "fm-2",
      textEn: "Irregular household expenses (car insurance, school fees, Eid gifts) should be handled by:",
      textAr: "المصروفات المنزلية غير المنتظمة (تأمين السيارة ورسوم المدرسة وهدايا العيد) يجب إدارتها عبر:",
      choices: [
        { id: "a", textEn: "Ignoring them since they don't happen every month",          textAr: "تجاهلها لأنها لا تحدث كل شهر"                      },
        { id: "b", textEn: "Dividing the annual cost by 12 and saving monthly (sinking fund)", textAr: "قسمة التكلفة السنوية على ١٢ والادخار شهرياً (صندوق تراكم)" },
        { id: "c", textEn: "Funding them only from annual bonuses",                      textAr: "تمويلها من المكافآت السنوية فقط"                     },
        { id: "d", textEn: "Putting them on credit card and paying over time",           textAr: "وضعها على بطاقة ائتمان والسداد على مدى الوقت"       },
      ],
      correctId: "b",
      explanationCorrectEn: "Sinking funds prevent 'bill shock'. If school fees are AED 24,000/year, save AED 2,000/month. When the bill arrives, it's already funded — no credit card needed.",
      explanationCorrectAr: "صناديق التراكم تمنع 'صدمة الفاتورة'. إذا كانت رسوم المدرسة ٢٤٬٠٠٠ درهم/سنة، ادّخر ٢٬٠٠٠ درهم/شهر. عند وصول الفاتورة، تكون مموّلة بالفعل — لا حاجة لبطاقة ائتمان.",
      explanationWrongEn: "Sinking funds = divide annual cost by 12, save monthly. When the big bill arrives, the money is ready. No scrambling, no credit card debt.",
      explanationWrongAr: "صناديق التراكم = قسّم التكلفة السنوية على ١٢، ادّخر شهرياً. عند وصول الفاتورة الكبيرة، المال جاهز. لا تخبط وبحث ولا ديون بطاقات ائتمان.",
    },
  ],

  // ── Family Majlis — fm-5: "Family Finance Boss" (boss) ───────────────────────
  "fm-5": [
    {
      id: "fm-5-q1", nodeId: "fm-5",
      textEn: "Which financial document is MOST important for a family to have in place?",
      textAr: "أي وثيقة مالية الأهم بالنسبة للأسرة أن تمتلكها؟",
      choices: [
        { id: "a", textEn: "A premium rewards credit card",                           textAr: "بطاقة ائتمان مكافآت متميزة"                         },
        { id: "b", textEn: "A stock trading account",                                 textAr: "حساب تداول أسهم"                                   },
        { id: "c", textEn: "A will, up-to-date beneficiary designations, and insurance", textAr: "وصية ومستفيدون محدَّثون وتأمين"                 },
        { id: "d", textEn: "A BNPL account for major purchases",                      textAr: "حساب اشترِ الآن وادفع لاحقاً للمشتريات الكبيرة"    },
      ],
      correctId: "c",
      explanationCorrectEn: "A will ensures your wishes are followed. Beneficiary designations ensure assets pass directly. Insurance protects income. Without these, a family can be left in financial chaos after a loss.",
      explanationCorrectAr: "الوصية تضمن اتباع رغباتك. تعيينات المستفيدين تضمن انتقال الأصول مباشرةً. التأمين يحمي الدخل. بدون هذه الأمور، يمكن أن تُترك الأسرة في فوضى مالية بعد الخسارة.",
      explanationWrongEn: "For families: wills + beneficiaries + insurance are the foundation. Trading accounts and rewards cards are optional extras — protection comes first.",
      explanationWrongAr: "للأسر: الوصايا + المستفيدون + التأمين هي الأساس. حسابات التداول وبطاقات المكافآت إضافات اختيارية — الحماية تأتي أولاً.",
    },
    {
      id: "fm-5-q2", nodeId: "fm-5",
      textEn: "A family emergency fund should ideally cover:",
      textAr: "يجب أن يغطي صندوق الطوارئ العائلي في المثالية:",
      choices: [
        { id: "a", textEn: "Only the primary earner's monthly salary",          textAr: "راتب المعيل الرئيسي الشهري فقط"             },
        { id: "b", textEn: "The full household monthly expenses for 3–6 months", textAr: "المصروفات الشهرية الكاملة للمنزل لمدة ٣–٦ أشهر" },
        { id: "c", textEn: "School fees only for one academic year",             textAr: "رسوم المدرسة فقط لعام دراسي واحد"           },
        { id: "d", textEn: "Two months of rent only",                           textAr: "شهران من الإيجار فقط"                       },
      ],
      correctId: "b",
      explanationCorrectEn: "A family fund needs to cover ALL household expenses — rent, food, school fees, utilities, transport — for 3–6 months. A single income's salary is often not enough.",
      explanationCorrectAr: "يحتاج الصندوق العائلي لتغطية جميع مصروفات المنزل — الإيجار والطعام والرسوم الدراسية والمرافق والمواصلات — لمدة ٣–٦ أشهر. راتب دخل واحد غالباً لا يكفي.",
      explanationWrongEn: "Family fund = total monthly household expenses × 3–6 months. A two-income family may need a larger fund if both incomes are at risk simultaneously.",
      explanationWrongAr: "الصندوق العائلي = إجمالي المصروفات الشهرية للمنزل × ٣–٦ أشهر. الأسرة ذات الدخلين قد تحتاج صندوقاً أكبر إذا كان كلا الدخلين في خطر في وقت واحد.",
    },
    {
      id: "fm-5-q3", nodeId: "fm-5",
      textEn: "The most effective way to reduce financial arguments in a relationship is:",
      textAr: "الطريقة الأكثر فاعلية لتقليل الخلافات المالية في العلاقة:",
      choices: [
        { id: "a", textEn: "Whoever earns more makes all the financial decisions",         textAr: "من يكسب أكثر يتخذ جميع القرارات المالية"           },
        { id: "b", textEn: "Scheduled monthly money conversations with shared goals",      textAr: "محادثات شهرية مجدوَلة عن المال مع أهداف مشتركة"    },
        { id: "c", textEn: "Never discussing money to avoid conflict",                     textAr: "عدم مناقشة المال أبداً لتجنب الخلاف"               },
        { id: "d", textEn: "One partner handles saving; the other handles spending",       textAr: "شريك يتولى الادخار والآخر يتولى الإنفاق"           },
      ],
      correctId: "b",
      explanationCorrectEn: "Regular, calm money meetings — reviewing spending, checking progress on goals, planning ahead — remove surprise and resentment. Make it a ritual, not a conflict.",
      explanationCorrectAr: "اجتماعات المال المنتظمة والهادئة — مراجعة الإنفاق والتحقق من التقدم نحو الأهداف والتخطيط المستقبلي — تزيل المفاجأة والاستياء. اجعلها طقساً لا صراعاً.",
      explanationWrongEn: "Monthly money dates: review the budget together, track goals, discuss next month. Regular communication removes 'money surprises' which are the root cause of most financial arguments.",
      explanationWrongAr: "مواعيد المال الشهرية: راجعا الميزانية معاً وتتبّعا الأهداف وناقشا الشهر القادم. التواصل المنتظم يزيل 'مفاجآت المال' التي هي السبب الجذري لمعظم الخلافات المالية.",
    },
  ],

  // ── Bridge of Borders — bb-1: "Sending Money Home" ───────────────────────────
  "bb-1": [
    {
      id: "bb-1-q1", nodeId: "bb-1",
      textEn: "When comparing remittance services, the two most important factors are:",
      textAr: "عند مقارنة خدمات التحويل، أهم عاملَين هما:",
      choices: [
        { id: "a", textEn: "Brand name and number of physical branch locations",  textAr: "الاسم التجاري وعدد الفروع"                      },
        { id: "b", textEn: "Exchange rate offered and transfer fees charged",     textAr: "سعر الصرف المقدَّم والرسوم المفروضة"             },
        { id: "c", textEn: "Transfer speed and mobile app user ratings",         textAr: "سرعة التحويل وتقييمات تطبيق الجوال"             },
        { id: "d", textEn: "Number of countries supported and loyalty programmes", textAr: "عدد الدول المدعومة وبرامج الولاء"              },
      ],
      correctId: "b",
      explanationCorrectEn: "The rate and fee together determine how much actually arrives at the destination. A service with 'zero fees' but a worse exchange rate may send less money than a service with a small fee and better rate.",
      explanationCorrectAr: "السعر والرسوم معاً يحددان كم يصل فعلاً إلى الوجهة. خدمة بـ'صفر رسوم' لكن بسعر صرف أسوأ قد ترسل أقل من خدمة برسوم صغيرة وسعر أفضل.",
      explanationWrongEn: "Always compare: what amount will arrive? = (amount sent − fee) × exchange rate. A beautiful app with terrible rates sends less money home.",
      explanationWrongAr: "قارن دائماً: كم سيصل؟ = (المبلغ المرسَل − الرسوم) × سعر الصرف. تطبيق جميل بأسعار فظيعة يرسل أموالاً أقل للوطن.",
    },
    {
      id: "bb-1-q2", nodeId: "bb-1",
      textEn: "The 'mid-market rate' (interbank rate) is:",
      textAr: "'السعر الوسطي للسوق' (السعر بين البنوك) هو:",
      choices: [
        { id: "a", textEn: "The rate you get at airport currency exchange booths",           textAr: "السعر الذي تحصل عليه في أكشاك صرف العملة بالمطار"     },
        { id: "b", textEn: "The true midpoint between buying and selling rates, before markup", textAr: "النقطة الوسطى الحقيقية بين أسعار الشراء والبيع قبل الهامش" },
        { id: "c", textEn: "A rate set by the UAE Central Bank for retail customers",       textAr: "سعر تحدده مصرف الإمارات المركزي للعملاء التجزئة"      },
        { id: "d", textEn: "An average of all exchange rates available in the UAE",         textAr: "متوسط جميع أسعار الصرف المتاحة في الإمارات"           },
      ],
      correctId: "b",
      explanationCorrectEn: "The mid-market rate is what banks trade at between themselves — no markup. When you transfer money, providers mark it up. Apps like Wise show you the mid-market rate vs what you're being charged.",
      explanationCorrectAr: "السعر الوسطي للسوق هو ما تتداول به البنوك فيما بينها — بدون هامش. عندما تحوّل مالاً، يضيف مزودو الخدمة هامشاً عليه. تطبيقات مثل Wise تُظهر لك السعر الوسطي مقارنةً بما يُحصَّل منك.",
      explanationWrongEn: "Mid-market = the 'true' exchange rate, no margin. Any spread between the mid-market rate and what you receive IS the hidden fee, even if they advertise 'no transfer fee'.",
      explanationWrongAr: "الوسطي = سعر الصرف 'الحقيقي' بدون هامش. أي فرق بين السعر الوسطي وما تستلمه هو الرسوم المخفية، حتى لو أعلنوا 'بدون رسوم تحويل'.",
    },
    {
      id: "bb-1-q3", nodeId: "bb-1",
      textEn: "Ravi sends AED 2,000 to India monthly. Service A: 22.5 INR/AED, AED 15 fee. Service B: 22.0 INR/AED, no fee. Which service delivers more to the recipient?",
      textAr: "يرسل رافي ٢٬٠٠٠ درهم إلى الهند شهرياً. خدمة أ: ٢٢.٥ روبية/درهم، رسوم ١٥ درهم. خدمة ب: ٢٢.٠ روبية/درهم، بدون رسوم. أيهما يوصل أكثر للمستلم؟",
      choices: [
        { id: "a", textEn: "Service A: (2,000−15) × 22.5 = 44,663 INR",  textAr: "خدمة أ: (٢٬٠٠٠−١٥) × ٢٢.٥ = ٤٤٬٦٦٣ روبية" },
        { id: "b", textEn: "Service B: 2,000 × 22.0 = 44,000 INR",        textAr: "خدمة ب: ٢٬٠٠٠ × ٢٢.٠ = ٤٤٬٠٠٠ روبية"      },
        { id: "c", textEn: "Both deliver the same amount",                 textAr: "كلاهما يوصل نفس المبلغ"                    },
        { id: "d", textEn: "Service B because 'no fee' is always better",  textAr: "خدمة ب لأن 'بدون رسوم' أفضل دائماً"       },
      ],
      correctId: "a",
      explanationCorrectEn: "Service A: (2,000 − 15) × 22.5 = 1,985 × 22.5 = 44,663 INR. Service B: 2,000 × 22.0 = 44,000 INR. Service A delivers 663 more rupees despite the fee. Always calculate total delivered.",
      explanationCorrectAr: "خدمة أ: (٢٬٠٠٠ − ١٥) × ٢٢.٥ = ١٬٩٨٥ × ٢٢.٥ = ٤٤٬٦٦٣ روبية. خدمة ب: ٢٬٠٠٠ × ٢٢.٠ = ٤٤٬٠٠٠ روبية. خدمة أ توصل ٦٦٣ روبية أكثر رغم الرسوم. احسب دائماً المجموع الموصَّل.",
      explanationWrongEn: "'No fee' doesn't mean 'delivers more'. Calculate: (AED sent − fee) × exchange rate = INR received. Service A delivers more despite charging a fee.",
      explanationWrongAr: "'بدون رسوم' لا تعني 'يوصل أكثر'. احسب: (الدرهم المرسَل − الرسوم) × سعر الصرف = الروبية المستلَمة. خدمة أ توصل أكثر رغم فرضها رسوماً.",
    },
  ],

  // ── Bridge of Borders — bb-2: "Exchange Rates & Fees" ────────────────────────
  "bb-2": [
    {
      id: "bb-2-q1", nodeId: "bb-2",
      textEn: "A remittance service advertises 'zero transfer fees' but offers a worse exchange rate. This means:",
      textAr: "خدمة تحويل تُعلن 'صفر رسوم تحويل' لكن تقدم سعر صرف أسوأ. هذا يعني:",
      choices: [
        { id: "a", textEn: "The transfer is completely free — truly zero cost",   textAr: "التحويل مجاني تماماً — تكلفة صفر فعلية"         },
        { id: "b", textEn: "The cost is embedded in the exchange rate spread",    textAr: "التكلفة مضمّنة في هامش سعر الصرف"              },
        { id: "c", textEn: "They make no profit on your transaction",            textAr: "لا يحققون ربحاً على معاملتك"                   },
        { id: "d", textEn: "It is the best option for any transfer amount",      textAr: "هو الخيار الأفضل لأي مبلغ تحويل"               },
      ],
      correctId: "b",
      explanationCorrectEn: "No business transfers money for free. 'Zero fee' services recover their margin by offering exchange rates worse than the mid-market rate. The fee is still there — just hidden.",
      explanationCorrectAr: "لا شركة تحوّل الأموال مجاناً. خدمات 'الرسوم الصفرية' تسترد هامشها بتقديم أسعار صرف أسوأ من السعر الوسطي. الرسوم لا تزال موجودة — فقط مخفية.",
      explanationWrongEn: "'No fee' means no visible fee. The profit comes from giving you a worse exchange rate than the mid-market. Always check: what does the recipient actually get?",
      explanationWrongAr: "'بدون رسوم' تعني لا رسوم مرئية. الربح يأتي من إعطائك سعر صرف أسوأ من السعر الوسطي. تحقق دائماً: ماذا يستلم المستلم فعلاً؟",
    },
    {
      id: "bb-2-q2", nodeId: "bb-2",
      textEn: "Over 12 months, sending AED 3,000/month with a AED 20 fee per transfer — how much do you pay in fees annually?",
      textAr: "على مدى ١٢ شهراً، إرسال ٣٬٠٠٠ درهم شهرياً برسوم ٢٠ درهم لكل تحويل — كم تدفع رسوماً سنوياً؟",
      choices: [
        { id: "a", textEn: "AED 20",  textAr: "٢٠ درهم"  },
        { id: "b", textEn: "AED 120", textAr: "١٢٠ درهم" },
        { id: "c", textEn: "AED 240", textAr: "٢٤٠ درهم" },
        { id: "d", textEn: "AED 480", textAr: "٤٨٠ درهم" },
      ],
      correctId: "c",
      explanationCorrectEn: "AED 20 × 12 = AED 240/year. If a competing service charges AED 8/transfer, you'd save AED 144/year — enough to send an extra AED 144 home.",
      explanationCorrectAr: "٢٠ × ١٢ = ٢٤٠ درهم/سنة. إذا تقاضت خدمة منافسة ٨ درهم/تحويل، ستوفّر ١٤٤ درهم/سنة — يكفي لإرسال ١٤٤ درهم إضافية للوطن.",
      explanationWrongEn: "20 × 12 = 240 per year. Small fees compound into significant amounts. Switching to a service charging AED 5/transfer saves AED 180/year.",
      explanationWrongAr: "٢٠ × ١٢ = ٢٤٠ سنوياً. الرسوم الصغيرة تتراكم لمبالغ كبيرة. التحوّل لخدمة تفرض ٥ درهم/تحويل يوفّر ١٨٠ درهم/سنة.",
    },
    {
      id: "bb-2-q3", nodeId: "bb-2",
      textEn: "Sending money through an unlicensed 'hawala' channel in the UAE is:",
      textAr: "إرسال الأموال عبر قناة 'حوالة' غير مرخصة في الإمارات يُعدّ:",
      choices: [
        { id: "a", textEn: "Perfectly legal and widely used",                         textAr: "قانوني تماماً ومستخدَم على نطاق واسع"             },
        { id: "b", textEn: "Legal only for transfers under AED 3,500",               textAr: "قانوني فقط للتحويلات أقل من ٣٬٥٠٠ درهم"         },
        { id: "c", textEn: "Illegal — all transfers must go through licensed channels", textAr: "غير قانوني — جميع التحويلات يجب أن تمر عبر قنوات مرخصة" },
        { id: "d", textEn: "Allowed only for transfers to certain GCC countries",    textAr: "مسموح به فقط للتحويلات إلى دول خليجية معينة"     },
      ],
      correctId: "c",
      explanationCorrectEn: "All money transfers in the UAE must go through Central Bank-licensed institutions. Using unlicensed channels exposes you to criminal liability, loss of funds, and no legal recourse.",
      explanationCorrectAr: "يجب أن تمر جميع تحويلات الأموال في الإمارات عبر مؤسسات مرخصة من مصرف الإمارات المركزي. استخدام القنوات غير المرخصة يعرّضك للمسؤولية الجنائية وخسارة الأموال وعدم وجود لجوء قانوني.",
      explanationWrongEn: "UAE anti-money laundering laws require all transfers to go through licensed exchange houses or banks. Unlicensed hawala networks are illegal — and if something goes wrong, there's no protection.",
      explanationWrongAr: "تتطلب قوانين مكافحة غسيل الأموال الإماراتية مرور جميع التحويلات عبر بيوت صرف أو بنوك مرخصة. شبكات الحوالة غير المرخصة غير قانونية — وإذا سار الأمر بشكل خاطئ، لا حماية.",
    },
  ],

  // ── Bridge of Borders — bb-5: "Remittance Boss" (boss) ───────────────────────
  "bb-5": [
    {
      id: "bb-5-q1", nodeId: "bb-5",
      textEn: "Ravi switches from a service charging AED 25/transfer to one charging AED 8/transfer (same exchange rate). He sends monthly. Annual saving?",
      textAr: "ينتقل رافي من خدمة تفرض ٢٥ درهم/تحويل إلى أخرى تفرض ٨ درهم/تحويل (نفس سعر الصرف). يرسل شهرياً. التوفير السنوي؟",
      choices: [
        { id: "a", textEn: "AED 17",  textAr: "١٧ درهم"  },
        { id: "b", textEn: "AED 96",  textAr: "٩٦ درهم"  },
        { id: "c", textEn: "AED 204", textAr: "٢٠٤ درهم" },
        { id: "d", textEn: "AED 300", textAr: "٣٠٠ درهم" },
      ],
      correctId: "c",
      explanationCorrectEn: "(AED 25 − AED 8) × 12 = AED 17 × 12 = AED 204/year. A 30-minute comparison exercise that pays AED 204 in annual savings — better return than most savings accounts.",
      explanationCorrectAr: "(٢٥ − ٨) × ١٢ = ١٧ × ١٢ = ٢٠٤ درهم/سنة. تمرين مقارنة لمدة ٣٠ دقيقة يدفع ٢٠٤ درهم في توفيرات سنوية — عائد أفضل من معظم حسابات الادخار.",
      explanationWrongEn: "(25−8) = 17 saved per transfer. × 12 months = AED 204/year saved. Small comparison, real money.",
      explanationWrongAr: "(٢٥−٨) = ١٧ درهماً توفيراً لكل تحويل. × ١٢ شهراً = ٢٠٤ درهم/سنة توفيراً. مقارنة صغيرة، مال حقيقي.",
    },
    {
      id: "bb-5-q2", nodeId: "bb-5",
      textEn: "Which remittance service type typically offers the most competitive exchange rates in the UAE?",
      textAr: "أي نوع من خدمات التحويل يقدم عادةً أكثر أسعار الصرف تنافسية في الإمارات؟",
      choices: [
        { id: "a", textEn: "Airport currency exchange booths",             textAr: "أكشاك صرف العملة في المطار"                   },
        { id: "b", textEn: "Luxury hotel front desks",                    textAr: "مكاتب استقبال الفنادق الفاخرة"                 },
        { id: "c", textEn: "Licensed digital apps and exchange houses",   textAr: "التطبيقات الرقمية المرخصة وبيوت الصرف"         },
        { id: "d", textEn: "Convenience stores with money transfer kiosks", textAr: "محلات الراحة التي بها أكشاك تحويل الأموال"   },
      ],
      correctId: "c",
      explanationCorrectEn: "Licensed digital remittance apps (Wise, Remitly, Al Ansari app, etc.) and reputable UAE exchange houses compete fiercely on rates. Airports and hotels are always the worst due to captive audiences.",
      explanationCorrectAr: "تطبيقات التحويل الرقمية المرخصة (Wise وRemitly وتطبيق الأنصاري وغيرها) وبيوت الصرف الإماراتية المرموقة تتنافس بشدة على الأسعار. المطارات والفنادق دائماً الأسوأ بسبب جماهير مقيّدة.",
      explanationWrongEn: "Airport booths have the worst rates — you're captive. Licensed UAE exchange houses and digital apps compete fiercely, offering rates close to the mid-market rate.",
      explanationWrongAr: "أكشاك المطار لديها أسوأ الأسعار — أنت مقيّد. بيوت الصرف الإماراتية المرخصة والتطبيقات الرقمية تتنافس بشدة، وتقدم أسعاراً قريبة من السعر الوسطي.",
    },
    {
      id: "bb-5-q3", nodeId: "bb-5",
      textEn: "FX risk when sending money internationally means:",
      textAr: "مخاطر العملة الأجنبية عند إرسال الأموال دولياً تعني:",
      choices: [
        { id: "a", textEn: "The risk that your transfer gets physically lost",               textAr: "خطر فقدان تحويلك مادياً"                               },
        { id: "b", textEn: "The risk the exchange rate changes between initiation and completion", textAr: "خطر تغيّر سعر الصرف بين الإرسال والاستلام"           },
        { id: "c", textEn: "The fee charged for the foreign exchange transaction",           textAr: "الرسوم المفروضة على معاملة الصرف الأجنبي"              },
        { id: "d", textEn: "The risk that the recipient's country rejects the currency",    textAr: "خطر رفض بلد المستلم للعملة"                            },
      ],
      correctId: "b",
      explanationCorrectEn: "FX risk: if you send at 22.5 INR/AED but the rate shifts to 21.8 before completion, the recipient gets less. Apps offering 'rate lock' or instant transfer eliminate this risk.",
      explanationCorrectAr: "مخاطر العملة: إذا أرسلت بسعر ٢٢.٥ روبية/درهم لكن السعر انتقل إلى ٢١.٨ قبل الاكتمال، يستلم المستلم أقل. التطبيقات التي تقدم 'تثبيت السعر' أو التحويل الفوري تزيل هذه المخاطرة.",
      explanationWrongEn: "FX risk = the exchange rate moving against you between order and execution. Fix it with instant transfers or rate-lock features on transfer platforms.",
      explanationWrongAr: "مخاطر العملة = تحرّك سعر الصرف ضدك بين الطلب والتنفيذ. تخلّص منه بالتحويلات الفورية أو ميزات تثبيت السعر على منصات التحويل.",
    },
  ],
};
